act_code: '60701'
requisite: Решение акима Успенского сельского округа Успенского района Павлодарской области от 6 октября 2011 года № 22. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 7 октября 2011 года № 12-12-109. Утратило силу решением акима Успенского сельского округа Успенского района Павлодарской области от 29 октября 2014 года № 3 (вводится в действие со дня его подписания)
title:
  rus: Об утверждении регламента оказания государственной услуги
  kaz: Мемлекеттік қызмет көрсету регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2011-10-06
approved_by:
- '164011008002'
version_date:
  kaz: 2011-10-06
  rus: 2011-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/60701/kaz/06.10.2011
  rus: https://zan.gov.kz/client/#!/doc/60701/rus/06.10.2011
