act_code: '136021'
requisite: Решение маслихата Павлодарской области от 8 ноября 2019 года № 418/35. Зарегистрировано Департаментом юстиции Павлодарской области 15 ноября 2019 года № 6604. Утратило силу решением Павлодарского областного маслихата от 26 декабря 2025 года № 241/27 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Павлодарской области
  kaz: Павлодар облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-08
approved_by:
- '164000000002'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/136021/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/136021/rus/14.04.2022
caused_by:
  code: '166746'
  requisite: Решение Павлодарского областного маслихата от 14 апреля 2022 года № 147/12. Зарегистрировано в Министерстве юстиции Республики Казахстан 19 апреля 2022 года № 27645. Утратило силу решением Павлодарского областного маслихата от 26 декабря 2025 года № 241/27 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата Павлодарской области от 8 ноября 2019 года № 418/35 «Об определении размера и перечня категорий получателей жилищных сертификатов по Павлодарской области»
    kaz: Павлодар облыстық мәслихатының 2019 жылғы 8 қарашадағы № 418/35 «Павлодар облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166746/rus
