act_code: '136021'
requisite: Решение маслихата Павлодарской области от 8 ноября 2019 года № 418/35. Зарегистрировано Департаментом юстиции Павлодарской области 15 ноября 2019 года № 6604. Утратило силу решением Павлодарского областного маслихата от 26 декабря 2025 года № 241/27 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Павлодарской области
  kaz: Павлодар облысы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-08
approved_by:
- '164000000002'
version_date:
  kaz: 2019-11-08
  rus: 2019-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/136021/kaz/08.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136021/rus/08.11.2019
