act_code: '78064'
requisite: Решение маслихата города Аксу Павлодарской области от 20 февраля 2014 года № 196/28. Зарегистрировано Департаментом юстиции Павлодарской области 18 марта 2014 года № 3731. Утратило силу решением маслихата города Аксу Павлодарской области от 8 июля 2016 года № 43/5
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Аксу
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ақсу қаласының мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-20
approved_by:
- '164004000002'
version_date:
  kaz: 2015-07-22
  rus: 2015-07-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/78064/kaz/22.07.2015
  rus: https://zan.gov.kz/client/#!/doc/78064/rus/22.07.2015
caused_by:
  code: '92686'
  requisite: Решение маслихата города Аксу Павлодарской области от 22 июля 2015 года № 358/47. Зарегистрировано Департаментом юстиции Павлодарской области 11 августа 2015 года № 4654. Утратило силу решением маслихата города Аксу Павлодарской области от 8 июля 2016 года № 43/5
  title:
    rus: О внесении изменения и дополнений в решение Аксуского городского маслихата от 20 февраля 2014 года № 196/28 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан города Аксу»
    kaz: Ақсу қалалық мәслихатының 2014 жылғы 20 ақпандағы «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ақсу қаласының мұқтаж  азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» № 196/28 шешіміне өзгеріс пен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/92686/rus
