act_code: '3505'
requisite: Решение акима Павлодарской области от 11 июня 1999 года № 153. Зарегистрировано Управлением юстиции Павлодарской области 7 июля 1999 года за № 173
title:
  rus: Об открытии государственного учреждения «Областная специализированная кадетская школа-интернат»
  kaz: «Облыстық мамандандырылған кадет мектеп - интернаты» мемлекеттік мекемесін ашу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-06-10
approved_by:
- '164000000003'
version_date:
  kaz: 1999-06-10
  rus: 1999-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/3505/kaz/10.06.1999
  rus: https://zan.gov.kz/client/#!/doc/3505/rus/10.06.1999
