act_code: '48968'
requisite: Решение акима Караобинского сельского округа Актогайского района Павлодарской области от 9 ноября 2009 года № 2. Зарегистрировано Управлением юстиции Актогайского района Павлодарской области 2 декабря 2009 года № 12-4-70
title:
  rus: О присвоении наименования улицам в селах Красная поляна, Спартак, Исантерек, Жана-ауыл Караобинского сельского округа
  kaz: Қараоба ауылдық округінің Красная поляна, Спартак, Исантерек, Жана-ауыл аулындағы көшесіне ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-09
approved_by:
- '164003006001'
version_date:
  kaz: 2009-11-09
  rus: 2009-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/48968/kaz/09.11.2009
  rus: https://zan.gov.kz/client/#!/doc/48968/rus/09.11.2009
