act_code: '64383'
requisite: Решение маслихата Железинского района Павлодарской области от 29 февраля 2012 года № 12-5/2. Зарегистрировано Департаментом юстиции Павлодарской области 29 марта 2012 года N 12-6-139. Утратило силу решением маслихата Железинского района Павлодарской области от 14 ноября 2013 года № 162-5/21
title:
  rus: Об установлении единых ставок фиксированного налога по Железинскому району
  kaz: Железинка ауданы бойынша тіркелген салықтың бірыңғай мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-29
approved_by:
- '164006000002'
version_date:
  kaz: 2012-02-29
  rus: 2012-02-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/64383/kaz/29.02.2012
  rus: https://zan.gov.kz/client/#!/doc/64383/rus/29.02.2012
