act_code: '189775'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 6 декабря 2023 года № 3/10. Зарегистрировано в Департаменте юстиции Павлодарской области 11 декабря 2023 года № 7438-14. Утратило силу решением маслихата района Тереңкөл Павлодарской области от 24 июня 2026 года № 3/47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан района Тереңкөл
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Тереңкөл ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-06
approved_by:
- '164008000002'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/189775/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189775/rus/06.12.2023
