act_code: '71321'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 11 февраля 2013 года № 4/13. Зарегистрировано Департаментом юстиции Павлодарской области 28 февраля 2013 года № 3460
title:
  rus: О назначении социальной помощи отдельным категориям нуждающихся граждан Лебяжинского района на 2013 год
  kaz: Лебяжі ауданы бойынша 2013 жылға арналған мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-11
approved_by:
- '164009000002'
version_date:
  kaz: 2014-03-05
  rus: 2014-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/71321/kaz/05.03.2014
  rus: https://zan.gov.kz/client/#!/doc/71321/rus/05.03.2014
