act_code: '71321'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 11 февраля 2013 года № 4/13. Зарегистрировано Департаментом юстиции Павлодарской области 28 февраля 2013 года № 3460
title:
  rus: О назначении социальной помощи отдельным категориям нуждающихся граждан Лебяжинского района на 2013 год
  kaz: Лебяжі ауданы бойынша 2013 жылға арналған мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-11
approved_by:
- '164009000002'
version_date:
  kaz: 2013-04-03
  rus: 2013-04-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/71321/kaz/03.04.2013
  rus: https://zan.gov.kz/client/#!/doc/71321/rus/03.04.2013
caused_by:
  code: '72176'
  requisite: Решение маслихата Лебяжинского района Павлодарской области от 03 апреля 2013 года № 3/15. Зарегистрировано Департаментом юстиции Павлодарской области 22 апреля 2013 года № 3511
  title:
    rus: О внесении изменения и дополнения в решение Лебяжинского районного маслихата (XIII внеочердная сессия V созыва) от 11 февраля 2013 года № 4/13 "О назначении социальной помощи отдельным категориям нуждающихся граждан Лебяжинского района на 2013 год"
    kaz: Лебяжі аудандық мәслихаттың (V сайланған XIII кезектен тыс сессиясы) 2013 жылғы 11 ақпандағы "Лебяжі ауданы бойынша 2013 жылға арналған мұқтаж азаматтардың жекелеген санаттарына әлеуметтік көмек тағайындау туралы" № 4/13 шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72176/rus
