act_code: '183965'
requisite: Решение акима Кызылжарского сельского округа города Аксу Павлодарской области от 14 июля 2023 года № 1-03/05
title:
  rus: О переименовании некоторых улиц села Кызылжар Кызылжарского сельского округа города Аксу
  kaz: Ақсу қаласы Қызылжар ауылдық округі Қызылжар ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-14
approved_by:
- '164004013002'
version_date:
  kaz: 2023-07-14
  rus: 2023-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/183965/kaz/14.07.2023
  rus: https://zan.gov.kz/client/#!/doc/183965/rus/14.07.2023
