act_code: '158010'
requisite: Решение Успенского районного маслихата Павлодарской области от 12 августа 2021 года № 49/7
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Успенскому району на 2021 - 2022 годы
  kaz: Успен ауданы бойынша 2021 - 2022 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2021-08-12
approved_by:
- '164011000002'
version_date:
  kaz: 2021-08-12
  rus: 2021-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/158010/kaz/12.08.2021
  rus: https://zan.gov.kz/client/#!/doc/158010/rus/12.08.2021
