act_code: '162506'
requisite: Решение Железинского районного маслихата Павлодарской области от 29 декабря 2021 года № 102/7
title:
  rus: О бюджете сельских округов Железинского района на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164006000002'
version_date:
  kaz: 2022-10-19
  rus: 2022-10-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/162506/kaz/19.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162506/rus/19.10.2022
caused_by:
  code: '173037'
  requisite: Решение Железинского районного маслихата Павлодарской области от 19 октября 2022 года № 192/7
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 29 декабря 2021 года № 102/7 «О бюджете сельских округов Железинского района на 2022-2024 годы»
    kaz: Железин аудандық мәслихатының 2021 жылғы 29 желтоқсандағы «2022-2024 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы» № 102/7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173037/rus
