act_code: '65978'
requisite: Решение акима Козыкеткенского аульного округа Успенского района Павлодарской области от 08 мая 2012 года № 1. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 07 июня 2012 года № 12-12-132
title:
  rus: О присвоении наименований улицам сел, входящих в состав Козыкеткенского аульного округа Успенского района
  kaz: Успен ауданының Қозыкеткен ауылдық округінің құрамына кіретін ауыл көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-08
approved_by:
- '164011007001'
version_date:
  kaz: 2012-05-08
  rus: 2012-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/65978/kaz/08.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65978/rus/08.05.2012
