act_code: '136016'
requisite: Решение маслихата Павлодарской области от 8 ноября 2019 года № 417/35. Зарегистрировано Департаментом юстиции Павлодарской области 15 ноября 2019 года № 6602
title:
  rus: О ставках платы за лесные пользования на участках государственного лесного фонда (за исключением ставок за древесину, отпускаемую на корню) Павлодарской области
  kaz: Павлодар облысының мемлекеттік орман қоры учаскелерінде орманды пайдаланғаны үшін төлемақы мөлшерлемелері (түбiрiмен босатылатын сүрек үшiн белгiленетiн мөлшерлемелерді қоспағанда) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-08
approved_by:
- '164000000002'
version_date:
  kaz: 2019-11-08
  rus: 2019-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/136016/kaz/08.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136016/rus/08.11.2019
