act_code: '150990'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 25 декабря 2020 года № 369/65. Зарегистрировано Департаментом юстиции Павлодарской области 30 декабря 2020 года № 7142
title:
  rus: Об установлении повышенных окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта, ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими и работающим в сельских населенных пунктах Баянаульского района, а также указанным специалистам, работающим в государственных организациях, финансируемых из местного бюджета
  kaz: Азаматтық қызметшілер болып табылатын және Баянауыл ауданының ауылдық елді мекендерінде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға, сондай-ақ жергілікті бюджеттен қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін аталған мамандарға жоғарылатылған айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '164005000002'
version_date:
  kaz: 2020-12-25
  rus: 2020-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/150990/kaz/25.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150990/rus/25.12.2020
