act_code: '41761'
requisite: Павлодар облысы Павлодар қаласы Мойылды ауылдық әкімінің 2008 жылғы 17 қыркүйектегі № 10 шешімі. Павлодар облысы Павлодар қаласының Әділет басқармасында 2008 жылғы 2 қазанда № 12-1-126 тіркелген. Күші жойылды - Павлодар облысы Павлодар қаласы Мойылды ауылдық әкімінің 2009 жылғы 5 маусымдағы № 6 шешімімен
title:
  rus: '"Мойылды ауылы әкімінің аппараты" мемлекеттік мекемесі бойынша мемлекеттік қызметтер көрсету стандарттарын бекіту туралы'
  kaz: '"Мойылды ауылы әкімінің аппараты" мемлекеттік мекемесі бойынша мемлекеттік қызметтер көрсету стандарттарын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
- СТНД
approved_on: 2008-09-17
approved_by:
- '164002000001'
version_date:
  kaz: 2008-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/41761/kaz/17.09.2008
