act_code: '51656'
requisite: Решение акима поселка Аксу Аксуского района Павлодарской области от 5 марта 2010 года № 1-03/5. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 9 апреля 2010 года № 12-2-134
title:
  rus: О переименовании улицы Пионерской поселка Аксу
  kaz: Ақсу кентінің Пионерская көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-05
approved_by:
- '164004001001'
version_date:
  kaz: 2010-03-05
  rus: 2010-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/51656/kaz/05.03.2010
  rus: https://zan.gov.kz/client/#!/doc/51656/rus/05.03.2010
