act_code: '175700'
requisite: Решение Иртышского районного маслихата Павлодарской области от 21 декабря 2022 года № 105-26-7
title:
  rus: Об Иртышском районном бюджете на 2023 – 2025 годы
  kaz: 2023 – 2025 жылдарға арналған Ертіс аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '164007000002'
version_date:
  kaz: 2022-12-21
  rus: 2022-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/175700/kaz/21.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175700/rus/21.12.2022
