act_code: '45576'
requisite: Решение маслихата города Экибастуза Павлодарской области от 17 марта 2009 года № 159/15. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 30 апреля 2009 года за № 12-3-228. Утратило силу решением маслихата города Экибастуза Павлодарской области от 12 апреля 2016 года № 13/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка и мест для проведения мирных собраний, митингов и пикетов
  kaz: Бейбіт жиналыстар, митингтер, пикеттер өткізу үшін тәртібі мен орнын қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-17
approved_by:
- '164013000002'
version_date:
  kaz: 2009-03-17
  rus: 2009-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/45576/kaz/17.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45576/rus/17.03.2009
