act_code: '224080'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 9 апреля 2026 года № 430/46
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Баянаульского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Баянауыл ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-04-09
approved_by:
- '164005000002'
version_date:
  kaz: 2026-09-08
  rus: 2026-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/224080/kaz/08.09.2026
  rus: https://zan.gov.kz/client/#!/doc/224080/rus/08.09.2026
caused_by:
  code: '229995'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 8 сентября 2026 года № 501/54
  title:
    rus: О внесении изменения в решение Баянаульского районного маслихата от 09 апреля 2026 года № 430/46 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Баянаульского района»
    kaz: Баянауыл аудандық маслихатының 2026 жылғы 09 сәуірдегі Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Баянауыл ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы № 430/46 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229995/rus
