act_code: '127919'
requisite: Решение маслихата Железинского района Павлодарской области от 21 ноября 2018 года № 296/6. Зарегистрировано Департаментом юстиции Павлодарской области 29 декабря 2018 года № 6213
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Железинского района
  kaz: Железин ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-11-21
approved_by:
- '164006000002'
version_date:
  kaz: 2018-11-21
  rus: 2018-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/127919/kaz/21.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127919/rus/21.11.2018
