act_code: '127919'
requisite: Решение маслихата Железинского района Павлодарской области от 21 ноября 2018 года № 296/6. Зарегистрировано Департаментом юстиции Павлодарской области 29 декабря 2018 года № 6213
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов Железинского района
  kaz: Железин ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-11-21
approved_by:
- '164006000002'
version_date:
  kaz: 2021-12-02
  rus: 2021-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/127919/kaz/02.12.2021
  rus: https://zan.gov.kz/client/#!/doc/127919/rus/02.12.2021
caused_by:
  code: '161051'
  requisite: Решение Железинского районного маслихата Павлодарской области от 2 декабря 2021 года № 79/7
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 21 ноября 2018 года № 296/6 «Об утверждении регламента местного сообщества сельских округов Железинского района»
    kaz: Железин аудандық мәслихатының 2018 жылғы 21 қарашадағы «Железин ауданының ауылдық округтерінің жергілікті қоғамдастық регламентін бекіту туралы» № 296/6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161051/rus
