act_code: '133184'
requisite: Решение акима Теренкольского сельского округа района Тереңкөл Павлодарской области от 3 июля 2019 года № 40. Зарегистрировано Департаментом юстиции Павлодарской области 9 июля 2019 года № 6469
title:
  rus: Об установлении публичного сервитута в Теренкольском сельском округе района Тереңкөл
  kaz: Тереңкөл ауданы Тереңкөл ауылдық округінде қауымдық сервитут орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-03
approved_by:
- '164008001002'
version_date:
  kaz: 2019-07-03
  rus: 2019-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/133184/kaz/03.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133184/rus/03.07.2019
