act_code: '3185'
requisite: Решение акима Павлодарской области от 1 апреля 1999 года № 50. Зарегистрировано Управлением юстиции Павлодарской области 13 апреля 1999 года за № 132
title:
  rus: Об областном конкурсе по качеству образовательных услуг среди общеобразовательных и профессиональных школ
  kaz: Жалпы білім беретін және кәсіптік мектептер арасындағы білім сапасы жөніндегі облыстық конкурс туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-31
approved_by:
- '164000000003'
version_date:
  kaz: 1999-03-31
  rus: 1999-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/3185/kaz/31.03.1999
  rus: https://zan.gov.kz/client/#!/doc/3185/rus/31.03.1999
