act_code: '217659'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 28 ноября 2025 года № 292/37
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги)
  kaz: Автотұрақтардың (паркингтердің) санаттарын белгілеу және автотұрақтарға (паркингтерге)бөлінген жерлерге салықтың базалық ставкаларын ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-28
approved_by:
- '164013000002'
version_date:
  kaz: 2025-11-28
  rus: 2025-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/217659/kaz/28.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217659/rus/28.11.2025
