act_code: '115982'
requisite: Решение акима Шакатского сельского округа Павлодарского района Павлодарской области от 3 ноября 2017 года № 1-21-08. Зарегистрировано Департаментом юстиции Павлодарской области 16 ноября 2017 года № 5685. Утратило силу решением акима Шакатского сельского округа Павлодарского района Павлодарской области от 6 декабря 2018 года № 1-03-11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий на территории некоторых улиц села Маралды Шакатского сельского округа Павлодарского района
  kaz: Павлодар ауданы Шақат ауылдық округі Маралды ауылының кейбір көшелерінің аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-03
approved_by:
- '164014012002'
version_date:
  kaz: 2017-11-03
  rus: 2017-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/115982/kaz/03.11.2017
  rus: https://zan.gov.kz/client/#!/doc/115982/rus/03.11.2017
