act_code: '25905'
requisite: Лебяжі аудандық мәслихатының 2005 жылғы 27 қазандағы № 3/18 шешімі. Лебяжі ауданының әділет басқармасында 2005 жылғы 24 қарашада № 12-9-15 тіркелді
title:
  rus: «Лебяжі ауданының жасыл екпелерін қорғау және көріктендіру Ережесі туралы»
  kaz: «Лебяжі ауданының жасыл екпелерін қорғау және көріктендіру Ережесі туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-10-27
approved_by:
- '164009000002'
version_date:
  kaz: 2005-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/25905/kaz/27.10.2005
