act_code: '204990'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 27 декабря 2024 года № 1/26
title:
  rus: О бюджете сельских округов района Тереңкөл на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тереңкөл ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164008000002'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/204990/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/204990/rus/26.11.2025
caused_by:
  code: '217392'
  requisite: Решение маслихата района Тереңкөл Павлодарской области от 26 ноября 2025 года № 1/36
  title:
    rus: О внесении изменений в решение маслихата района Тереңкөл от 27 декабря 2024 года № 1/26 «О бюджете сельских округов района Тереңкөл на 2025-2027 годы»
    kaz: Тереңкөл аудандық мәслихатының 2024 жылғы 27 желтоқсандағы «2025 -2027 жылдарға арналған Тереңкөл ауданының ауылдық округтерінің бюджеті туралы» № 1/26 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217392/rus
