act_code: '1259'
requisite: Решение Акима Павлодарской области от 25 августа 1998 года № 275. Зарегистрировано Управлением юстиции Павлодарской области 31 августа 1998 года за № 68
title:
  rus: О частичном изменений функций, структуры и штатов отдельных департаментов области
  kaz: Облыстың жекелеген департаменттерінің қызметтеріндегі, құрылымдары мен штаттарындағы ішінара өзгерістер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-08-24
approved_by:
- '164000000003'
version_date:
  kaz: 1998-08-24
  rus: 1998-08-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/1259/kaz/24.08.1998
  rus: https://zan.gov.kz/client/#!/doc/1259/rus/24.08.1998
