act_code: '224790'
requisite: Решение акима Актогайского района Павлодарской области от 30 апреля 2026 года № 1. Отменено решением акима Актогайского района Павлодарской области от 22 мая 2026 года № 2-р (вводится в действие со дня подписания и распространяет свое действие на отношения, возникшие  с 26.04.2026)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба в Актогайскогом районе
  kaz: Ақтоғай ауданында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-30
approved_by:
- '164003000003'
version_date:
  kaz: 2026-04-30
  rus: 2026-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/224790/kaz/30.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224790/rus/30.04.2026
