act_code: '17307'
requisite: Решение маслихата Павлодарской области от 19 июня 2003 года № 135/27. Зарегистрировано Управлением юстиции Павлодарской области 2 июля 2003 года за № 1916
title:
  rus: О плане мероприятий на 2003 год по реализации программы экономического сотрудничества между Павлодарской областью и приграничными областями Российской Федерации на 2001 - 2003 годы
  kaz: Павлодар облысы мен Ресей Федерациясының шекаралас облыстары арасындағы 2001 - 2003 жылдарға арналған экономикалық ынтымақтастық бағдарламасын iске асыру жөнiндегi 2003 жылға арналған iс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-18
approved_by:
- '164000000002'
version_date:
  kaz: 2003-06-18
  rus: 2003-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/17307/kaz/18.06.2003
  rus: https://zan.gov.kz/client/#!/doc/17307/rus/18.06.2003
