act_code: '42968'
requisite: Решение маслихата Павлодарской области от 18 декабря 2008 года N 146/11. Зарегистрировано Департаментом юстиции Павлодарской области 24 декабря 2008 года за N 3128. Утратило силу решением маслихата Павлодарской области от 16 февраля 2011 года N 352/32
title:
  rus: Об областном бюджете на 2009 год
  kaz: 2009 жылға арналған облыстық бюджет
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-17
approved_by:
- '164000000002'
version_date:
  kaz: 2009-04-22
  rus: 2009-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/42968/kaz/22.04.2009
  rus: https://zan.gov.kz/client/#!/doc/42968/rus/22.04.2009
caused_by:
  code: '45495'
  requisite: Решение маслихата Павлодарской области от 22 апреля 2009 года № 191/15. Зарегистрировано Департаментом юстиции 23 апреля 2009 года за № 3136. Утратило силу решением маслихата Павлодарской области от 16 февраля 2011 года № 352/32
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата (XI сессия, IV созыв) от 18 декабря 2008 года № 146/11 "Об областном бюджете на 2009 год"
    kaz: Облыстық мәслихаттың (IV сайланған XI сессиясы) 2008 жылғы 18 желтоқсандағы "2009 жылға арналған облыстық бюджеті туралы" № 146/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/45495/rus
