act_code: '190973'
requisite: Решение маслихата района Аққулы Павлодарской области от 27 декабря 2023 года № 58/15
title:
  rus: О бюджетах сельских округов района Аққулы на 2024 - 2026 годы
  kaz: Аққулы ауданының ауылдық округтерінің 2024 - 2026 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '164009000002'
version_date:
  kaz: 2024-07-18
  rus: 2024-07-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/190973/kaz/18.07.2024
  rus: https://zan.gov.kz/client/#!/doc/190973/rus/18.07.2024
caused_by:
  code: '198856'
  requisite: Решение маслихата района Аққулы Павлодарской области от 18 июля 2024 года № 100/20
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 27 декабря 2023 года № 58/15 «О бюджетах сельских округов района Аққулы на 2024-2026 годы»
    kaz: Аққулы аудандық мәслихатының 2023 жылғы 27 желтоқсандағы «Аққулы ауданының ауылдық округтерінің 2024 - 2026 жылдарға арналған бюджеттері туралы» № 58/15 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198856/rus
