act_code: '190942'
requisite: Решение Иртышского районного маслихата Павлодарской области от 27 декабря 2023 года № 48-14-8
title:
  rus: О бюджете сёл и сельских округов Иртышского района на 2024 – 2026 годы
  kaz: 2024 – 2026 жылдарға арналған Ертіс ауданының ауылдар және ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '164007000002'
version_date:
  kaz: 2024-08-14
  rus: 2024-08-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/190942/kaz/14.08.2024
  rus: https://zan.gov.kz/client/#!/doc/190942/rus/14.08.2024
caused_by:
  code: '199724'
  requisite: Решение Иртышского районного маслихата Павлодарской области от 14 августа 2024 года № 87-24-8
  title:
    rus: О внесении изменений в решение Иртышского районного маслихата от 27 декабря 2023 года № 48-14-8 «О бюджете сёл и сельских округов Иртышского района на 2024 – 2026 годы»
    kaz: Ертіс аудандық мәслихатының 2023 жылғы 27 желтоқсандағы «2024 – 2026 жылдарға арналған Ертіс ауданының ауылдар және ауылдық округтерінің бюджеті туралы» № 48-14-8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199724/rus
