act_code: '96702'
requisite: Решение маслихата города Павлодара Павлодарской области от 24 декабря 2015 года № 455/61. Зарегистрировано Департаментом юстиции Павлодарской области 29 декабря 2015 года № 4866
title:
  rus: О бюджете города Павлодара на 2016 - 2018 годы
  kaz: Павлодар қаласының 2016 - 2018 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-24
approved_by:
- '164002000002'
version_date:
  kaz: 2015-12-24
  rus: 2015-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/96702/kaz/24.12.2015
  rus: https://zan.gov.kz/client/#!/doc/96702/rus/24.12.2015
