act_code: '24566'
requisite: Решение Маслихата Павлодарской области от 30 мая 2005 года № 47/12. Зарегистрировано Департаментом юстиции Павлодарской области 24 июня 2005 года за № 3038
title:
  rus: О программе профилактики правонарушений и борьбы с преступностью в области на 2005 - 2007 годы
  kaz: Облыста құқық бұзушылықтың алдын алу және қылмысқа қарсы күрестiң 2005 - 2007 жылдарға арналған бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2005-05-30
approved_by:
- '164000000002'
version_date:
  kaz: 2005-05-30
  rus: 2005-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/24566/kaz/30.05.2005
  rus: https://zan.gov.kz/client/#!/doc/24566/rus/30.05.2005
