act_code: '28139'
requisite: Решение Экибастузского городского Маслихата от 25 апреля 2006 года № 326/25. Зарегистрировано Управлением юстиции города Экибастуза 29 мая 2006 года № 12-3-60
title:
  rus: О Правилах содержания домашних животных на территории Экибастузского региона
  kaz: Екібастұз өңірінің аумағында үй жануарларын ұстау Қағидасы туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-04-25
approved_by:
- '164013000002'
version_date:
  kaz: 2006-04-25
  rus: 2006-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/28139/kaz/25.04.2006
  rus: https://zan.gov.kz/client/#!/doc/28139/rus/25.04.2006
