act_code: '40657'
requisite: Решение акима Щербактинского района Павлодарской области от 16 июня 2008 года № 44-1. Зарегистрировано Управлением юстиции Щербактинского района Павлодарской области 30 июня 2008 года № 12-13-56
title:
  rus: О переименовании улицы Калинина в улицу Бауыржан Момышулы
  kaz: О переименовании улицы Калинина в улицу Бауыржан Момышулы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-16
approved_by:
- '164012000003'
version_date:
  rus: 2008-06-16
source:
  rus: https://zan.gov.kz/client/#!/doc/40657/rus/16.06.2008
