act_code: '17134'
requisite: Решение маслихата Павлодарской области от 24 июня 2002 года (XX сессия, II созыва) № 52/20. Зарегистрировано Управлением юстиции Павлодарской области 8 июля 2002 года за № 1305
title:
  rus: Об областной программе функционирования и развития языков на 2002 – 2003 годы «Ана тілі»
  kaz: Тілдерді қолдану мен дамытудың 2002 – 2003 жылдарға арналған «Ана тілі» облыстық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-06-23
approved_by:
- '164000000002'
version_date:
  kaz: 2002-06-23
  rus: 2002-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/17134/kaz/23.06.2002
  rus: https://zan.gov.kz/client/#!/doc/17134/rus/23.06.2002
