act_code: '116717'
requisite: Решение маслихата Павлодарской области от 14 декабря 2017 года № 175/18. Зарегистрировано Департаментом юстиции Павлодарской области 15 декабря 2017 года № 5741
title:
  rus: Об областном бюджете на 2018 - 2020 годы
  kaz: 2018 - 2020  жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-14
approved_by:
- '164000000002'
version_date:
  kaz: 2018-06-14
  rus: 2018-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/116717/kaz/14.06.2018
  rus: https://zan.gov.kz/client/#!/doc/116717/rus/14.06.2018
caused_by:
  code: '122564'
  requisite: Решение маслихата Павлодарской области от 14 июня 2018 года № 227/22. Зарегистрировано Департаментом юстиции Павлодарской области 18 июня 2018 года № 5994
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата от 14 декабря 2017 года № 175/18 «Об областном бюджете на 2018 - 2020 годы»
    kaz: Облыстық мәслихаттың 2017 жылғы 14 желтоқсандағы «2018 - 2020 жылдарға арналған облыстық бюджет туралы» № 175/18  шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122564/rus
