act_code: '126806'
requisite: Решение акима Шолаксорского сельского округа Актогайского района Павлодарской области от 29 ноября 2018 года № 1. Зарегистрировано Департаментом юстиции Павлодарской области 10 декабря 2018 года № 6145
title:
  rus: О переименовании некоторых улиц в селе Шолаксор Шолаксорского сельского округа Актогайского района
  kaz: Ақтоғай ауданы Шолақсор ауылдық округінің Шолақсор ауылындағы кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-29
approved_by:
- '164003003002'
version_date:
  kaz: 2018-11-29
  rus: 2018-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/126806/kaz/29.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126806/rus/29.11.2018
