act_code: '117139'
requisite: Решение маслихата города Экибастуза Павлодарской области от 26 декабря 2017 года № 201/25. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2017 года № 5761
title:
  rus: Об Экибастузском городском бюджете на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '164013000002'
version_date:
  kaz: 2018-09-11
  rus: 2018-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/117139/kaz/11.09.2018
  rus: https://zan.gov.kz/client/#!/doc/117139/rus/11.09.2018
caused_by:
  code: '125244'
  requisite: Решение маслихата города Экибастуза Павлодарской области от 11 сентября 2018 года № 288/34. Зарегистрировано Департаментом юстиции Павлодарской области 11 октября 2018 года № 6081
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 26 декабря 2017 года № 201/25 «Об Экибастузском городском бюджете на 2018 - 2020 годы»
    kaz: Екібастұз қалалық мәслихатының 2017 жылғы 26 желтоқсандағы «2018 - 2020 жылдарға арналған Екібастұз қалалық бюджеті туралы» № 201/25 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125244/rus
