act_code: '218804'
requisite: Решение маслихата района Аққулы Павлодарской области от 17 декабря 2025 года № 168/40
title:
  rus: О бюджете района Аққулы на 2026-2028 годы
  kaz: 2026 - 2028 жылдарға арналған Аққулы аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-17
approved_by:
- '164009000002'
version_date:
  kaz: 2026-09-07
  rus: 2026-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/218804/kaz/07.09.2026
  rus: https://zan.gov.kz/client/#!/doc/218804/rus/07.09.2026
caused_by:
  code: '229784'
  requisite: Решение маслихата района Аққулы Павлодарской области от 7 сентября 2026 года № 214/52
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 17 декабря 2025 года № 168/40 «О бюджете района Аққулы на 2026-2028 годы»
    kaz: Аққулы аудандық мәслихатының 2025 жылғы 17 желтоқсандағы «2026-2028 жылдарға арналған Аққулы аудандық бюджеті туралы» № 168/40 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229784/rus
