act_code: '37085'
requisite: Решение акима Павлодарского района Павлодарской области от 14 января 2008 года № 1/Р. Зарегистрировано управлением юстиции Павлодарского района Павлодарской области 21 января 2008 года № 12-11-87
title:
  rus: О проведении приписки граждан Республики Казахстан 1991 года рождения к призывному участку отдела по делам обороны Павлодарского района в январе – марте 2008 года
  kaz: 1991 жылы туған Қазақстан Республикасының азаматтарын 2007 жылдың қаңтар – наурызында Павлодар ауданы қорғаныс істері Бөлімінің шақыру учаскесіне тіркеуін өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-01-14
approved_by:
- '164014000003'
version_date:
  kaz: 2008-01-14
  rus: 2008-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/37085/kaz/14.01.2008
  rus: https://zan.gov.kz/client/#!/doc/37085/rus/14.01.2008
