act_code: '41075'
requisite: Решение маслихата города Павлодара Павлодарской области от 19 июня 2008 года № 148/7. Зарегистрировано управлением юстиции города Павлодара Павлодарской области 1 августа 2008 года за № 12-1-124. Утратило силу решением маслихата города Павлодара Павлодарской области от 31 марта 2010 года № 26/23
title:
  rus: Об утверждении "Правил оказания жилищной помощи малообеспеченным гражданам по оплате содержания жилища, потребления коммунальных услуг, услуг связи и компенсации затрат на отдельные виды капитального ремонта общего имущества объекта кондоминиума из бюджета города"
  kaz: '"Қалалық бюджеттен тұрғын үйді ұстау, коммуналдық қызметті, байланыс қызметін тұтыну төлемақысы және кондоминиум объектісінің ортақ мүлкін күрделі жөндеудің жекелеген түрлеріне жұмсалатын шығындар өтемақысы бойынша аз қамтамасыз етілген азаматтарға тұрғын үй көмегін көрсету қағидасын" бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-06-19
approved_by:
- '164002000002'
version_date:
  kaz: 2008-06-19
  rus: 2008-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/41075/kaz/19.06.2008
  rus: https://zan.gov.kz/client/#!/doc/41075/rus/19.06.2008
