act_code: '162510'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 29 декабря 2021 года №  19/101
title:
  rus: О бюджете Шакатского сельского округа на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Шақат ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164014000002'
version_date:
  kaz: 2022-09-22
  rus: 2022-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/162510/kaz/22.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162510/rus/22.09.2022
caused_by:
  code: '171969'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 22 сентября 2022 года № 28/164
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 29 декабря 2021 года № 19/101 «О бюджете Шакатского сельского округа на 2022-2024 годы»
    kaz: Павлодар аудандық мәслихатының 2021 жылғы 29 желтоқсандағы «2022-2024 жылдарға арналған Шақат ауылдық округінің бюджеті туралы» № 19/101 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171969/rus
