act_code: '183782'
requisite: Решение Павлодарского областного маслихата от 27 июня 2023 года № 37/3
title:
  rus: Об утверждении Положения государственного учреждения «Ревизионная комиссия по Павлодарской области»
  kaz: «Павлодар облысы бойынша тексеру комиссиясы» мемлекеттік мекемесі туралы» Ережені бекіту жөнінде
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-06-27
approved_by:
- '164000000002'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/183782/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/183782/rus/26.11.2025
caused_by:
  code: '217752'
  requisite: Решение Павлодарского областного маслихата от 26 ноября 2025 года № 225/25
  title:
    rus: О внесении изменений в решение Павлодарского областного маслихата от 27 июня 2023 года № 37/3 «Об утверждении Положения государственного учреждения «Ревизионная комиссия по Павлодарской области»
    kaz: Павлодар облыстық мәслихатының 2023 жылғы 27 маусымдағы «Павлодар облысы бойынша тексеру комиссиясы» мемлекеттік мекемесі туралы» Ережені бекіту жөнінде» № 37/3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217752/rus
