act_code: '202883'
requisite: Решение акима Сатпаевского сельского округа Баянаульского района Павлодарской области от 20 ноября 2024 года № 1-03-07
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «CopperExploratoinGroup» на территории села Кокдомбак Cатпаевского сельского округа Баянаульского района
  kaz: «Copper Exploratoin Group» жауапкершілігі шектеулі серіктестігіне Баянауыл ауданы Сәтбаев ауылдық округі Көкдомбақ ауылы аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '164005012002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/202883/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202883/rus/20.11.2024
