act_code: '49636'
requisite: Решение маслихата Железинского района Павлодарской области от 28 декабря 2009 года № 175-4/20. Зарегистрировано Управлением юстиции Железинского района Павлодарской области 29 декабря 2009 года № 12-6-82
title:
  rus: Очередная (XX сессия, IV созыва) "О районном бюджете на 2010 - 2012 годы"
  kaz: (IV шақырылымның кезекті XX сессиясы) "2010 - 2012 жылдарға арналған аудан бюджеті туралы"
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '164006000002'
version_date:
  kaz: 2010-04-16
  rus: 2010-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/49636/kaz/16.04.2010
  rus: https://zan.gov.kz/client/#!/doc/49636/rus/16.04.2010
caused_by:
  code: '52124'
  requisite: Решение маслихата Железинского района Павлодарской области от 16 апреля 2010 года № 188-4/23. Зарегистрировано Управлением юстиции Железинского района Павлодарской области 23 апреля 2010 года № 12-6-87
  title:
    rus: О внесении изменений в решение районного Маслихата очередной XX сессия, IV созыва № 175-4/20 от 28 декабря 2009 года "О районном бюджете на 2010 - 2012 годы"
    kaz: Аудан мәслихатының 2009 жылғы 28 желтоқсандағы 4 шақырылымы 20 сессиясының "2010 - 2012 жылдарға арналған аудан бюджеті туралы" № 175-4/20 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/52124/rus
