act_code: '120420'
requisite: Решение маслихата Павлодарского района Павлодарской области от 27 марта 2018 года № 30/169. Зарегистрировано Департаментом юстиции Павлодарской области 6 апреля 2018 года № 5943. Утратило силу решением маслихата Павлодарского района Павлодарской области от 29 июня 2018 года № 35/183 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества Красноармейского сельского округа Павлодарского района
  kaz: Павлодар ауданы Красноармейка ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-03-27
approved_by:
- '164014000002'
version_date:
  kaz: 2018-03-27
  rus: 2018-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/120420/kaz/27.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120420/rus/27.03.2018
