act_code: '204881'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 26 декабря 2024 года № 27/225
title:
  rus: О бюджете Зангарского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Заңғар ауылдық округінің  бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '164014000002'
version_date:
  kaz: 2024-12-26
  rus: 2024-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/204881/kaz/26.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204881/rus/26.12.2024
