act_code: '79451'
requisite: Решение маслихата Железинского района Павлодарской области от 25 апреля 2014 года № 202-5/27. Зарегистрировано Департаментом юстиции Павлодарской области 30 апреля 2014 года № 3779. Утратило силу решением Железинского районного маслихата Павлодарской области от 8 января 2021 года № 520/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням
  kaz: Алушылардың жекелеген санаттары үшін атаулы күндер мен мереке күндеріне әлеуметтік көмектің мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-25
approved_by:
- '164006000002'
version_date:
  kaz: 2019-03-26
  rus: 2019-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/79451/kaz/26.03.2019
  rus: https://zan.gov.kz/client/#!/doc/79451/rus/26.03.2019
caused_by:
  code: '130568'
  requisite: Решение маслихата Железинского района Павлодарской области от 26 марта 2019 года № 327/6. Зарегистрировано Департаментом юстиции Павлодарской области 12 апреля 2019 года № 6298. Утратило силу решением Железинского районного маслихата Павлодарской области от 8 января 2021 года № 520/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Железинского районного маслихата от 25 апреля 2014 года № 202-5/27«Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням»
    kaz: Железинка аудандық мәслихатының 2014 жылғы 25 сәуірдегі «Алушылардың жекелеген санаттары үшін атаулы күндер мен мереке күндеріне әлеуметтік көмектің мөлшерлерін белгілеу туралы» № 202-5/27 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/130568/rus
