act_code: '79451'
requisite: Решение маслихата Железинского района Павлодарской области от 25 апреля 2014 года № 202-5/27. Зарегистрировано Департаментом юстиции Павлодарской области 30 апреля 2014 года № 3779. Утратило силу решением Железинского районного маслихата Павлодарской области от 8 января 2021 года № 520/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням
  kaz: Алушылардың жекелеген санаттары үшін атаулы күндер мен мереке күндеріне әлеуметтік көмектің мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-25
approved_by:
- '164006000002'
version_date:
  kaz: 2015-03-11
  rus: 2015-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/79451/kaz/11.03.2015
  rus: https://zan.gov.kz/client/#!/doc/79451/rus/11.03.2015
caused_by:
  code: '88368'
  requisite: Решение маслихата Железинского района Павлодарской области от 11 марта 2015 года № 273-5/34. Зарегистрировано Департаментом юстиции Павлодарской области 07 апреля 2015 года № 4409. Утратило силу решением Железинского районного маслихата Павлодарской области от 8 января 2021 года № 520/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 25 апреля 2014 года № 202-5/27 «Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням»
    kaz: Железинка аудандық мәслихатының 2014 жылғы 25 сәуірдегі «Алушылардың жекелеген санаттары үшін атаулы күндер мен мереке күндеріне әлеуметтік көмектің мөлшерлерін белгілеу туралы» № 202-5/27 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88368/rus
