act_code: '221796'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 30 января 2026 года № 165/55
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку и захоронение твёрдых бытовых отходов по Щербактинскому району
  kaz: Шарбақты ауданы бойынша коммуналдық қалдықтардың түзілу және жиналу нормаларын, халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2026-01-30
approved_by:
- '164012000002'
version_date:
  kaz: 2026-01-30
  rus: 2026-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/221796/kaz/30.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221796/rus/30.01.2026
