act_code: '150534'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 23 декабря 2020 года № 487/63. Зарегистрировано Департаментом юстиции Павлодарской области 25 декабря 2020 года № 7109
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в городе Экибастуз
  kaz: Екібастұз қаласында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '164013000002'
version_date:
  kaz: 2021-04-28
  rus: 2021-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/150534/kaz/28.04.2021
  rus: https://zan.gov.kz/client/#!/doc/150534/rus/28.04.2021
caused_by:
  code: '155926'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 28 апреля 2021 года № 29/4. Зарегистрировано Департаментом юстиции Павлодарской области 18 мая 2021 года № 7282
  title:
    rus: О внесении изменения в решение Экибастузского городского маслихата от 23 декабря 2020 года № 487/63 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в городе Экибастуз»
    kaz: Екібастұз қалалық мәслихатының 2020 жылғы 23 желтоқсандағы «Екібастұз қаласында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» № 487/63 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155926/rus
