act_code: '85529'
requisite: Решение акима Иртышского района Павлодарской области от 03 декабря 2014 года № 3. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2014 года № 4244. Утратило силу решением акима Иртышского района Павлодарской области от 7 июня 2019 года № 8 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Иртышского района
  kaz: Ертіс ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '164007000001'
version_date:
  kaz: 2015-03-26
  rus: 2015-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/85529/kaz/26.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85529/rus/26.03.2015
caused_by:
  code: '88086'
  requisite: Решение акима Иртышского района Павлодарской области от 26 марта 2015 года № 7. Зарегистрировано Департаментом юстиции Павлодарской области 27 марта 2015 года № 4390. Утратило силу решением акима Иртышского района Павлодарской области от 7 июня 2019 года № 8 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима района от 3 декабря 2014 года № 3 «Об образовании избирательных участков на территории Иртышского района»
    kaz: Аудан әкімінің 2014 жылғы 3 желтоқсандағы «Ертіс ауданы аумағында сайлау учаскелерін құру туралы» № 3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88086/rus
