act_code: '127808'
requisite: Решение маслихата Актогайского района Павлодарской области от 25 декабря 2018 года № 218/42. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2018 года № 6197
title:
  rus: Об Актогайском районном бюджете на 2019 - 2021 годы
  kaz: Ақтоғай ауданының 2019 - 2021 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '164003000002'
version_date:
  kaz: 2018-12-25
  rus: 2018-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/127808/kaz/25.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127808/rus/25.12.2018
