act_code: '174505'
requisite: Решение Успенского районного маслихата Павлодарской области от 25 ноября 2022 года № 131/23
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сельских округов, прибывшим для работы и проживания в сельские населенные пункты  Успенского района на 2023 год
  kaz: 2023 жылға арналған Успен ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-25
approved_by:
- '164011000002'
version_date:
  kaz: 2023-10-23
  rus: 2023-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/174505/kaz/23.10.2023
  rus: https://zan.gov.kz/client/#!/doc/174505/rus/23.10.2023
caused_by:
  code: '187484'
  requisite: Решение Успенского районного маслихата Павлодарской области от 23 октября 2023 года № 53/9
  title:
    rus: О внесении изменения в решение Успенского районного маслихата от 25 ноября 2022 года № 131/23 «О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сельских округов, прибывшим для работы и проживания в сельские населенные пункты Успенского района на 2023 год»
    kaz: Успен аудандық мәслихатының «Успен аудандық мәслихатының 2022 жылғы 25 қарашадағы № 131/23 «2023 жылға арналған Успен ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау шараларын ұсыну туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187484/rus
