act_code: '52580'
requisite: Павлодар облысы Лебяжі ауданы Лебяжі ауылдық округ әкімінің 2010 жылғы 26 сәуірдегі № 12 шешімі. Павлодар облысы Лебяжі ауданының Әділет басқармасында 2010 жылғы 18 мамырда № 12-9-111 тіркелген
title:
  rus: Лебяжі ауылдық округі Аққу ауылының көше атауларын өзгерту туралы
  kaz: Лебяжі ауылдық округі Аққу ауылының көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-26
approved_by:
- '164009000001'
version_date:
  kaz: 2010-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/52580/kaz/26.04.2010
