act_code: '5178'
requisite: Аким Павлодарской области от 27 ноября 1999 года № 257. Зарегистрировано Управлением юстиции Павлодарской области 1 февраля 2000 года № 211
title:
  rus: Об утверждении ставок платежей в областной Фонд охраны окружающей среды на 2000 год
  kaz: Қоршаған ортаны қорғау облыстық Қорына 2000 жылы төленетін төлем мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-11-27
approved_by:
- '164000000003'
version_date:
  kaz: 1999-11-27
  rus: 1999-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/5178/kaz/27.11.1999
  rus: https://zan.gov.kz/client/#!/doc/5178/rus/27.11.1999
