act_code: '204888'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 26 декабря 2024 года № 27/227
title:
  rus: О бюджете cельского округа Кемеңгер на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Кемеңгер ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '164014000002'
version_date:
  kaz: 2025-04-30
  rus: 2025-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/204888/kaz/30.04.2025
  rus: https://zan.gov.kz/client/#!/doc/204888/rus/30.04.2025
caused_by:
  code: '209664'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 30 апреля 2025 года № 30/259
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 26 декабря 2024 года № 27/227 «О бюджете cельского округа Кемеңгер на 2025-2027 годы»
    kaz: Павлодар аудандық мәслихатының 2024 жылғы 26 желтоқсандағы «2025-2027 жылдарға арналған Кемеңгер ауылдық округінің бюджеті туралы» № 27/227 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209664/rus
