act_code: '148460'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 3 ноября 2020 года № 530/71. Зарегистрировано Департаментом юстиции Павлодарской области 13 ноября 2020 года № 7024
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сел, поселков, сельских округов, прибывшим для работы и проживания в сельские населенные пункты города Павлодара на 2020 год
  kaz: 2020 жылға арналған Павлодар қаласының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдар, кенттер, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-03
approved_by:
- '164002000002'
version_date:
  kaz: 2020-11-03
  rus: 2020-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/148460/kaz/03.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148460/rus/03.11.2020
