act_code: '204970'
requisite: Решение Железинского районного маслихата Павлодарской области от 27 декабря 2024 года № 158/8
title:
  rus: О бюджете сельских округов Железинского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164006000002'
version_date:
  kaz: 2025-04-17
  rus: 2025-04-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/204970/kaz/17.04.2025
  rus: https://zan.gov.kz/client/#!/doc/204970/rus/17.04.2025
caused_by:
  code: '209303'
  requisite: Решение Железинского районного маслихата Павлодарской области от 17 апреля 2025 года № 169/8
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 27 декабря 2024 года № 158/8 «О бюджете сельских округов Железинского района на 2025-2027 годы»
    kaz: Железин аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 158/8 «2025-2027 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209303/rus
