act_code: '204970'
requisite: Решение Железинского районного маслихата Павлодарской области от 27 декабря 2024 года № 158/8
title:
  rus: О бюджете сельских округов Железинского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164006000002'
version_date:
  kaz: 2025-07-10
  rus: 2025-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/204970/kaz/10.07.2025
  rus: https://zan.gov.kz/client/#!/doc/204970/rus/10.07.2025
caused_by:
  code: '212200'
  requisite: Решение Железинского районного маслихата Павлодарской области от 10 июля 2025 года № 187/8
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 27 декабря 2024 года № 158/8 «О бюджете сельских округов Железинского района на 2025-2027 годы»
    kaz: Железин аудандық мәслихатының 2024 жылғы 27 желтоқсандағы «2025-2027 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы» № 158/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212200/rus
