act_code: '37196'
requisite: Решение маслихата города Павлодара Павлодарской области от 21 декабря 2007 года № 60/3. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 23 января 2008 года за № 102. Утратило силу - решением маслихата города Павлодара Павлодарской области от 4 июня 2009 года № 74/15
title:
  rus: Об утверждении стоимости разовых талонов и ставок фиксированного суммарного налога по отдельным видам предпринимательской деятельности
  kaz: Кәсіпкерлік қызметтің жеке түрлері бойынша тіркелген жиынтық салықтың ставкаларын және біржолғы талондардың құнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-21
approved_by:
- '164002000002'
version_date:
  kaz: 2007-12-21
  rus: 2007-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/37196/kaz/21.12.2007
  rus: https://zan.gov.kz/client/#!/doc/37196/rus/21.12.2007
