act_code: '123691'
requisite: Решение маслихата Майского района Павлодарской области от 12 июля 2018 года № 6/33. Зарегистрировано Департаментом юстиции Павлодарской области 24 июля 2018 года № 6028
title:
  rus: Об утверждении регламента собрания местного сообщества сел и сельских округов Майского района
  kaz: Май ауданының ауылдар және ауылдық округтерінің  жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-07-12
approved_by:
- '164010000002'
version_date:
  kaz: 2022-02-10
  rus: 2022-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/123691/kaz/10.02.2022
  rus: https://zan.gov.kz/client/#!/doc/123691/rus/10.02.2022
caused_by:
  code: '164396'
  requisite: Решение маслихата Майского района Павлодарской области от 10 февраля 2022 года № 10/13
  title:
    rus: О внесении изменений в решение маслихата Майского района от 12 июля 2018 года № 6/33 «Об утверждении регламента собрания местного сообщества сел и сельских округов Майского района»
    kaz: Май аудандық мәслихатының 2018 жылғы 12 шілдедегі «Май ауданының ауылдар және ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» № 6/33 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164396/rus
