act_code: '95201'
requisite: Решение маслихата города Павлодара Павлодарской области от 22 октября 2015 года № 428/58. Зарегистрировано Департаментом юстиции Павлодарской области 11 ноября 2015 года № 4783. Утратило силу решением Павлодарского городского маслихата Павлодарской области от 16 сентября 2020 года № 520/70 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента Павлодарского городского маслихата
  kaz: Павлодар қалалық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2015-10-22
approved_by:
- '164002000002'
version_date:
  kaz: 2015-10-22
  rus: 2015-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/95201/kaz/22.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95201/rus/22.10.2015
