act_code: '199318'
requisite: Решение Иртышского районного маслихата Павлодарской области от 31 июля 2024 года № 83-23-8. Отменено решением Иртышского районного маслихата Павлодарской области от 24 августа 2026 года № 182-61-8 (вводится в действие со дня его принятия)
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Иртышского районного маслихата»
  kaz: «Ертіс аудандық мәслихат аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2024-07-31
approved_by:
- '164007000002'
version_date:
  kaz: 2024-07-31
  rus: 2024-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/199318/kaz/31.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199318/rus/31.07.2024
