act_code: '117598'
requisite: Решение маслихата Иртышского района Павлодарской области от 29 декабря 2017 года № 108-21-6. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2018 года № 5777
title:
  rus: О бюджете села Иртышск на 2018 - 2020 годы
  kaz: Ертіс ауылының 2018 - 2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-29
approved_by:
- '164007000002'
version_date:
  kaz: 2018-10-22
  rus: 2018-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/117598/kaz/22.10.2018
  rus: https://zan.gov.kz/client/#!/doc/117598/rus/22.10.2018
caused_by:
  code: '125931'
  requisite: Решение маслихата Иртышского района Павлодарской области от 22 октября 2018 года № 145-31-6. Зарегистрировано Департаментом юстиции Павлодарской области 12 ноября 2018 года № 6109
  title:
    rus: О внесении изменений в решение Иртышского районного маслихата от 29 декабря 2017 года № 108-21-6 «О бюджете села Иртышск на 2018 - 2020 годы»
    kaz: Ертіс аудандық мәслихатының 2017 жылғы 29 желтоқсандағы «Ертіс ауылының 2018 - 2020  жылдарға арналған бюджеті туралы» № 108-21-6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125931/rus
