act_code: '174743'
requisite: Решение Иртышского районного маслихата Павлодарской области от 1 декабря 2022 года № 104-25-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 декабря 2022 года № 30936
title:
  rus: О повышении ставок земельного налога Иртышского района
  kaz: Ертіс ауданының жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-01
approved_by:
- '164007000002'
version_date:
  kaz: 2022-12-01
  rus: 2022-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/174743/kaz/01.12.2022
  rus: https://zan.gov.kz/client/#!/doc/174743/rus/01.12.2022
