act_code: '83742'
requisite: Решение маслихата Майского района Павлодарской области от 29 сентября 2014 года № 14/40. Зарегистрировано Департаментом юстиции Павлодарской области 17 октября 2014 года № 4118. Утратило силу решением маслихата Майского района Павлодарской области от 23 июня 2020 года № 1/60 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций, проживающим и работающим в сельских населенных пунктах
  kaz: Ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-09-29
approved_by:
- '164010000002'
version_date:
  kaz: 2014-09-29
  rus: 2014-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/83742/kaz/29.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83742/rus/29.09.2014
