act_code: '11055'
requisite: Решение Акима Павлодарской области от 6 февраля 2001 года № 31. Зарегистрировано Управлением юстиции 30 марта 2001 года за № 604
title:
  rus: Об утверждении тарифов на медицинские услуги, оказанные в рамках гарантированного объема бесплатной медицинской помощи
  kaz: Тегін медициналық көмектің кепілдендірілген көлемі шеңберінде көрсетілген медициналық қызметтерге тарифтер бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-02-06
approved_by:
- '164000000003'
version_date:
  kaz: 2001-02-06
  rus: 2001-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/11055/kaz/06.02.2001
  rus: https://zan.gov.kz/client/#!/doc/11055/rus/06.02.2001
