act_code: '130638'
requisite: Решение маслихата района Аққулы Павлодарской области от 8 апреля 2019 года № 196/39. Зарегистрировано Департаментом юстиции Павлодарской области 15 апреля 2019 года № 6304. Утратило силу решением маслихата района Аққулы Павлодарской области от 12 сентября 2023 года № 35/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества сельских округов района Аққулы
  kaz: Аққулы ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-04-08
approved_by:
- '164009000002'
version_date:
  kaz: 2021-09-06
  rus: 2021-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/130638/kaz/06.09.2021
  rus: https://zan.gov.kz/client/#!/doc/130638/rus/06.09.2021
caused_by:
  code: '158349'
  requisite: Решение маслихата района Аққулы Павлодарской области от 6 сентября 2021 года № 38/7. Утратило силу решением маслихата района Аққулы Павлодарской области от 12 сентября 2023 года № 35/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 8 апреля 2019 года № 196/39 «Об утверждении регламента собрания местного сообщества сельских округов района Аққулы»
    kaz: Аққулы аудандық мәслихатының 2019 жылғы 8 сәуірдегі «Аққулы ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» № 196/39 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158349/rus
