act_code: '207816'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 5 марта 2025 года № 7/27
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по району Тереңкөл на 2025-2029 годы
  kaz: Тереңкөл ауданы бойынша 2025-2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-05
approved_by:
- '164008000002'
version_date:
  kaz: 2025-03-05
  rus: 2025-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/207816/kaz/05.03.2025
  rus: https://zan.gov.kz/client/#!/doc/207816/rus/05.03.2025
