act_code: '127825'
requisite: Решение маслихата Майского района Павлодарской области от 25 декабря 2018 года № 1/40. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2018 года № 6200
title:
  rus: О Майском районном бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Май аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '164010000002'
version_date:
  kaz: 2019-12-05
  rus: 2019-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/127825/kaz/05.12.2019
  rus: https://zan.gov.kz/client/#!/doc/127825/rus/05.12.2019
caused_by:
  code: '136913'
  requisite: Решение маслихата Майского района Павлодарской области от 5 декабря 2019 года № 3/54. Зарегистрировано Департаментом юстиции Павлодарской области 11 декабря 2019 года № 6658
  title:
    rus: О внесении изменений в решение Майского районного маслихата от 25 декабря 2018 года № 1/40 «О Майском районном бюджете на 2019 - 2021 годы»
    kaz: Май аудандық мәслихатының 2018 жылғы 25 желтоқсандағы «2019 - 2021 жылдарға арналған Май аудандық бюджеті туралы» № 1/40 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136913/rus
