act_code: '91984'
requisite: Решение маслихата Майского района Павлодарской области от 23 июня 2015 года № 4/49. Зарегистрировано Департаментом юстиции Павлодарской области 20 июля 2015 года № 4613. Утратило силу решением маслихата Майского района Павлодарской области от 15 сентября 2015 года N 2/53 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата Майского района
  kaz: Май аудандық мәслихаты аппараты "Б" корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-06-23
approved_by:
- '164010000002'
version_date:
  kaz: 2015-06-23
  rus: 2015-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/91984/kaz/23.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91984/rus/23.06.2015
