act_code: '48999'
requisite: Решение маслихата Качирского района Павлодарской области от 25 ноября 2009 года № 6/18. Зарегистрировано Управлением юстиции Качирского района Павлодарской области 2 декабря 2009 года № 12-8-78. Утратило силу решением маслихата Качирского района Павлодарской области от 25 декабря 2009 года № 4/19
title:
  rus: Об утверждении порядка предоставления малообеспеченным гражданам жилищных субсидий на содержание жилья и оплату коммунальных услуг
  kaz: Аз қамтасыз етілген азаматтарға тұрғын үйді ұстау және коммуналдық қызметтерге ақы төлеу бойынша тұрғын үй жәрдемақысын беру тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-25
approved_by:
- '164008000002'
version_date:
  kaz: 2009-11-25
  rus: 2009-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/48999/kaz/25.11.2009
  rus: https://zan.gov.kz/client/#!/doc/48999/rus/25.11.2009
