act_code: '162752'
requisite: Решение Актогайского районного маслихата Павлодарской области от 29 декабря 2021 года № 79/16
title:
  rus: О бюджете Жолболдинского сельского округа на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Жолболды ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164003000002'
version_date:
  kaz: 2022-12-06
  rus: 2022-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/162752/kaz/06.12.2022
  rus: https://zan.gov.kz/client/#!/doc/162752/rus/06.12.2022
caused_by:
  code: '174970'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 6 декабря 2022 года № 136/29
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 29 декабря 2021 года № 79/16 «О бюджете Жолболдинского сельского округа на 2022-2024 годы»
    kaz: Ақтоғай аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 79/16 «2022-2024 жылдарға арналған Жолболды ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174970/rus
