act_code: '11062'
requisite: Павлодар облыстық мәслихаттың 2001 жылғы 13 наурыздағы II сайланған, X (кезектен тыс) сессия шешімі. Павлодар облысының Әділет басқармасында 2001 жылғы 12 сәуірде № 627 тіркелді
title:
  rus: Облыстық «2001 жылы шегіртке зиянкестіктерімен күрес шаралары» бағдарламасы туралы
  kaz: Облыстық «2001 жылы шегіртке зиянкестіктерімен күрес шаралары» бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-13
approved_by:
- '164000000002'
version_date:
  kaz: 2001-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/11062/kaz/13.03.2001
