act_code: '202800'
requisite: Решение и.о. акима Актогайского района Павлодарской области от 18 ноября 2024 года № 8. Утратило силу решением акима Актогайского района Павлодарской области от 11 февраля 2025 года № 1 р (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Актогайского района Павлодарской области
  kaz: Павлодар облысы Ақтоғай ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-18
approved_by:
- '164003000003'
version_date:
  kaz: 2024-11-18
  rus: 2024-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/202800/kaz/18.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202800/rus/18.11.2024
