act_code: '85905'
requisite: Решение маслихата Железинского района Павлодарской области от 25 декабря 2014 года № 267-5/32. Зарегистрировано Департаментом юстиции Павлодарской области 14 января 2015 года № 4265
title:
  rus: О бюджете Железинского района на  2015 - 2017 годы
  kaz: Железинка ауданының  2015 - 2017 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '164006000002'
version_date:
  kaz: 2015-09-07
  rus: 2015-09-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/85905/kaz/07.09.2015
  rus: https://zan.gov.kz/client/#!/doc/85905/rus/07.09.2015
caused_by:
  code: '93913'
  requisite: Решение маслихата Железинского района Павлодарской области от 7 сентября 2015 года № 318-5/39. Зарегистрировано Департаментом юстиции Павлодарской области 22 сентября 2015 года № 4718
  title:
    rus: О внесении изменения в решение Железинского районного маслихата от 25 декабря 2014 года № 267-5/32 «О  бюджете Железинского района на 2015 - 2017 годы»
    kaz: Железинка аудандық мәслихатының 2014 жылғы 25 желтоқсандағы «Железинка ауданының 2015 - 2017 жылдарға арналған бюджеті туралы» № 267-5/32 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93913/rus
