act_code: '184273'
requisite: Решение акима Муткеновского сельского округа Актогайского района Павлодарской области от 11 июля 2023 года № 4
title:
  rus: О переименовании улицы Орталық на улицу Ғосман Смағұлұлы в селе Абжан Муткеновского сельского округа Актогайского района Павлодарской области
  kaz: Павлодар облысы Ақтоғай ауданы Мүткенов ауылдық округінің Әбжан ауылындағы Орталық көшесін Ғосман Смағұлұлы көшесіне қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-11
approved_by:
- '164003011002'
version_date:
  kaz: 2023-07-11
  rus: 2023-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/184273/kaz/11.07.2023
  rus: https://zan.gov.kz/client/#!/doc/184273/rus/11.07.2023
