act_code: '66096'
requisite: Павлодар облысы Баянауыл ауданы Қаратомар ауылдық округ әкімінің 2012 жылғы 25 мамырдағы № 06 шешімі. Павлодар облысының Баянауыл аудандық Әділет басқармасында 2012 жылғы 08 маусымда № 12-5-108 тіркелді
title:
  rus: Баянауыл ауданы Қаратомар ауылдық округіне қарасты Қаратомар ауылына көше атауларын беру туралы
  kaz: Баянауыл ауданы Қаратомар ауылдық округіне қарасты Қаратомар ауылына көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-25
approved_by:
- '164005007001'
version_date:
  kaz: 2012-05-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/66096/kaz/25.05.2012
