act_code: '228723'
requisite: Решение акима Агашорынского сельского округа Иртышского района Павлодарской области от 10 августа 2026 года № 1-03-09
title:
  rus: Об установлении публичного сервитута на территории села Узынсу Агашорынского сельского округа Иртышского района
  kaz: Ертіс ауданы Ағашорын ауылдық округі Ұзынсу ауылы аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-10
approved_by:
- '164007003002'
version_date:
  kaz: 2026-08-10
  rus: 2026-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/228723/kaz/10.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228723/rus/10.08.2026
