act_code: '189778'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 6 декабря 2023 года № 5/10. Зарегистрировано в Департаменте юстиции Павлодарской области 11 декабря 2023 года № 7439-14
title:
  rus: Об утверждении ставок туристского взноса для иностранцев в районе Тереңкөл
  kaz: Тереңкөл ауданында шетелдіктер үшін арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-06
approved_by:
- '164008000002'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/189778/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189778/rus/06.12.2023
