act_code: '65388'
requisite: Решение маслихата Успенского района Павлодарской области от 13 апреля 2012 года № 18/4. Зарегистрировано Департаментом юстиции Павлодарской области 08 мая 2012 года № 12-12-129. Утратило силу решением маслихата Успенского района Павлодарской области от 19 ноября 2013 года № 118/27
title:
  rus: О ставках фиксированного налога
  kaz: Тіркелген салықтың мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-13
approved_by:
- '164011000002'
version_date:
  kaz: 2012-04-13
  rus: 2012-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/65388/kaz/13.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65388/rus/13.04.2012
