act_code: '62679'
requisite: Решение маслихата города Экибастуза Павлодарской области от 20 декабря 2011 года № 405/38. Зарегистрировано Департаментом юстиции Павлодарской области 10 января 2012 года № 12-3-311
title:
  rus: О бюджете города Экибастуза на 2012 - 2014 годы
  kaz: 2012 - 2014 жылдарға арналған Екібастұз қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164013000002'
version_date:
  kaz: 2012-12-06
  rus: 2012-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/62679/kaz/06.12.2012
  rus: https://zan.gov.kz/client/#!/doc/62679/rus/06.12.2012
caused_by:
  code: '69123'
  requisite: Решение маслихата города Экибастуза Павлодарской области от 06 декабря 2012 года № 90/11. Зарегистрировано Департаментом юстиции Павлодарской области 11 декабря 2012 года № 3273
  title:
    rus: О внесении изменений и дополнения в решение Экибастузского городского маслихата (очередная XXXVIII сессия, IV созыв) от 20 декабря 2011 года № 405/38 "О бюджете города Экибастуза на 2012 - 2014 годы"
    kaz: Екібастұз қалалық мәслихатының (IV шақырылған кезекті XXXVIII сессия) 2011 жылғы 20 желтоқсандағы "2012 - 2014 жылдарға арналған Екібастұз қаласының бюджеті туралы" № 405/38 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/69123/rus
