act_code: '175939'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 26 декабря 2022 года № 1/34
title:
  rus: О бюджете сельских округов района Тереңкөл на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Тереңкөл ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '164008000002'
version_date:
  kaz: 2022-12-26
  rus: 2022-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/175939/kaz/26.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175939/rus/26.12.2022
