act_code: '40487'
requisite: Решение акима села Павлодарское Павлодарской области от 14 мая 2008 года N 12. Зарегистрировано управлением юстиции села Павлодарское Павлодарской области 20 июня 2008 года за N 116. Утратило силу решением акима села Павлодарское Павлодарской области от 8 июня 2009 года N 13
title:
  rus: Об утверждении стандартов государственных услуг, оказываемых государственным учреждением "Аппарат акима села Павлодарское"
  kaz: '"Павлодар ауылы әкімінің аппараты" мемлекеттік мекемесі бойынша мемлекеттік қызметтерді көрсету стандарттарын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
- СТНД
approved_on: 2008-05-14
approved_by:
- '164002003001'
version_date:
  kaz: 2008-09-18
  rus: 2008-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/40487/kaz/18.09.2008
  rus: https://zan.gov.kz/client/#!/doc/40487/rus/18.09.2008
caused_by:
  code: '42049'
  requisite: Решение акима села Павлодарское города Павлодара Павлодарской области от 18 сентября 2008 года № 28. Зарегистрировано Управлением юстиции города Павлодара 20 октября 2008 года за № 12-1-127. Утратило силу решением акима села Павлодарское города Павлодар Павлодарской области от 8 июня 2009 года № 13
  title:
    rus: О внесении изменений и дополнений в решение акима села Павлодарское от 14 мая 2008 года № 12 "Об утверждении стандартов государственных услуг, оказываемых государственным учреждением "Аппарат акима села Павлодарское"
    kaz: 2008 жылдың 14 мамырдан № 12 Павлодар ауылы әкімінің "Павлодар ауылы әкімінің аппараты" мемлекеттік мекемесі бойынша мемлекеттік қызметтерді көрсету стандарттарын бекіту туралы" шешіміне толықтыру мен өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42049/rus
