act_code: '1598'
requisite: Решение Акима Павлодарской области от 14 июля 1998 года № 233. Загеристрировано Управлением юстиции Павлодарской области 26 октября 1998 года за № 81. Утратило силу решением акима Павлодарской области от 29 октября 2004 года  № 25
title:
  rus: О нормах потребления коммунальных услуг по теплу, горячей и холодной воде
  kaz: Жылу, ыстық және суық су беру коммуналдық қызметтерін тұтыну мөлшерлерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-07-13
approved_by:
- '164000000003'
version_date:
  kaz: 1998-07-13
  rus: 1998-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/1598/kaz/13.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1598/rus/13.07.1998
