act_code: '117449'
requisite: Решение маслихата Баянаульского района Павлодарской области от 29 декабря 2017 года № 138/22. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2018 года № 5780
title:
  rus: О бюджете Баянаульского сельского округа и поселка Майкаин на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған Баянауыл ауылдық округі және Майқайың кенті бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-29
approved_by:
- '164005000002'
version_date:
  kaz: 2018-12-13
  rus: 2018-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117449/kaz/13.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117449/rus/13.12.2018
caused_by:
  code: '127025'
  requisite: Решение маслихата Баянаульского района Павлодарской области от 13 декабря 2018 года № 217/38. Зарегистрировано Департаментом юстиции Павлодарской области 14 декабря 2018 года № 6160
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 29 декабря 2017 года № 138/22 «О бюджете Баянаульского сельского округа и поселка Майкаин               на 2018 - 2020 годы»
    kaz: Баянауыл аудандық мәслихатының 2017 жылғы 29 желтоқсандағы «2018 - 2020 жылдарға арналған Баянауыл ауылдық округі және Майқайың кенті бюджеті туралы» № 138/22 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127025/rus
