act_code: '204694'
requisite: Решение Иртышского районного маслихата Павлодарской области от 25 декабря 2024 года № 108-29-8
title:
  rus: Об Иртышском районном бюджете на 2025 – 2027 годы
  kaz: 2025 – 2027 жылдарға арналған Ертіс аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '164007000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204694/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204694/rus/25.12.2024
