act_code: '183550'
requisite: Решение Павлодарского областного маслихата от 27 июня 2023 года № 39/3. Зарегистрировано Департаментом юстиции Павлодарской области 30 июня 2023 года № 7368-14. Утратило силу решением Павлодарского областного маслихата от 25 февраля 2025 года № 183/19 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения в Павлодарской области
  kaz: Павлодар облысында ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық жүйелерінен халыққа берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-27
approved_by:
- '164000000002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/183550/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183550/rus/27.06.2023
