act_code: '202607'
requisite: Решение акима Жанажольского сельского округа Баянаульского района Павлодарской области от 28 октября 2024 года № 1-03/06
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Copper Exploratoin Group» на территории Жанажольского сельского округа Баянаульского района
  kaz: «Copper Exploratoin Group» жауапкершілігі шектеулі серіктестігіне Баянауыл ауданы Жаңажол ауылдық округі аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-28
approved_by:
- '164005005002'
version_date:
  kaz: 2024-10-28
  rus: 2024-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/202607/kaz/28.10.2024
  rus: https://zan.gov.kz/client/#!/doc/202607/rus/28.10.2024
