act_code: '218762'
requisite: Решение Актогайского районного маслихата Павлодарской области от 17 декабря 2025 года № 234/42
title:
  rus: Об Актогайском районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Ақтоғай аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-17
approved_by:
- '164003000002'
version_date:
  kaz: 2026-09-02
  rus: 2026-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/218762/kaz/02.09.2026
  rus: https://zan.gov.kz/client/#!/doc/218762/rus/02.09.2026
caused_by:
  code: '229630'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 2 сентября 2026 года № 290/57
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 17 декабря 2025 года № 234/42 «Об Актогайском районном бюджете на 2026-2028 годы»
    kaz: Ақтоғай аудандық мәслихаттының 2025 жылғы 17 желтоқсандағы № 234/42 «2026-2028 жылдарға арналған Ақтоғай аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229630/rus
