act_code: '83111'
requisite: Решение маслихата Баянаульского района Павлодарской области от 30 июля 2014 года № 197/36. Зарегистрировано Департаментом юстиции Павлодарской области 11 сентября 2014 года № 4013. Утратило силу решением Баянаульского районного маслихата Павлодарской области от 31 июля 2024 года № 194/21 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количества представителей жителей улиц поселка Майкаин и села Ушкулун для участия в сходе местного сообщества на территории поселка Майкаин и села Ушкулун Баянаульского района
  kaz: Баянауыл ауданы Майқайың кентінің және Үшқұлын ауылының аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін Майқайың кенті көшелерінің және Үшқұлын ауылының тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-07-30
approved_by:
- '164005000002'
version_date:
  kaz: 2014-07-30
  rus: 2014-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/83111/kaz/30.07.2014
  rus: https://zan.gov.kz/client/#!/doc/83111/rus/30.07.2014
