act_code: '61093'
requisite: Павлодар облысы Лебяжі ауданы Шарбақты ауылдық округ әкімінің 2011 жылғы 30 қыркүйектегі № 7 шешімі. Павлодар облысы Лебяжі аудандық Әділет басқармасында 2011 жылғы 03 қарашада № 12-9-144 тіркелді
title:
  rus: Лебяжі ауданының Шарбақты ауылдық округіне қарасты Шарбақты, Төс-ағаш, Жабағлы ауылдарының көше атауларын бекіту туралы
  kaz: Лебяжі ауданының Шарбақты ауылдық округіне қарасты Шарбақты, Төс-ағаш, Жабағлы ауылдарының көше атауларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-30
approved_by:
- '164012000001'
version_date:
  kaz: 2011-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/61093/kaz/30.09.2011
