act_code: '147391'
requisite: Решение Железинского районного маслихата Павлодарской области от 30 сентября 2020 года № 486/6. Зарегистрировано Департаментом юстиции Павлодарской области 14 октября 2020 года № 6984. Утратило силу решением Железинского районного маслихата Павлодарской области от 16 ноября 2023 года № 63/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Железинского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Железин ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидалары бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-09-30
approved_by:
- '164006000002'
version_date:
  kaz: 2022-07-29
  rus: 2022-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/147391/kaz/29.07.2022
  rus: https://zan.gov.kz/client/#!/doc/147391/rus/29.07.2022
caused_by:
  code: '170342'
  requisite: Решение Железинского районного маслихата Павлодарской области от 29 июля 2022 года № 162/7. Зарегистрировано в Министерстве юстиции Республики Казахстан 3 августа 2022 года № 29009. Утратило силу решением Железинского районного маслихата Павлодарской области от 16 ноября 2023 года № 63/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 30 сентября 2020 года № 486/6 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных  категорий нуждающихся граждан Железинского района
    kaz: Железин аудандық мәслихатының 2020 жылғы 30 қыркүйектегі «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Железин ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» № 486/6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/170342/rus
