act_code: '162214'
requisite: Решение маслихата района Аққулы Павлодарской области от 24 декабря 2021 года № 52/11. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26046
title:
  rus: О бюджете района Аққулы на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Аққулы аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164009000002'
version_date:
  kaz: 2022-04-01
  rus: 2022-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/162214/kaz/01.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162214/rus/01.04.2022
caused_by:
  code: '165917'
  requisite: Решение маслихата района Аққулы Павлодарской области от 1 апреля 2022 года № 67/14
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 24 декабря 2021 года № 52/11 «О бюджете района Аққулы на 2022-2024 годы»
    kaz: Аққулы аудандық мәслихатының 2021 жылғы 24 желтоқсандағы «2022 - 2024 жылдарға арналған Аққулы аудандық бюджеті туралы» № 52/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165917/rus
