act_code: '28492'
requisite: Решение маслихата Железинского района Павлодарской области от 12 июня 2006 года № 177-3/25. Зарегистрировано Управлением юстиции Железинского района Павлодарской области 20 июня 2006 года № 12-6-28
title:
  rus: Об утверждении стоимости разовых талонов на эпизодические виды деятельности
  kaz: Об утверждении стоимости разовых талонов на эпизодические виды деятельности
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-06-12
approved_by:
- '164006000002'
version_date:
  rus: 2006-06-12
source:
  rus: https://zan.gov.kz/client/#!/doc/28492/rus/12.06.2006
