act_code: '62605'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2011 жылғы 20 желтоқсандағы № 262/43 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 05 қаңтарда № 12-5-96 тіркелді
title:
  rus: Баянауыл ауданының 2012 - 2014 жылдарға арналған бюджеті туралы
  kaz: Баянауыл ауданының 2012 - 2014 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164005000002'
version_date:
  kaz: 2012-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/62605/kaz/12.09.2012
caused_by:
  code: '67835'
  requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2012 жылғы 12 қыркүйектегі № 42/8 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 26 қыркүйекте № 3223 тіркелді
  title:
    rus: Баянауыл аудандық мәслихатының (IV сайланған кезекті XLIII сессия) 2011 жылғы 20 желтоқсандағы № 262/43 "Баянауыл ауданының 2012 - 2014 жылдарға арналған бюджеті туралы" шешіміне өзгеріс енгізу туралы
    kaz: Баянауыл аудандық мәслихатының (IV сайланған кезекті XLIII сессия) 2011 жылғы 20 желтоқсандағы № 262/43 "Баянауыл ауданының 2012 - 2014 жылдарға арналған бюджеті туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/67835/rus
