act_code: '194624'
requisite: Решение Актогайского районного маслихата Павлодарской области от 19 марта 2024 года № 118/16. Зарегистрировано в Департаменте юстиции Павлодарской области 20 марта 2024 года № 7513-14
title:
  rus: Об определении размера и правил оказания жилищной помощи по Актогайскому району
  kaz: Ақтоғай ауданы бойынша тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '164003000002'
version_date:
  kaz: 2026-03-19
  rus: 2026-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/194624/kaz/19.03.2026
  rus: https://zan.gov.kz/client/#!/doc/194624/rus/19.03.2026
caused_by:
  code: '223920'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 19 марта 2026 года № 259/48. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 марта 2026 года № 38224
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 19 марта 2024 года № 118/16 «Об определении размера и порядка оказания жилищной помощи по Актогайскому району»
    kaz: Ақтоғай аудандық мәслихатының 2024 жылғы 19 наурыздағы «Ақтоғай ауданы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» № 118/16 шешіміне өзгеріс еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223920/rus
