act_code: '189311'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 24 ноября 2023 года № 79/9. Зарегистрировано в Департаменте юстиции Павлодарской области 30 ноября 2023 года № 7428-14
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Павлодаре
  kaz: Павлодар қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқу жоспары бойынша үйде оқытуға жұмсалған шығындарды өтеу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-24
approved_by:
- '164002000002'
version_date:
  kaz: 2023-11-24
  rus: 2023-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/189311/kaz/24.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189311/rus/24.11.2023
