act_code: '51157'
requisite: Решение акима города Экибастуза Павлодарской области от 12 февраля 2010 года № 5. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 9 марта 2010 года № 12-3-257
title:
  rus: О приписке граждан 1993 года рождения к призывному участку государственного учреждения "Объединенный отдел по делам обороны города Экибастуза Павлодарской области" в январе - марте 2010 года
  kaz: 1993 жылы туған азаматтарды 2010 жылдың қаңтар - наурызында "Павлодар облысы Екібастұз қаласының қорғаныс істері жөніндегі біріккен бөлімі" мемлекеттік мекемесінің шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-12
approved_by:
- '164013000001'
version_date:
  kaz: 2011-08-22
  rus: 2011-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/51157/kaz/22.08.2011
  rus: https://zan.gov.kz/client/#!/doc/51157/rus/22.08.2011
