act_code: '167625'
requisite: Решение Аксуского городского маслихата Павлодарской области от 29 апреля 2022 года № 153/22. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2022 года № 28012
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по городу Аксу
  kaz: Ақсу қаласы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-29
approved_by:
- '164004000002'
version_date:
  kaz: 2022-04-29
  rus: 2022-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/167625/kaz/29.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167625/rus/29.04.2022
