act_code: '162205'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 24 декабря 2021 года № 4/14. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26022
title:
  rus: О бюджете района Тереңкөл на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Тереңкөл аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164008000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162205/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162205/rus/24.12.2021
