act_code: '137791'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 27 декабря 2019 года № 1/53. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2019 года № 6695
title:
  rus: О бюджете сельских округов района Тереңкөл на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Тереңкөл ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '164008000002'
version_date:
  kaz: 2020-10-20
  rus: 2020-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/137791/kaz/20.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137791/rus/20.10.2020
caused_by:
  code: '147915'
  requisite: Решение маслихата района Тереңкөл Павлодарской области от 20 октября 2020 года № 1/62. Зарегистрировано Департаментом юстиции Павлодарской области 29 октября 2020 года № 7001
  title:
    rus: О внесении изменений в решение маслихата района Тереңкөл от 27 декабря 2019 года № 1/53 «О бюджете сельских округов района Тереңкөл на 2020 - 2022 годы»
    kaz: Тереңкөл аудандық мәслихатының 2019 жылғы 27 желтоқсандағы «2020 - 2022 жылдарға арналған Тереңкөл ауданының ауылдық округтерінің бюджеті туралы» № 1/53 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147915/rus
