act_code: '81991'
requisite: Решение маслихата Качирского района Павлодарской области от 24 июля 2014 года № 3/32. Зарегистрировано Департаментом юстиции Павлодарской области 14 августа 2014 года № 3923. Утратило силу решением маслихата Качирского района Павлодарской области от 16 сентября 2015 года № 4/47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента маслихата Качирского района
  kaz: Качир ауданы мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-07-24
approved_by:
- '164008000002'
version_date:
  kaz: 2014-07-24
  rus: 2014-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/81991/kaz/24.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81991/rus/24.07.2014
