act_code: '16718'
requisite: Лебяжі аудандық мәслихатының 2003 жылғы 2 шілдедегі № 3/22 шешімі. Павлодар облысының Әділет басқармасында 2003 жылғы 18 тамызда № 1990 тіркелді. Күші жойылды - Павлодар облысы Лебяжі аудандық мәслихатының 2009 жылғы 28 шілдедегі № 8/2 шешімімен
title:
  rus: Лебяжi ауданының елдi мекендер аумағында ақпараттық жарнама өнiмдерiн орналастыру қағидасы туралы
  kaz: Лебяжi ауданының елдi мекендер аумағында ақпараттық жарнама өнiмдерiн орналастыру қағидасы туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2003-07-01
approved_by:
- '164009000002'
version_date:
  kaz: 2003-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/16718/kaz/01.07.2003
