act_code: '139741'
requisite: Решение акима Кенжекольского сельского округа города Павлодара Павлодарской области от 19 февраля 2020 года № 17-1-03/8. Зарегистрировано Департаментом юстиции Павлодарской области 24 февраля 2020 года № 6732
title:
  rus: О переименовании улиц сел Кенжеколь и Долгое Кенжекольского сельского округа города Павлодара
  kaz: Павлодар қаласы Кенжекөл ауылдық округінің Кенжекөл және Долгое ауылдарының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-19
approved_by:
- '164002002002'
version_date:
  kaz: 2020-02-19
  rus: 2020-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/139741/kaz/19.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139741/rus/19.02.2020
