act_code: '21238'
requisite: Решение Акимата Павлодарской области от 10 августа 2004 года № 20. Зарегистрировано Департаментом юстиции Павлодарской области 10 сентября 2004 года за № 2708. Утратило силу решением акима Павлодарской области от 14 сентября 2009 года № 3
title:
  rus: О вопросах лицензирования производства, передачи и распределения тепловой энергии, эксплуатации котлов и трубопроводов, работающих под давлением, эксплуатации сосудов, работающих под давлением в составе промышленных холодильных установок и бытовых газовых баллонов, на территории области
  kaz: Облыс аумағындағы жылу қуатын өндіруді, беруді және бөлуді, қазандарды және қысым арқылы жұмыс істейтін құбырларды пайдалануды, өнеркәсіптік мұздатқыш қондырғылары және тұрмыстық газ баллондарының құрамында қысым арқылы жұмыс істейтін ыдыстарды пайдалануды лицензиялау мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-08-09
approved_by:
- '164000000001'
version_date:
  kaz: 2004-08-09
  rus: 2004-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/21238/kaz/09.08.2004
  rus: https://zan.gov.kz/client/#!/doc/21238/rus/09.08.2004
