act_code: '131301'
requisite: Решение маслихата Павлодарского района Павлодарской области от 4 мая 2019 года № 53/241. Зарегистрировано Департаментом юстиции Павлодарской области 6 мая 2019 года № 6348
title:
  rus: Об утверждении проекта (схемы) зонирования земель и о повышении ставок земельного налога Павлодарского района
  kaz: Павлодар ауданының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту және жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2019-05-04
approved_by:
- '164014000002'
version_date:
  kaz: 2021-04-21
  rus: 2021-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/131301/kaz/21.04.2021
  rus: https://zan.gov.kz/client/#!/doc/131301/rus/21.04.2021
caused_by:
  code: '155574'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 21 апреля 2021 года № 3/28. Зарегистрировано Департаментом юстиции Павлодарской области 5 мая 2021 года № 7272
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 4 мая 2019 года № 53/241 «Об утверждении проекта (схемы) зонирования земель и о повышении ставок земельного налога Павлодарского района»
    kaz: Павлодар аудандық мәслихатының 2019 жылғы 4 мамырдағы «Павлодар ауданының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту және жер салығының мөлшерлемелерін арттыру туралы» № 53/241 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155574/rus
