act_code: '191559'
requisite: Решение акима Железинского сельского округа Железинского района Павлодарской области от 3 января 2024 года № 1
title:
  rus: О переименовании улиц в селе Железинка Железинского сельского округа Железинского района
  kaz: Железин ауданы Железин ауылдық округінің Железинка ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-03
approved_by:
- '164006006002'
version_date:
  kaz: 2024-01-03
  rus: 2024-01-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/191559/kaz/03.01.2024
  rus: https://zan.gov.kz/client/#!/doc/191559/rus/03.01.2024
