act_code: '176145'
requisite: Решение Иртышского районного маслихата Павлодарской области от 27 декабря 2022 года № 110-27-7. Утратило силу решением Иртышского районного маслихата Павлодарской области от 29 ноября 2024 года № 100-27-8 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Иртышскому району на 2023-2024 годы
  kaz: Ертіс ауданы бойынша 2023-2024 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2022-12-27
approved_by:
- '164007000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176145/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176145/rus/27.12.2022
