act_code: '200837'
requisite: Решение акима сельского округа Кемеңгер Павлодарского района Павлодарской области от 5 сентября 2024 года № 1-03-1
title:
  rus: Об установлении публичного сервитута на земельный участок
  kaz: Жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-05
approved_by:
- '164014010002'
version_date:
  kaz: 2024-09-05
  rus: 2024-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/200837/kaz/05.09.2024
  rus: https://zan.gov.kz/client/#!/doc/200837/rus/05.09.2024
