act_code: '56088'
requisite: Решение маслихата Качирского района Павлодарской области от 23 декабря 2010 года № 1/27. Зарегистрировано Управлением юстиции Качирского района Павлодарской области 27 декабря 2010 года № 12-8-98. Утратило силу решением маслихата Качирского района Павлодарской области от 17 июня 2013 года № 8/14
title:
  rus: О бюджете района на 2011 - 2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '164008000002'
version_date:
  kaz: 2011-02-14
  rus: 2011-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56088/kaz/14.02.2011
  rus: https://zan.gov.kz/client/#!/doc/56088/rus/14.02.2011
caused_by:
  code: '57421'
  requisite: Решение маслихата Качирского района Павлодарской области от 14 февраля 2011 года № 3/28. Зарегистрировано Департаментом юстиции Павлодарской области 24 февраля 2011 года № 12-8-101
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата (XXVII сессия, IV созыв) от 23 декабря 2010 года № 1/27 "О бюджете района на 2011 - 2013 годы"
    kaz: Аудандық мәслихаттың (IV сайланған XXVII сессиясы) 2010 жылғы 23 желтоқсандағы "2011 - 2013 жылдарға арналған аудан бюджеті туралы" № 1/27 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57421/rus
