act_code: '219271'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 19 декабря 2025 года № 40/334
title:
  rus: О бюджете Заринского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Заря ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '164014000002'
version_date:
  kaz: 2026-05-12
  rus: 2026-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/219271/kaz/12.05.2026
  rus: https://zan.gov.kz/client/#!/doc/219271/rus/12.05.2026
caused_by:
  code: '225213'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 12 мая 2026 года № 46/372
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 19 декабря 2025 года № 40/334 «О бюджете Заринского сельского округа на 2026-2028 годы»
    kaz: Павлодар аудандық мәслихатының 2025 жылғы 19 желтоқсандағы «2026-2028 жылдарға арналған Заря ауылдық округінің бюджеті туралы» № 40/334 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225213/rus
