act_code: '211493'
requisite: Решение акима Баянаульского района Павлодарской области от 23 июня 2025 года № 3/06. Утратило силу решением акима Баянаульского района Павлодарской области от 26 января 2026 года № 1/01 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба на территории Баянаульского района Павлодарской области
  kaz: Павлодар облысы Баянауыл ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-23
approved_by:
- '164005000003'
version_date:
  kaz: 2025-06-23
  rus: 2025-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/211493/kaz/23.06.2025
  rus: https://zan.gov.kz/client/#!/doc/211493/rus/23.06.2025
