act_code: '5402'
requisite: Павлодар облыстық Мәслихаттың ІІ сайланған, ІІ сессияның 1999 жылғы 13 желтоқсандағы шешімі. Павлодар облысының Әділет басқармасында 2000 жылғы 16 ақпанда № 219 тіркелді
title:
  rus: Облысты басқару нобайы туралы
  kaz: Облысты басқару нобайы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-12-13
approved_by:
- '164000000002'
version_date:
  kaz: 1999-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/5402/kaz/13.12.1999
