act_code: '192975'
requisite: Решение маслихата района Аққулы Павлодарской области от 31 января 2024 года № 70/17
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села для участия в сходе местного сообщества сельского округа Аққулы района Аққулы
  kaz: Аққулы ауданы Аққулы ауылдық округінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын  және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-01-31
approved_by:
- '164009000002'
version_date:
  kaz: 2024-01-31
  rus: 2024-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/192975/kaz/31.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192975/rus/31.01.2024
