act_code: '170561'
requisite: Решение Павлодарского областного маслихата от 8 августа 2022 года № 182/14
title:
  rus: Об утверждении Правил содержания и выгула домашних животных в Павлодарской области
  kaz: Павлодар облысында үй жануарларын ұстаудың және серуендетудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-08-08
approved_by:
- '164000000002'
version_date:
  kaz: 2022-08-08
  rus: 2022-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/170561/kaz/08.08.2022
  rus: https://zan.gov.kz/client/#!/doc/170561/rus/08.08.2022
