act_code: '81477'
requisite: Решение маслихата города Экибастуза Павлодарской области от 19 июня 2014 года № 230/30. Зарегистрировано Департаментом юстиции Павлодарской области 23 июля 2014 года № 3882. Утратило силу решением Экибастузского городского маслихата Павлодарской области от 25 августа 2022 года № 137/21 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количества представителей жителей села для участия в сходе местного сообщества на территории села Шикылдак города Экибастуза
  kaz: Екібастұз қаласы Шиқылдақ ауылының аумағында бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-06-19
approved_by:
- '164013000002'
version_date:
  kaz: 2014-06-19
  rus: 2014-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/81477/kaz/19.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81477/rus/19.06.2014
