act_code: '198617'
requisite: Решение акима Песчанского сельского округа района Тереңкөл Павлодарской области от 9 июля 2024 года № 1
title:
  rus: Об установлении публичного сервитута на территории села Песчаное Песчанского сельского округа района Тереңкөл
  kaz: Тереңкөл ауданы Песчан ауылдық округі Песчан ауылы аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-09
approved_by:
- '164008004002'
version_date:
  kaz: 2024-07-09
  rus: 2024-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/198617/kaz/09.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198617/rus/09.07.2024
