act_code: '175765'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 21 декабря 2022 года № 1/33
title:
  rus: О бюджете района Тереңкөл на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Тереңкөл аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-21
approved_by:
- '164008000002'
version_date:
  kaz: 2022-12-21
  rus: 2022-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/175765/kaz/21.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175765/rus/21.12.2022
