act_code: '62633'
requisite: Решение маслихата Павлодарской области от 06 декабря 2011 года № 402/40. Зарегистрировано Департаментом юстиции Павлодарской области 06 января 2012 года № 3196
title:
  rus: О ставках платы за пользование водными ресурсами поверхностных источников на 2012 год по Павлодарской области
  kaz: Павлодар облысы бойынша 2012 жылға арналған жерүсті су көздерінің ресурстарын пайдаланғаны үшін төленетін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-06
approved_by:
- '164000000002'
version_date:
  kaz: 2011-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/62633/kaz/06.12.2011
