act_code: '95141'
requisite: Решение маслихата Железинского района Павлодарской области от 12 октября 2015 года № 326-5/41. Зарегистрировано Департаментом юстиции Павлодарской области 09 ноября 2015 года № 4781. Утратило силу решением маслихата Железинского района Павлодарской области от 16 февраля 2016 года № 355-5/48 (вводится в действие со дня подписания)
title:
  rus: О повышении ставки земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения Железинского района Павлодарской области
  kaz: Павлодар облысы Железин ауданының Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын  ауыл шаруашылығы мақсатындағы жерлеріне жер салығының мөлшерлемесін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-12
approved_by:
- '164006000002'
version_date:
  kaz: 2015-10-12
  rus: 2015-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/95141/kaz/12.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95141/rus/12.10.2015
