act_code: '205014'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 27 декабря 2024 года № 214/26
title:
  rus: О бюджете сельских округов, сел и поселков города Экибастуза на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164013000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205014/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205014/rus/27.12.2024
