act_code: '139722'
requisite: Решение акима Актогайского сельского округа Актогайского района Павлодарской области от 17 февраля 2020 года № 3. Зарегистрировано Департаментом юстиции Павлодарской области 21 февраля 2020 года № 6730
title:
  rus: Об установлении публичного сервитута на территории Актогайского сельского округа Актогайского района
  kaz: Ақтоғай ауданы Ақтоғай ауылдық округінің аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-17
approved_by:
- '164003001001'
version_date:
  kaz: 2020-02-17
  rus: 2020-02-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/139722/kaz/17.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139722/rus/17.02.2020
