act_code: '185829'
requisite: Решение акима Шакинского сельского округа района Аққулы Павлодарской области от 5 сентября 2023 года № 1-17/03
title:
  rus: О переименовании некоторых улиц села Шака Шакинского сельского округа  района Аққулы
  kaz: Аққулы ауданы Шақа ауылдық округінің Шақа ауылындағы кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-05
approved_by:
- '164009010002'
version_date:
  kaz: 2023-09-05
  rus: 2023-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/185829/kaz/05.09.2023
  rus: https://zan.gov.kz/client/#!/doc/185829/rus/05.09.2023
