act_code: '18530'
requisite: Баянауыл аудандық Мәслихатының (II-сайланған ХХIХ сессиясының) 2003 жылғы 14 сәуірдегі № 84 шешімі. Павлодар облысының Әділет басқармасында 2003 жылғы 13 мамырда № 1787 тіркелді. Күші жойылды - Павлодар облысы Баянауыл аудандық мәслихатының 2010 жылғы 26 шілдедегі № 179/26 шешімімен
title:
  rus: Баянауыл аудандық мәслихатының регламентiн бекiту туралы
  kaz: Баянауыл аудандық мәслихатының регламентiн бекiту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2003-04-13
approved_by:
- '164005000002'
version_date:
  kaz: 2003-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/18530/kaz/13.04.2003
