act_code: '14685'
requisite: Решение маслихата Павлодарской области от 5 ноября 2002 года (XXIII сессия, II созыва) № 76/23. Зарегистрировано Управлением юстиции Павлодарской области 6 декабря 2004 года за № 1555
title:
  rus: Об областной программе импорт замещения и качества на 2002 – 2003 годы
  kaz: Облыстық 2002 – 2003 жылдарға арналған импорт алмастыру және сапа бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-11-05
approved_by:
- '164000000002'
version_date:
  kaz: 2002-11-05
  rus: 2002-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/14685/kaz/05.11.2002
  rus: https://zan.gov.kz/client/#!/doc/14685/rus/05.11.2002
