act_code: '219101'
requisite: Решение Актогайского районного маслихата Павлодарской области от 19 декабря 2025 года № 242/43
title:
  rus: «О бюджете Муткеновского сельского округа 2026-2028 годы»
  kaz: «2026-2028 жылдарға арналған Мүткенов ауылдық округінің бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '164003000002'
version_date:
  kaz: 2025-12-19
  rus: 2025-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/219101/kaz/19.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219101/rus/19.12.2025
