act_code: '72827'
requisite: Решение маслихата города Павлодар Павлодарской области от 30 апреля 2013 года № 147/19. Зарегистрировано Департаментом юстиции Павлодарской области 31 мая 2013 года № 3545. Утратило силу решением маслихата города Павлодара Павлодарской области от 15 июня 2020 года № 494/66 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении тарифов на вывоз твёрдых бытовых отходов с территории города Павлодара
  kaz: Павлодар қаласының аумағынан тұрмыстық қатты қалдықтарды шығару тарифтерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-30
approved_by:
- '164002000002'
version_date:
  kaz: 2016-07-14
  rus: 2016-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/72827/kaz/14.07.2016
  rus: https://zan.gov.kz/client/#!/doc/72827/rus/14.07.2016
caused_by:
  code: '105686'
  requisite: Решение маслихата города Павлодара Павлодарской области от 14 июля 2016 года № 58/7. Зарегистрировано Департаментом юстиции Павлодарской области 23 августа 2016 года № 5217. Утратило силу решением маслихата города Павлодара Павлодарской области от 15 июня 2020 года № 494/66 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата от 30 апреля 2013 года № 147/19 «Об утверждении тарифов на вывоз коммунальных отходов с территории города Павлодара»
    kaz: Павлодар қалалық мәслихатының 2013 жылғы 30 сәуірдегі «Павлодар қаласының аумағынан коммуналдық қалдықтарды шығару тарифтерін бекіту туралы» № 147/19 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105686/rus
