act_code: '16484'
requisite: Решение маслихата Павлодарской области от 25 апреля 2003 года № 118/26. Зарегистрировано Управлением юстиции Павлодарской области 21 мая 2003 года за № 1817
title:
  rus: Об утверждении плана мероприятий на 2003 год по реализации программы комплексного развития Майского района на 2001 - 2003 годы
  kaz: 2001 - 2003 жылдарға арналған Май ауданын кешенді дамыту бағдарламасын іске асыру жөніндегі 2003 жылға арналған іс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-04-24
approved_by:
- '164000000002'
version_date:
  kaz: 2003-04-24
  rus: 2003-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/16484/kaz/24.04.2003
  rus: https://zan.gov.kz/client/#!/doc/16484/rus/24.04.2003
