act_code: '127829'
requisite: Решение маслихата Успенского района Павлодарской области от 25 декабря 2018 года № 193/38. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2018 года № 6201
title:
  rus: Об Успенском районном бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Успен аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '164011000002'
version_date:
  kaz: 2019-08-27
  rus: 2019-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/127829/kaz/27.08.2019
  rus: https://zan.gov.kz/client/#!/doc/127829/rus/27.08.2019
caused_by:
  code: '134397'
  requisite: Решение маслихата Успенского района Павлодарской области от 27 августа 2019 года № 230/50. Зарегистрировано Департаментом юстиции Павлодарской области 3 сентября 2019 года № 6530
  title:
    rus: О внесении изменений в решение Успенского районного маслихата от 25 декабря 2018 года № 193/38 «Об Успенском районном бюджете на 2019 - 2021 годы»
    kaz: Успен аудандық мәслихатының 2018 жылғы 25 желтоқсандағы «2019 - 2021 жылдарға арналған Успен аудандық бюджеті туралы» № 193/38 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134397/rus
