act_code: '80623'
requisite: Решение маслихата города Аксу Павлодарской области от 30 апреля 2014 года № 226/31. Зарегистрировано Департаментом юстиции Павлодарской области 11 июня 2014 года № 3851. Утратило силу решением маслихата города Аксу Павлодарской области от 26 ноября 2019 года № 373/52 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении схем зонирования земель города Аксу и сельских округов города Аксу для целей налогооблажения и поправочных коэффициентов к базовым ставкам земельного налога
  kaz: Ақсу қаласы және Ақсу қаласының селолық округтері жерлеріне салық салу мақсатында жерлерді аймаққа бөлу сызбаларын және жер салығының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-30
approved_by:
- '164004000002'
version_date:
  kaz: 2014-04-30
  rus: 2014-04-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/80623/kaz/30.04.2014
  rus: https://zan.gov.kz/client/#!/doc/80623/rus/30.04.2014
