act_code: '77502'
requisite: Решение маслихата Щербактинского района Павлодарской области от 15 января 2014 года № 106/37. Зарегистрировано Департаментом юстиции Павлодарской области 17 февраля 2014 года № 3696. Утратило силу решением Щербактинского районного маслихата Павлодарской области от 29 сентября 2020 года № 266/81 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Щербактинского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Шарбақты ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-01-15
approved_by:
- '164012000002'
version_date:
  kaz: 2019-05-17
  rus: 2019-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/77502/kaz/17.05.2019
  rus: https://zan.gov.kz/client/#!/doc/77502/rus/17.05.2019
caused_by:
  code: '131766'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 17 мая 2019 года № 191/56. Зарегистрировано Департаментом юстиции Павлодарской области 22 мая 2019 года № 6379. Утратило силу решением Щербактинского районного маслихата Павлодарской области от 29 сентября 2020 года № 266/81 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение Щербактинского районного маслихата от 15 января 2014 года № 106/37 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Щербактинского района»
    kaz: Шарбақты аудандық мәслихатының 2014 жылғы 15 қаңтардағы «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Шарбақты ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» №106/37 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131766/rus
