act_code: '77502'
requisite: Решение маслихата Щербактинского района Павлодарской области от 15 января 2014 года № 106/37. Зарегистрировано Департаментом юстиции Павлодарской области 17 февраля 2014 года № 3696. Утратило силу решением Щербактинского районного маслихата Павлодарской области от 29 сентября 2020 года № 266/81 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Щербактинского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Шарбақты ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-01-15
approved_by:
- '164012000002'
version_date:
  kaz: 2016-04-04
  rus: 2016-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/77502/kaz/04.04.2016
  rus: https://zan.gov.kz/client/#!/doc/77502/rus/04.04.2016
caused_by:
  code: '101426'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 4 апреля 2016 года № 6/2. Зарегистрировано Департаментом юстиции Павлодарской области 18 апреля 2016 года № 5081. Утратило силу решением Щербактинского районного маслихата Павлодарской области от 29 сентября 2020 года № 266/81 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 15 января 2014 года № 106/37 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Щербактинского района»
    kaz: Шарбақты аудандық мәслихатының 2014 жылғы 15 қаңтардағы № 106/37 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Шарбақты ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101426/rus
