act_code: '223076'
requisite: Решение акима города Аксу Павлодарской области от 12 марта 2026 года № 4
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-12
approved_by:
- '164004000003'
version_date:
  kaz: 2026-03-12
  rus: 2026-03-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/223076/kaz/12.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223076/rus/12.03.2026
