act_code: '63817'
requisite: Решение маслихата города Аксу Павлодарской области от 27 января 2012 года № 15/2. Зарегистрировано Департаментом юстиции Павлодарской области 29 февраля 2012 года № 12-2-195. Утратило силу решением маслихата города Аксу Павлодарской области от 23 июля 2012 года № 12-2-195
title:
  rus: О перечне отдельных категорий граждан, имеющих право на дополнительную социальную помощь в 2012 году
  kaz: 2012 жылы қосымша әлеуметтік көмекке құқығы бар азаматтардың жекелеген санаттарының тізбесі туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2012-01-27
approved_by:
- '164004000002'
version_date:
  kaz: 2012-01-27
  rus: 2012-01-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/63817/kaz/27.01.2012
  rus: https://zan.gov.kz/client/#!/doc/63817/rus/27.01.2012
