act_code: '35446'
requisite: Решение маслихата города Экибастуза Павлодарской области от 25 сентября 2007 года № 12/2. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 22 октября 2007 года № 12-3-111
title:
  rus: О правилах застройки города Экибастуза
  kaz: Екібастұз қаласы құрылысының қағидалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-25
approved_by:
- '164013000002'
version_date:
  kaz: 2007-10-25
  rus: 2007-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/35446/kaz/25.10.2007
  rus: https://zan.gov.kz/client/#!/doc/35446/rus/25.10.2007
