act_code: '36619'
requisite: Решение маслихата города Аксу Павлодарской области от 21 декабря 2007 года № 26/5. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 10 января 2008 года за № 12-2-79. Утратило силу решением маслихата города Аксу Павлодарской области от 20 февраля 2014 года № 199/28
title:
  rus: О правилах застройки территории города и населенных пунктов административного подчинения города Аксу
  kaz: Қала аумағы мен Ақсу қаласының әкімшілік бағынысындағы елді мекендер құрылысының Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-12-21
approved_by:
- '164004000002'
version_date:
  kaz: 2010-06-09
  rus: 2010-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/36619/kaz/09.06.2010
  rus: https://zan.gov.kz/client/#!/doc/36619/rus/09.06.2010
caused_by:
  code: '53402'
  requisite: Решение маслихата города Аксу Павлодарской области от 9 июня 2010 года № 216/26. Зарегистрировано Департаментом юстиции Павлодарской области 8 июля 2010 года № 12-2-147. Утратило силу решением маслихата города Аксу Павлодарской области от 20 февраля 2014 года № 199/28
  title:
    rus: О внесении изменений и дополнения в решение городского маслихата от 21 декабря 2007 года № 26/5 "О Правилах застройки территории города и населенных пунктов административного подчинения города Аксу"
    kaz: Қалалық мәслихаттың 2007 жылғы 21 желтоқсандағы "Қала аумағы мен Ақсу қаласының әкімшілік бағынысындағы елді мекендер құрылысының Ережесі туралы" № 26/5 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53402/rus
