act_code: '119201'
requisite: Решение исполняющего обязанности акима Байконысского сельского округа Качирского района Павлодарской области от 21 февраля 2018 года № 1-12/02. Зарегистрировано Департаментом юстиции Павлодарской области 27 февраля 2018 года № 5872
title:
  rus: О переименовании улиц села Байконыс Байконысского сельского округа Качирского района
  kaz: Качир ауданы Байқоныс ауылдық округі Байқоныс ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-21
approved_by:
- '164008008002'
version_date:
  kaz: 2018-02-21
  rus: 2018-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/119201/kaz/21.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119201/rus/21.02.2018
