act_code: '190173'
requisite: Решение акима села Иртышск Иртышского района Павлодарской области от 19 декабря 2023 года № 1-03-11
title:
  rus: О переименовании некоторых улиц села Иртышск Иртышского района
  kaz: Ертіс ауданы Ертіс ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-19
approved_by:
- '164007018001'
version_date:
  kaz: 2023-12-19
  rus: 2023-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/190173/kaz/19.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190173/rus/19.12.2023
