act_code: '7175'
requisite: Решение акима Павлодарской области от 4 сентября 2000 г. № 199 Зарегистрировано Управлением юстиции 28 сентября 2000 г. за № 440. Утратило силу - решением акима Павлодарской области от 18 июня 2003 года № 18
title:
  rus: Об областной экспертной комиссии по социально-политической  рекламе
  kaz: Әлеуметтiк-саяси жарнама жөнiндегi облыстық сараптау комиссиясы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-09-03
approved_by:
- '164000000001'
version_date:
  kaz: 2000-09-03
  rus: 2000-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/7175/kaz/03.09.2000
  rus: https://zan.gov.kz/client/#!/doc/7175/rus/03.09.2000
