act_code: '46716'
requisite: Решение маслихата города Павлодара Павлодарской области от 4 июня 2009 года № 74/15. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 29 июня 2009 года за № 12-1-140. Утратило силу решением маслихата города Павлодара Павлодарской области от 17 апреля 2012 года № 21/4
title:
  rus: Об утверждении стоимости разовых талонов и ставок фиксированного налога
  kaz: Біржолғы талондардың құнын және тіркелген салық ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-04
approved_by:
- '164002000002'
version_date:
  rus: 2009-06-04
source:
  rus: https://zan.gov.kz/client/#!/doc/46716/rus/04.06.2009
