act_code: '129625'
requisite: Решение маслихата Павлодарского района Павлодарской области от 4 марта 2019 года № 50/227. Зарегистрировано Департаментом юстиции Павлодарской области 14 марта 2019 года № 6270
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Павлодарского района на 2019 год
  kaz: 2019 жылға арналған Павлодар ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-04
approved_by:
- '164014000002'
version_date:
  kaz: 2019-08-22
  rus: 2019-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/129625/kaz/22.08.2019
  rus: https://zan.gov.kz/client/#!/doc/129625/rus/22.08.2019
caused_by:
  code: '134399'
  requisite: Решение маслихата Павлодарского района Павлодарской области от 22 августа 2019 года № 58/255. Зарегистрировано Департаментом юстиции Павлодарской области 3 сентября 2019 года № 6532
  title:
    rus: О внесении изменения в решение Павлодарского районного маслихата от 4 марта 2019 года № 50/227 «О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Павлодарского района на 2019 год»
    kaz: Павлодар аудандық мәслихатының 2019 жылғы 4 наурыздағы «2019 жылға арналған Павлодар ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға әлеуметтік колдау шараларын ұсыну туралы» № 50/227 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134399/rus
