act_code: '56512'
requisite: Решение маслихата Успенского района Павлодарской области от 24 декабря 2010 года № 168/28. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 05 января 2011 года № 12-12-100
title:
  rus: О бюджете района на 2011 - 2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '164011000002'
version_date:
  kaz: 2011-02-11
  rus: 2011-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/56512/kaz/11.02.2011
  rus: https://zan.gov.kz/client/#!/doc/56512/rus/11.02.2011
caused_by:
  code: '57299'
  requisite: Решение маслихата Успенского района Павлодарской области от 11 февраля 2011 года № 177/31. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 17 февраля 2011 года № 12-12-101
  title:
    rus: О внесении изменений в решение Успенского районного маслихата (XXVIII сессия IV созыв) от 24 декабря 2010 года № 168/28 "О бюджете района на 2011 - 2013 годы"
    kaz: Успен аудандық мәслихатының 2010 жылғы 24 желтоқсандағы (IV сайланған XXVIII сессиясы) "2011 - 2013 жылдарға арналған аудан бюджеті туралы" № 168/28 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57299/rus
