act_code: '136140'
requisite: Решение акима Песчанского сельского округа района Тереңкөл Павлодарской области от 5 ноября 2019 года № 13. Зарегистрировано Департаментом юстиции Павлодарской области 20 ноября 2019 года № 6613
title:
  rus: Об установлении публичного сервитута на территории Песчанского сельского округа района Тереңкөл
  kaz: Тереңкөл ауданы Песчан ауылдық округінің аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-05
approved_by:
- '164008004002'
version_date:
  kaz: 2019-11-05
  rus: 2019-11-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/136140/kaz/05.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136140/rus/05.11.2019
