act_code: '193121'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 6 февраля 2024 года № 118/15. Зарегистрировано в Департаменте юстиции Павлодарской области 8 февраля 2024 года № 7474-14
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в городе Экибастуз
  kaz: Екібастұз қаласында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-06
approved_by:
- '164013000002'
version_date:
  kaz: 2024-06-04
  rus: 2024-06-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/193121/kaz/04.06.2024
  rus: https://zan.gov.kz/client/#!/doc/193121/rus/04.06.2024
caused_by:
  code: '197665'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 4 июня 2024 года № 163/20. Зарегистрировано в Департаменте юстиции Павлодарской области 14 июня 2024 года № 7563-14
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 6 февраля 2024 года № 118/15 «Об определении размера и порядка оказания жилищной помощи в городе Экибастуз»
    kaz: Екібастұз қалалық мәслихатының 2024 жылғы 6 ақпандағы № 118/15 «Екібастұз қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197665/rus
