act_code: '49251'
requisite: Решение акима Шолаксорского сельского округа Актогайского района Павлодарской области от 23 ноября 2009 года № 7. Зарегистрировано Управлением юстиции Актогайского района Павлодарской области 10 декабря 2009 года № 12-4-72
title:
  rus: О присвоении наименования улицы в селе Кырыкуй
  kaz: Қырықүй ауылындағы көшеге ат қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-23
approved_by:
- '164003003001'
version_date:
  kaz: 2009-11-23
  rus: 2009-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49251/kaz/23.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49251/rus/23.11.2009
