act_code: '38095'
requisite: Павлодар облысы Баянауыл ауданы әкімінің  2008 жылғы 15 ақпандағы № 3 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2008 жылғы 26 ақпанда № 12-5-51 тіркелген
title:
  rus: 1991 жылы тұған жасөспірімдерді шақыру  учаскелерінде тіркеуден  өткізу туралы
  kaz: 1991 жылы тұған жасөспірімдерді шақыру  учаскелерінде тіркеуден  өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-02-15
approved_by:
- '164005000003'
version_date:
  kaz: 2008-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/38095/kaz/15.02.2008
