act_code: '119443'
requisite: Решение маслихата Актогайского района Павлодарской области от 27 февраля 2018 года № 167/30. Зарегистрировано Департаментом юстиции Павлодарской области 13 марта 2018 года № 5906. Утратило силу решением маслихата Актогайского района Павлодарской области от 3 апреля 2019 года № 237/47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества Актогайского сельского округа Актогайского района
  kaz: Ақтоғай ауданы Ақтоғай ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-02-27
approved_by:
- '164003000002'
version_date:
  kaz: 2018-02-27
  rus: 2018-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/119443/kaz/27.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119443/rus/27.02.2018
