act_code: '65938'
requisite: Решение акима Акшиманского сельского округа Майского района Павлодарской области от 16 мая 2012 года № 1. Зарегистрировано Управлением юстиции Майского района Павлодарской области 06 июня 2012 года № 12-10-125
title:
  rus: О присвоении наименований улицам села Акшиман Майского района
  kaz: Май ауданы Ақшиман селосының көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-16
approved_by:
- '164010007001'
version_date:
  kaz: 2012-05-16
  rus: 2012-05-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/65938/kaz/16.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65938/rus/16.05.2012
