act_code: '58100'
requisite: Решение маслихата города Аксу Павлодарской области от 25 марта 2011 года № 284/33. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 12 апреля 2011 года № 12-2-172
title:
  rus: О предоставлении права льготного проезда некоторым категориям обучающихся и воспитанников учреждений образования города Аксу на городском общественном транспорте (кроме такси) на 2011 год
  kaz: Ақсу қаласының білім беру мекемелерінің оқушылары мен тәрбиеленушілерінің кейбір санаттарына 2011 жылы қалалық қоғамдық көлікте (таксиден басқа) жеңілдетілген жол жүру құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-25
approved_by:
- '164004000002'
version_date:
  kaz: 2011-03-25
  rus: 2011-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/58100/kaz/25.03.2011
  rus: https://zan.gov.kz/client/#!/doc/58100/rus/25.03.2011
