act_code: '121549'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 23 апреля 2018 года № 127/25. Зарегистрировано Департаментом юстиции Павлодарской области 11 мая 2018 года № 5970. Утратило силу решением маслихата района Аққулы Павлодарской области от 8 апреля 2019 года № 196/39 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества Лебяжинского сельского округа Лебяжинского района
  kaz: Лебяжі ауданы Лебяжі ауылдық округінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-04-23
approved_by:
- '164009000002'
version_date:
  kaz: 2018-04-23
  rus: 2018-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/121549/kaz/23.04.2018
  rus: https://zan.gov.kz/client/#!/doc/121549/rus/23.04.2018
