act_code: '224289'
requisite: Решение Майского районного маслихата Павлодарской области от 13 апреля 2026 года № 1/39
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Майского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Май ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-04-13
approved_by:
- '164010000002'
version_date:
  kaz: 2026-09-21
  rus: 2026-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/224289/kaz/21.09.2026
  rus: https://zan.gov.kz/client/#!/doc/224289/rus/21.09.2026
caused_by:
  code: '230217'
  requisite: Решение Майского районного маслихата Павлодарской области от 21 сентября 2026 года № 1/42
  title:
    rus: О внесении изменений в решение Майского районного маслихата от 13 апреля 2026 года № 1/39 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Майского района»
    kaz: Май аудандық мәслихатының 2026 жылғы 13 сәуірдегі № 1/39 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Май ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/230217/rus
