act_code: '176078'
requisite: Решение маслихата района Аққулы Павлодарской области от 27 декабря 2022 года № 125/25
title:
  rus: О бюджетах сельских округов района Аққулы на 2023 – 2025 годы
  kaz: Аққулы ауданының ауылдық округтерінің 2023 – 2025 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '164009000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176078/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176078/rus/27.12.2022
