act_code: '175836'
requisite: Решение Аксуского городского маслихата Павлодарской области от 22 декабря 2022 года № 212/31
title:
  rus: О бюджете города Аксу на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '164004000002'
version_date:
  kaz: 2023-03-31
  rus: 2023-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/175836/kaz/31.03.2023
  rus: https://zan.gov.kz/client/#!/doc/175836/rus/31.03.2023
caused_by:
  code: '179349'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 31 марта 2023 года № 9/2
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 22 декабря 2022 года № 212/31 «О бюджете города Аксу на 2023-2025 годы»
    kaz: Ақсу қалалық мәслихатының 2022 жылғы 22 желтоқсандағы «2023-2025 жылдарға арналған Ақсу қаласының бюджеті туралы» № 212/31 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179349/rus
