act_code: '3184'
requisite: Решение акима Павлодарской области от 9 марта 1999 года № 34. Зарегистрировано Управлением юстиции Павлодарской области 12 апреля 1999 года № 127. Утратило силу решением акима Павлодарской области от 6 августа 2001 года № 145
title:
  rus: О закреплении водоемов области для промыслового и любительского рыболовства
  kaz: Облыстың су қоймаларын кәсіпқой және әуесқой балық аулаушыларға бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-09
approved_by:
- '164000000003'
version_date:
  kaz: 1999-03-09
  rus: 1999-03-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/3184/kaz/09.03.1999
  rus: https://zan.gov.kz/client/#!/doc/3184/rus/09.03.1999
