act_code: '195211'
requisite: Решение Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18. Зарегистрировано в Департаменте юстиции Павлодарской области 3 апреля 2024 года № 7531-14
title:
  rus: Об утверждении Правил и размера оказания жилищной помощи по городу Аксу
  kaz: Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің Қағидалары мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '164004000002'
version_date:
  kaz: 2024-06-28
  rus: 2024-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195211/kaz/28.06.2024
  rus: https://zan.gov.kz/client/#!/doc/195211/rus/28.06.2024
caused_by:
  code: '198341'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 28 июня 2024 года № 134/20. Зарегистрировано в Департаменте юстиции Павлодарской области 1 июля 2024 года № 7567-14
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 28 марта 2024 года № 119/18 «Об определении размера и порядка оказания жилищной помощи по городу Аксу»
    kaz: Ақсу қалалық мәслихатының 2024 жылғы 28 наурыздағы «Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» № 119/18 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198341/rus
