act_code: '195211'
requisite: Решение Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18. Зарегистрировано в Департаменте юстиции Павлодарской области 3 апреля 2024 года № 7531-14
title:
  rus: Об утверждении Правил и размера оказания жилищной помощи по городу Аксу
  kaz: Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің Қағидалары мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '164004000002'
version_date:
  kaz: 2025-08-15
  rus: 2025-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/195211/kaz/15.08.2025
  rus: https://zan.gov.kz/client/#!/doc/195211/rus/15.08.2025
caused_by:
  code: '213940'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 15 августа 2025 года № 218/37. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 сентября 2025 года № 36803
  title:
    rus: О внесении изменения в решение Аксуского городского маслихата от 28 марта 2024 года № 119/18 «Об определении размера и порядка оказания жилищной помощи по городу Аксу»
    kaz: Ақсу қалалық мәслихатының 2024 жылғы 28 наурыздағы № 119/18 «Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213940/rus
