act_code: '92813'
requisite: Решение маслихата Майского района Павлодарской области от 14 июля 2015 года № 5/50. Зарегистрировано Департаментом юстиции Павлодарской области 14 августа 2015 года № 4657
title:
  rus: Об утверждении  границ оценочных зон и поправочных коэффициентов к базовым  ставкам платы за земельные участки в  населенных пунктах Майского района Павлодарской области
  kaz: Павлодар облысы Май ауданының елді мекендерінде жер телімдер үшін бағалау аймақтарының шекараларын және төлемақы базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2015-07-14
approved_by:
- '164010000002'
version_date:
  kaz: 2015-07-14
  rus: 2015-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/92813/kaz/14.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92813/rus/14.07.2015
