act_code: '42042'
requisite: Решение маслихата Иртышского района Павлодарской области от 22 октября 2008 года № 57-10-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 22 октября 2008 года № 12-7-77
title:
  rus: Об утверждении инструкции по предоставлению и размерам социальных выплат отдельным категориям граждан в 2008 году
  kaz: 2008 жылда жеке санаттағы азаматтарға әлеуметтік төлемдердің берілуі және мөлшері жөніндегі Нұсқауын бекіту туралы
form: РЕШ
type_codes:
- ИНСТ
- РЕШ
approved_on: 2008-10-22
approved_by:
- '164007000002'
version_date:
  kaz: 2008-10-22
  rus: 2008-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/42042/kaz/22.10.2008
  rus: https://zan.gov.kz/client/#!/doc/42042/rus/22.10.2008
