act_code: '152379'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 8 января 2021 года № 497/64. Зарегистрировано Департаментом юстиции Павлодарской области 22 января 2021 года № 7191. Утратило силу решением Экибастузского городского маслихата Павлодарской области от 29 сентября 2022 года № 164/22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога на неиспользуемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения города Экибастуз
  kaz: Екібастұз қаласының Қазақстан Республикасының жер заңнамасына сәйкес пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлеріне жер салығының базалық мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '164013000002'
version_date:
  kaz: 2021-01-08
  rus: 2021-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/152379/kaz/08.01.2021
  rus: https://zan.gov.kz/client/#!/doc/152379/rus/08.01.2021
