act_code: '162896'
requisite: Решение Актогайского районного маслихата Павлодарской области от 24 декабря 2021 года № 68/14. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 января 2022 года № 26336
title:
  rus: Об Актогайском районном бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Ақтоғай аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164003000002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/162896/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/162896/rus/25.03.2022
caused_by:
  code: '165571'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 25 марта 2022 года № 88/18
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 24 декабря 2021 года № 68/14 «Об Актогайском районном бюджете на 2022-2024 годы»
    kaz: Ақтоғай аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 68/14 «2022-2024 жылдарға арналған Ақтоғай аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165571/rus
