act_code: '102528'
requisite: Решение маслихата Иртышского района Павлодарской области от 20 апреля 2016 года № 12-3-6. Зарегистрировано Департаментом юстиции Павлодарской области 20 мая 2016 года № 5128. Утратило силу решением маслихата Иртышского района Павлодарской области от 23 мая 2018 года № 130-26-6 (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Иртышского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің  және Ертіс ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-04-20
approved_by:
- '164007000002'
version_date:
  kaz: 2016-07-13
  rus: 2016-07-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/102528/kaz/13.07.2016
  rus: https://zan.gov.kz/client/#!/doc/102528/rus/13.07.2016
caused_by:
  code: '105510'
  requisite: Решение маслихата Иртышского района Павлодарской области от 13 июля 2016 года № 19-4-6. Зарегистрировано Департаментом юстиции Павлодарской области 15 августа 2016 года № 5206. Утратило силу решением маслихата Иртышского района Павлодарской области от 23 мая 2018 года № 130-26-6 (вводится в действие по истечении десяти календарных дней со дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение Иртышского районного маслихата от 20 апреля 2016 года № 12-3-6 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Иртышского района»
    kaz: Ертіс аудандық мәслихатының 2016  жылғы 20 сәуірдегі «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ертіс ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» № 12-3-6 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105510/rus
