act_code: '190234'
requisite: Решение исполняющего обязанности акима поселка Ленинский города Павлодара от 15 декабря 2023 года № 13
title:
  rus: О переименование улиц поселка Ленинский города Павлодара
  kaz: Павлодар қаласы Ленин кентінің көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '164002001001'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190234/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190234/rus/15.12.2023
