act_code: '122707'
requisite: Решение маслихата Павлодарской области от 14 июня 2018 года № 236/22. Зарегистрировано Департаментом юстиции Павлодарской области 20 июня 2018 года № 5997. Утратило силу решением Павлодарского областного маслихата от 22 апреля 2021 года № 21/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном лекарственном обеспечении
  kaz: Қосымша дәрі-дәрмекпен қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-14
approved_by:
- '164000000002'
version_date:
  kaz: 2020-03-20
  rus: 2020-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/122707/kaz/20.03.2020
  rus: https://zan.gov.kz/client/#!/doc/122707/rus/20.03.2020
caused_by:
  code: '140796'
  requisite: Решение маслихата Павлодарской области от 20 марта 2020 года № 448/38. Зарегистрировано Департаментом юстиции Павлодарской области 31 марта 2020 года № 6777. Утратило силу решением Павлодарского областного маслихата от 22 апреля 2021 года № 21/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения и дополнения в решение Павлодарского областного маслихата от 14 июня 2018 года № 236/22 «О дополнительном лекарственном обеспечении»
    kaz: Павлодар облыстық мәслихатының 2018 жылғы 14 маусымдағы «Қосымша дәрі-дәрмекпен қамтамасыз ету туралы» № 236/22 шешіміне өзгерту мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140796/rus
