act_code: '209550'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 24 апреля 2025 года № 240/29
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Экибастуз на 2025-2029 годы
  kaz: 2025-2029 жылдарға арналған Екібастұз қаласы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-24
approved_by:
- '164013000002'
version_date:
  kaz: 2025-04-24
  rus: 2025-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/209550/kaz/24.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209550/rus/24.04.2025
