act_code: '189634'
requisite: Решение Аксуского городского маслихата Павлодарской области от 5 декабря 2023 года № 71/10. Зарегистрировано в Департаменте юстиции Павлодарской области 6 декабря 2023 года № 7437-14. Утратило силу решением Аксуского городского маслихата Павлодарской области от 9 июня 2026 года № 282/49 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Аксу
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ақсу қаласының мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-05
approved_by:
- '164004000002'
version_date:
  kaz: 2025-08-15
  rus: 2025-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/189634/kaz/15.08.2025
  rus: https://zan.gov.kz/client/#!/doc/189634/rus/15.08.2025
caused_by:
  code: '213293'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 15 августа 2025 года № 219/37. Утратило силу решением Аксуского городского маслихата Павлодарской области от 9 июня 2026 года № 282/49 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 5 декабря 2023 года № 71/10 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Аксу»
    kaz: Ақсу қалалық мәслихатының 2023 жылғы 5 желтоқсандағы № 71/10 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ақсу қаласының мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213293/rus
