act_code: '162247'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 23 декабря 2021 года № 84/13. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26052
title:
  rus: Об Экибастузском городском бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '164013000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162247/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162247/rus/23.12.2021
