act_code: '162247'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 23 декабря 2021 года № 84/13. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26052
title:
  rus: Об Экибастузском городском бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '164013000002'
version_date:
  kaz: 2022-09-29
  rus: 2022-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/162247/kaz/29.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162247/rus/29.09.2022
caused_by:
  code: '172280'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 29 сентября 2022 года № 162/22
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 23 декабря 2021 года № 84/13 «Об Экибастузском городском бюджете на 2022 - 2024 годы»
    kaz: Екібастұз қалалық мәслихатының 2021 жылғы 23 желтоқсандағы «2022 - 2024 жылдарға арналған Екібастұз қалалық бюджеті туралы» № 84/13 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172280/rus
