act_code: '65941'
requisite: Решение акима Сатинского сельского округа Майского района Павлодарской области от 18 мая 2012 года № 1. Зарегистрировано Управлением юстиции Майского района Павлодарской области 06 июня 2012 года № 12-10-127
title:
  rus: О присвоении наименований улицам в Сатинском сельском округе Майского района
  kaz: Май ауданы Саты селолық округінің көше атауларын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-18
approved_by:
- '164010006001'
version_date:
  kaz: 2012-05-18
  rus: 2012-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/65941/kaz/18.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65941/rus/18.05.2012
