act_code: '82774'
requisite: Решение маслихата Иртышского района Павлодарской области от 31 июля 2014 года № 155-31-5. Зарегистрировано Департаментом юстиции Павлодарской области 27 августа 2014 года № 3966. Утратило силу решением Иртышского районного маслихата Павлодарской области от 27 декабря 2022 года № 107-27-7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количества представителей жителей сел для участия в сходе местного сообщества на территории Кызылжарского сельского округа Иртышского района
  kaz: Ертіс ауданы Қызылжар ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-07-31
approved_by:
- '164007000002'
version_date:
  kaz: 2014-07-31
  rus: 2014-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/82774/kaz/31.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82774/rus/31.07.2014
