act_code: '193624'
requisite: Решение акима Баянаульского района Павлодарской области от 26 февраля 2024 года № 2/02. Утратило силу решением акима Баянаульского района Павлодарской области от 2 октября 2024 года № 9/10 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба на территории поселка Майкаин Баянаульского района Павлодарской области
  kaz: Павлодар облысы Баянауыл ауданы Майқайың кенті аумағында жергілікті ауқымдағы техногенді сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-26
approved_by:
- '164005000003'
version_date:
  kaz: 2024-02-26
  rus: 2024-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/193624/kaz/26.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193624/rus/26.02.2024
