act_code: '76464'
requisite: Решение маслихата Железинского района Павлодарской области от 27 декабря 2013 года № 164-5/23. Зарегистрировано Департаментом юстиции Павлодарской области 09 января 2014 года № 3659
title:
  rus: О бюджете Железинского района на 2014 - 2016 годы
  kaz: Железинка ауданының 2014 - 2016 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-27
approved_by:
- '164006000002'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/76464/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/76464/rus/25.12.2014
caused_by:
  code: '85395'
  requisite: Решение маслихата Железинского района Павлодарской области от 25 декабря 2014 года № 268-5/32. Зарегистрировано Департаментом юстиции Павлодарской области 26 декабря 2014 года № 4238
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 27 декабря 2013 года № 164-5/23 "О бюджете Железинского района на 2014 - 2016 годы"
    kaz: Железинка аудандық мәслихатының 2013 жылғы 27 желтоқсандағы "Железинка ауданының 2014 - 2016 жылдарға арналған бюджеті туралы" № 164-5/23 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/85395/rus
