act_code: '188948'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 21 ноября 2023 года № 9/103. Зарегистрировано в Департаменте юстиции Павлодарской области 24 ноября 2023 года № 7425-14. Утратило силу решением Павлодарского районного маслихата Павлодарской области от 11 июня 2026 года № 47/395 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Павлодарского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Павлодар ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-21
approved_by:
- '164014000002'
version_date:
  kaz: 2023-11-21
  rus: 2023-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/188948/kaz/21.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188948/rus/21.11.2023
