act_code: '36369'
requisite: Решение маслихата Павлодарской области от 14 декабря 2007 года № 36/3. Зарегистрировано управлением юстиции города Павлодара Павлодарской области 24 декабря 2007 года за № 3099
title:
  rus: Об областном бюджете на 2008 год
  kaz: 2008 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-14
approved_by:
- '164000000002'
version_date:
  kaz: 2008-10-24
  rus: 2008-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36369/kaz/24.10.2008
  rus: https://zan.gov.kz/client/#!/doc/36369/rus/24.10.2008
caused_by:
  code: '42115'
  requisite: Решение Павлодарского областного маслихата от 24 октября 2008 года № 134/10. Зарегистрировано департаментом юстиции Павлодарской области 29 октября 2008 года № 3126
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата (III сессия, IV созыв) от 14 декабря 2007 года № 36/3 "Об областном бюджете на 2008 год"
    kaz: Облыстық мәслихаттың (IV сайланған III сессиясы) 2007 жылғы 14 желтоқсандағы "2008 жылға арналған облыстық бюджет туралы" № 36/3 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/42115/rus
