act_code: '204879'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 25 декабря 2024 года № 212/24
title:
  rus: О Павлодарском городском бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Павлодар қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '164002000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204879/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204879/rus/25.12.2024
