act_code: '85972'
requisite: Решение маслихата Качирского района Павлодарской области от 25 декабря 2014 года № 3/39. Зарегистрировано Департаментом юстиции Павлодарской области 14 января 2015 года № 4269
title:
  rus: О бюджете Качирского района на 2015 - 2017 годы
  kaz: 2015 - 2017 жылдарға арналған Качир ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '164008000002'
version_date:
  kaz: 2015-04-10
  rus: 2015-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/85972/kaz/10.04.2015
  rus: https://zan.gov.kz/client/#!/doc/85972/rus/10.04.2015
caused_by:
  code: '89288'
  requisite: Решение маслихата Качирского района Павлодарской области от 10 апреля 2015 года № 1/42. Зарегистрировано Департаментом юстиции Павлодарской области 05 мая 2015 года № 4455
  title:
    rus: О внесении изменений и дополнения в решение Качирского районного маслихата (XXXIX – сессия, V - созыв) от 25 декабря 2014 года № 3/39 «О бюджете Качирского района на 2015 - 2017 годы»
    kaz: Качир аудандық мәслихатының (V сайланған XXХIХ сессиясы) 2014 жылғы 25 желтоқсандағы «2015 - 2017 жылдарға арналған Качир ауданының бюджеті туралы» № 3/39 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89288/rus
