act_code: '15649'
requisite: Решение Павлодарского областного маслихата (XX сессия, II созыв) от 24 июня 2002 года N 46/20. Зарегистрировано Управлением юстиции Павлодарской области 29 июля 2002 года за N 1375. Утратило силу решением маслихата Павлодарской области от 16 февраля 2011 года N 352/32
title:
  rus: О стратегическом плане развития области до 2010 года
  kaz: Облыстың 2010 жылға дейіңге дамуының стратегилық жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-06-22
approved_by:
- '164000000002'
version_date:
  kaz: 2002-06-23
  rus: 2002-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/15649/kaz/23.06.2002
  rus: https://zan.gov.kz/client/#!/doc/15649/rus/23.06.2002
