act_code: '60703'
requisite: Решение акима Надаровского сельского округа Успенского района Павлодарской области от 06 октября 2011 года N 10. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 07 октября 2011 года N 12-12-111. Утратило силу решением акима Надаровского сельского округа Успенского района Павлодарской области от 01 июля 2016 года № 1
title:
  rus: Об утверждении регламента оказания государственной услуги
  kaz: Мемлекеттік қызмет көрсету регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2011-10-06
approved_by:
- '164011011001'
version_date:
  kaz: 2011-10-06
  rus: 2011-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/60703/kaz/06.10.2011
  rus: https://zan.gov.kz/client/#!/doc/60703/rus/06.10.2011
