act_code: '150988'
requisite: Решение Железинского районного маслихата Павлодарской области от 24 декабря 2020 года № 508/6. Зарегистрировано Департаментом юстиции Павлодарской области 30 декабря 2020 года № 7141
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения, культуры, являющимся гражданскими служащими и работающим в сельской местности
  kaz: Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін әлеуметтік қамсыздандыру және мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '164006000002'
version_date:
  kaz: 2022-03-18
  rus: 2022-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/150988/kaz/18.03.2022
  rus: https://zan.gov.kz/client/#!/doc/150988/rus/18.03.2022
caused_by:
  code: '166127'
  requisite: Решение Железинского районного маслихата Павлодарской области от 18 марта 2022 года № 132/7. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27452
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 24 декабря 2020 года № 508/6 «Об установлении повышенных окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, спорта, ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими и работающим в сельских населенных пунктах Железинского района, а также указанным специалистам, работающим в государственных организациях, финансируемых из местного бюджета»
    kaz: Железин аудандық мәслихаттың 2020 жылғы 24 желтоқсандағы № 508/6 «Азаматтық қызметшілер болып табылатын және ауылдық жерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға, сондай-ақ жергілікті бюджеттен қаржыландырылатын мемлекеттік ұйымдарда жұмыс істейтін аталған мамандарға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелерді белгілеу туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166127/rus
