act_code: '194091'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 1 марта 2024 года № 1/15. Зарегистрировано в Департаменте юстиции Павлодарской области 7 марта 2024 года № 7500-14. Утратило силу решением маслихата района Тереңкөл Павлодарской области от 16 февраля 2026 года № 1/40 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в районе Тереңкөл
  kaz: Тереңкөл ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салықтар мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-01
approved_by:
- '164008000002'
version_date:
  kaz: 2024-03-01
  rus: 2024-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/194091/kaz/01.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194091/rus/01.03.2024
