act_code: '46248'
requisite: Решение маслихата города Экибастуза Павлодарской области от 25 апреля 2009 года № 170/16. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 28 мая 2009 года за № 12-3-231. Утратило силу решением маслихата города Экибастуза Павлодарской области от 25 декабря 2009 года № 237/19
title:
  rus: О Правилах предоставления жилищной помощи малообеспеченным семьям (гражданам) по оплате содержания жилища, потребления коммунальных услуг и компенсации на ремонт общего имущества объекта кондоминиума по городу Экибастузу
  kaz: Екібастұз қаласы бойынша кондоминиум объектілерінің жалпы мүлкін жөндеуге коммуналды қызметтері мен отемақыны пайдалану, тұрғын үйді күту бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін беру Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-04-25
approved_by:
- '164013000002'
version_date:
  kaz: 2009-07-27
  rus: 2009-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/46248/kaz/27.07.2009
  rus: https://zan.gov.kz/client/#!/doc/46248/rus/27.07.2009
caused_by:
  code: '47621'
  requisite: Решение маслихата города Экибастуза Павлодарской области от 27 июля 2009 года № 186/17. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 28 августа 2009 года № 12-3-240. Утратило силу решением маслихата города Экибастуза Павлодарской области от 21 августа 2014 года № 258/31
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата (очередная XVI сессия, IV созыв) от 25 апреля 2009 года № 170/16 "О правилах предоставления жилищной помощи малообеспеченным семьям (гражданам) по оплате содержания жилища, потребления коммунальных услуг и компенсации на ремонт общего имущества объекта кондоминиума по городу Экибастузу"
    kaz: Екібастұз қалалық мәслихатының 2009 жылғы 25 сәуірдегі (IV шақырылған кезекті XVI сессия) "Екібастұз қаласы бойынша кондоминиум объектілерінің жалпы мүлкін жөндеуге коммуналдық қызметтері мен өтемақыны пайдалану, тұрғын үйді күту бойынша табысы аз отбасыларға (азаматтарға) тұрғын үй көмегін беру Ережелері туралы" № 170/16 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/47621/rus
