act_code: '34953'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2007 жылғы 15 тамыздағы № 301 шешімі. Павлодар облысының Баянауыл ауданының Әділет басқармасында 2007 жылғы 7 қыркүйекте № 12-5-42 тіркелді
title:
  rus: Жер учаскелерін жер пайдаланушыларға жалға берген кездегі төлемақының базалық ставкасын бекіту туралы
  kaz: Жер учаскелерін жер пайдаланушыларға жалға берген кездегі төлемақының базалық ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-08-15
approved_by:
- '164005000002'
version_date:
  kaz: 2007-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/34953/kaz/15.08.2007
