act_code: '12955'
requisite: Решение маслихата Павлодарской области от 25 апреля 2002 года (XIX (внеочередной) сессии, II созыва) № 30/19. Зарегистрировано Управлением юстиции Павлодарской области 30 мая 2002 года за № 1242
title:
  rus: О плане мероприятий на 2002 год по реализации областной программы «Молодежь» на 2001 – 2002 годы
  kaz: 2001 – 2002 жылдарға арналған «Жастар» облыстық бағдарламасын жүзеге асыру жөніндегі 2002 жылға арналған іс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-24
approved_by:
- '164000000002'
version_date:
  kaz: 2002-04-24
  rus: 2002-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/12955/kaz/24.04.2002
  rus: https://zan.gov.kz/client/#!/doc/12955/rus/24.04.2002
