act_code: '19445'
requisite: Решение Экибастузского городского маслихата от 24 февраля 2004 года № 3/47. Зарегистрировано департаментом юстиции Павлодарской области 2 апреля 2004 года за № 2376. Утратило силу решением маслихата города Экибастуза Павлодарской области от 27 июля 2009 года № 201/17
title:
  rus: О правилах размещения твердых бытовых отходов в Экибастузском регионе
  kaz: Екiбастұз аймағында тұрмыстық-қатты қалдықтарды орналастыру Қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-02-24
approved_by:
- '164013000002'
version_date:
  kaz: 2004-02-24
  rus: 2004-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/19445/kaz/24.02.2004
  rus: https://zan.gov.kz/client/#!/doc/19445/rus/24.02.2004
