act_code: '155802'
requisite: Решение Павлодарского областного маслихата от 22 апреля 2021 года № 20/3. Зарегистрировано Департаментом юстиции Павлодарской области 12 мая 2021 года № 7279. Утратило силу решением Павлодарского областного маслихата от 14 апреля 2022 года № 145/12 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников по Павлодарской области
  kaz: Павлодар облысы бойынша жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-22
approved_by:
- '164000000002'
version_date:
  kaz: 2021-04-22
  rus: 2021-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/155802/kaz/22.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155802/rus/22.04.2021
