act_code: '162577'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 24 декабря 2021 года № 18/82. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26210
title:
  rus: О Павлодарском районном бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Павлодар аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164014000002'
version_date:
  kaz: 2022-10-27
  rus: 2022-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/162577/kaz/27.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162577/rus/27.10.2022
caused_by:
  code: '173255'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 27 октября 2022 года № 30/167
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 24 декабря 2021 года № 18/82 «О Павлодарском районном бюджете на 2022-2024 годы»
    kaz: Павлодар аудандық мәслихатының 2021 жылғы 24 желтоқсандағы «2022-2024 жылдарға арналған Павлодар аудандық бюджеті туралы» № 18/82 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173255/rus
