act_code: '3177'
requisite: Решение ХХII сессии I созыва Павлодарского областного Маслихата от 18 декабря 1998 года. Зарегистрировано Управлением юстиции Павлодарской области 11 марта 1999 года за № 115. Утратило силу решением маслихата Павлодарской области от 20 июня 2009 года № 107/6
title:
  rus: Об утверждении Положения о пойме реки Иртыш
  kaz: Ертiс өзенi қойнауы жөнiндегi Ереженi бекiту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1998-12-18
approved_by:
- '164000000002'
version_date:
  kaz: 1998-12-18
  rus: 1998-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/3177/kaz/18.12.1998
  rus: https://zan.gov.kz/client/#!/doc/3177/rus/18.12.1998
