act_code: '56516'
requisite: Решение маслихата Щербактинского района Павлодарской области от 24 декабря 2010 года № 155/32. Зарегистрировано Управлением юстиции Щербактинского района Павлодарской области 31 декабря 2010 года № 12-13-118
title:
  rus: О районном бюджете на 2011 - 2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '164012000002'
version_date:
  kaz: 2014-07-21
  rus: 2014-07-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/56516/kaz/21.07.2014
  rus: https://zan.gov.kz/client/#!/doc/56516/rus/21.07.2014
