act_code: '85757'
requisite: Решение от 24.12.2014 № 341/48, Маслихат города Павлодар
title:
  rus: 'О бюджете города Павлодара на 2015 - 2017 годы '
  kaz: 'Павлодар қаласының 2015-2017 жылдарға арналған бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '164002000002'
version_date:
  kaz: 2015-05-26
  rus: 2015-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/85757/kaz/26.05.2015
  rus: https://zan.gov.kz/client/#!/doc/85757/rus/26.05.2015
caused_by:
  code: '90114'
  requisite: Решение № 389/53 от 26.05.2015, Маслихат города Павлодар
  title:
    rus: 'О внесении изменений и дополнений в решение Павлодарского городского маслихата от 24 декабря 2014 года № 341/48 «О бюджете города Павлодара на 2015 - 2017 годы» '
    kaz: 'Павлодар қалалық мәслихатының 2014 жылғы 24 желтоқсандағы «Павлодар қаласының 2015-2017 жылдарға арналған бюджеті туралы» № 341/48 шешіміне өзгерістер мен толықтырулар енгізу туралы '
  link: https://zan.gov.kz/client/#!/doc/90114/rus
