act_code: '140419'
requisite: Решение маслихата Щербактинского района Павлодарской области от 13 марта 2020 года № 238/71. Зарегистрировано Департаментом юстиции Павлодарской области 19 марта 2020 года № 6758
title:
  rus: Об  установлении повышенных  окладов и тарифных ставок специалистам в области здравоохранения, социального обеспечения, образования, культуры, архивного дела, спорта, ветеринарии, лесного хозяйства и особо охраняемых природных территорий, являющимся гражданскими служащими  и работающим в сельских населенных пунктах Щербактинского района
  kaz: Шарбақты ауданының азаматтық қызметші болып табылатын және ауылдық елді мекендерде жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, архив ісі, спорт, ветеринария, орман шаруашылығы және ерекше қорғалатын табиғи аумақтар саласындағы мамандарға  жоғарылатылған айлықақылар мен тарифтік мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-13
approved_by:
- '164012000002'
version_date:
  kaz: 2020-03-13
  rus: 2020-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/140419/kaz/13.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140419/rus/13.03.2020
