act_code: '16390'
requisite: Решение Павлодарского областного маслихата (ХХҮІІ созыва, созыва ІІ) от 19 июня 2003 года № 134/27. Зарегистрировано Управлением юстиции Павлодарской области 2 июля 2003 года за № 1915
title:
  rus: Об индустриальной стратегии области на период до 2010 года
  kaz: Облыстың 2010 жылға дейінгі кезеңге арналған индустриалдық стратегиясы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-06-18
approved_by:
- '164000000002'
version_date:
  kaz: 2003-06-18
  rus: 2003-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/16390/kaz/18.06.2003
  rus: https://zan.gov.kz/client/#!/doc/16390/rus/18.06.2003
