act_code: '116139'
requisite: Решение маслихата Успенского района Павлодарской области от 8 ноября 2017 года № 102/21. Зарегистрировано Департаментом юстиции Павлодарской области 23 ноября 2017 года № 5698
title:
  rus: Об утверждении положения о награждении Почетной грамотой Успенского района
  kaz: Успен ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2017-11-08
approved_by:
- '164011000002'
version_date:
  kaz: 2023-10-02
  rus: 2023-10-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/116139/kaz/02.10.2023
  rus: https://zan.gov.kz/client/#!/doc/116139/rus/02.10.2023
caused_by:
  code: '186767'
  requisite: Решение Успенского районного маслихата Павлодарской области от 2 октября 2023 года № 45/8. Зарегистрировано в Департаменте юстиции Павлодарской области 3 октября 2023 года № 7398-14
  title:
    rus: О внесении изменений в решение Успенского районного маслихата от 8 ноября 2017 года № 102/21 «Об утверждении положения о награждении Почетной грамотой Успенского района»
    kaz: Успен аудандық мәслихатының 2017 жылғы 8 қарашадағы № 102/21 «Успен ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186767/rus
