act_code: '164895'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 21 февраля 2022 года № 5/17. Отменено решением маслихата района Тереңкөл Павлодарской области от 17 апреля 2023 года № 8/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат маслихата района Тереңкөл»
  kaz: «Тереңкөл аудандық мәслихат аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2022-02-21
approved_by:
- '164008000002'
version_date:
  kaz: 2022-02-21
  rus: 2022-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/164895/kaz/21.02.2022
  rus: https://zan.gov.kz/client/#!/doc/164895/rus/21.02.2022
