act_code: '132665'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 13 июня 2019 года № 7/45. Зарегистрировано Департаментом юстиции Павлодарской области 18 июня 2019 года № 6424
title:
  rus: Об утверждении положения о награждении Почетной грамотой района Тереңкөл
  kaz: Тереңкөл ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-06-13
approved_by:
- '164008000002'
version_date:
  kaz: 2023-06-15
  rus: 2023-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/132665/kaz/15.06.2023
  rus: https://zan.gov.kz/client/#!/doc/132665/rus/15.06.2023
caused_by:
  code: '183143'
  requisite: Решение маслихата района Тереңкөл Павлодарской области от 15 июня 2023 года № 7/4. Зарегистрировано Департаментом юстиции Павлодарской области 21 июня 2023 года № 7349-14
  title:
    rus: О внесении изменений в решение маслихата района Тереңкөл от 13 июня 2019 года № 7/45 «Об утверждении положения о награждении Почетной грамотой района Тереңкөл»
    kaz: Тереңкөл аудандық мәслихатының 2019 жылғы 13 маусымдағы № 7/45 «Тереңкөл ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183143/rus
