act_code: '195141'
requisite: Решение акима Актогайского района Павлодарской области от 2 апреля 2024 года № 2р. Утратило силу решением акима Актогайского района Павлодарской области от 8 апреля 2024 года № 3р (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба в селе Жалаулы Жалаулинского сельского округа Актогайского района Павлодарской области
  kaz: Павлодар облысы Ақтоғай ауданының Жалаулы ауылдық округінің Жалаулы ауылы аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-02
approved_by:
- '164003000003'
version_date:
  kaz: 2024-04-02
  rus: 2024-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/195141/kaz/02.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195141/rus/02.04.2024
