act_code: '3130'
requisite: Павлодар облыстық мәслихатының 1999 жылғы 23 сәуірдегі шешімі. Павлодар облысының Әділет басқармасында 1999 жылғы 3 маусымда № 165 болып тіркелді
title:
  rus: Медициналық мекемелер қызметкерлерінің еңбек ақысы және балалары бар отбасылардың жәрдемақысы бойынша берешектерді өтеу жөніндегі қосымша шаралар туралы
  kaz: Медициналық мекемелер қызметкерлерінің еңбек ақысы және балалары бар отбасылардың жәрдемақысы бойынша берешектерді өтеу жөніндегі қосымша шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-22
approved_by:
- '164000000002'
version_date:
  kaz: 1999-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3130/kaz/22.04.1999
