act_code: '56438'
requisite: Павлодар облысы Май аудандық мәслихатының 2010 жылғы 23 желтоқсандағы № 2/30 шешімі. Павлодар облысының Әділет департаментінде 2010 жылғы 30 желтоқсанда № 12-10-101 тіркелді
title:
  rus: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '164010000002'
version_date:
  kaz: 2010-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/56438/kaz/23.12.2010
