act_code: '147065'
requisite: Решение акима Казанского сельского округа Майского района Павлодарской области от 22 сентября 2020 года № 8. Зарегистрировано Департаментом юстиции Павлодарской области 5 октября 2020 года № 6974. Утратило силу решением акима Казанского сельского округа Майского района Павлодарской области от 3 февраля 2021 года № 2 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий на территории «Бригада № 3» расположенного в Казанском сельском округе Майского района
  kaz: Май ауданы Қазан ауылдық округінде орналасқан «№ 3 Бригада» аумағында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-22
approved_by:
- '164010005002'
version_date:
  kaz: 2020-09-22
  rus: 2020-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/147065/kaz/22.09.2020
  rus: https://zan.gov.kz/client/#!/doc/147065/rus/22.09.2020
