act_code: '52873'
requisite: Решение маслихата города Экибастуза Павлодарской области от 14 апреля 2010 года № 248/21. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области от 28 мая 2010 года № 12-3-269. Утратило силу решением маслихата города Экибастуза Павлодарской области от 21 августа 2014 года № 258/31
title:
  rus: Об оказании социальной помощи для льготного проезда на пригородном автобусном транспорте (кроме такси) студентам из малообеспеченных семей, детям-сиротам, оставшимся без попечения родителей, проживающим в поселке Солнечный города Экибастуза и обучающимся по очной форме в высших и средних специальных учебных заведениях города Экибастуза
  kaz: Екібастұз қаласының Солнечный кентінде тұратын, табысы аз отбасылардың студенттеріне, ата-анасының қамқорлығынсыз қалған жетім балаларға және Екібастұз қаласының жоғарғы және орта арнаулы оқу орындарының күндізгі бөлімінде оқитындарына қала жанындағы автобус көлігінде (таксиден басқа) жеңілдікпен жүруі үшін әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-14
approved_by:
- '164013000002'
version_date:
  kaz: 2010-04-14
  rus: 2010-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/52873/kaz/14.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52873/rus/14.04.2010
