act_code: '124995'
requisite: Решение акима Чигириновского сельского округа Щербактинского района Павлодарской области от 14 сентября 2018 года № 09-р. Зарегистрировано Департаментом юстиции Павлодарской области 5 октября 2018 года № 6073
title:
  rus: О переименовании некоторых улиц села Чигириновка Чигириновского сельского округа Щербактинского района
  kaz: Шарбақты ауданы Чигиринов ауылдық округінің Чигиринов ауылындағы кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-09-14
approved_by:
- '164012014002'
version_date:
  kaz: 2018-09-14
  rus: 2018-09-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/124995/kaz/14.09.2018
  rus: https://zan.gov.kz/client/#!/doc/124995/rus/14.09.2018
