act_code: '174258'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 25 ноября 2022 года № 31/176. Утратило силу решением Павлодарского районного маслихата Павлодарской области от 19 октября 2023 года № 8/97 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села для участия в сходе местного сообщества на территории Чернорецкого сельского округа Павлодарского района
  kaz: Павлодар ауданы Чернорецк ауылдық округінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын айқындау тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-11-25
approved_by:
- '164014000002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/174258/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174258/rus/25.11.2022
