act_code: '136581'
requisite: Решение акима сельского округа Ақжол Актогайского района Павлодарской области от 25 ноября 2019 года № 4. Зарегистрировано Департаментом юстиции Павлодарской области 29 ноября 2019 года № 6640
title:
  rus: Об установлении публичного сервитута на территории сельского округа Ақжол
  kaz: Ақжол ауылдық округінің аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-25
approved_by:
- '164003007002'
version_date:
  kaz: 2019-11-25
  rus: 2019-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/136581/kaz/25.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136581/rus/25.11.2019
