act_code: '137840'
requisite: Решение маслихата Павлодарского района Павлодарской области от 26 декабря 2019 года № 65/288. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2019 года № 6697
title:
  rus: О бюджетах сельских округов и села Ольгинка Павлодарского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Павлодар ауданының ауылдық округтері және Ольгинка ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '164014000002'
version_date:
  kaz: 2020-10-23
  rus: 2020-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/137840/kaz/23.10.2020
  rus: https://zan.gov.kz/client/#!/doc/137840/rus/23.10.2020
caused_by:
  code: '147856'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 23 октября 2020 года № 76/338. Зарегистрировано Департаментом юстиции Павлодарской области 28 октября 2020 года № 6998
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 26 декабря 2019 года № 65/288 «О бюджетах сельских округов и села Ольгинка Павлодарского района на 2020 - 2022 годы»
    kaz: Павлодар аудандық мәслихатының 2019 жылғы 26 желтоқсандағы «2020 - 2022 жылдарға арналған Павлодар ауданының ауылдық округтері және Ольгинка ауылының бюджеттері туралы» № 65/288 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147856/rus
