act_code: '137840'
requisite: Решение маслихата Павлодарского района Павлодарской области от 26 декабря 2019 года № 65/288. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2019 года № 6697
title:
  rus: О бюджетах сельских округов и села Ольгинка Павлодарского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Павлодар ауданының ауылдық округтері және Ольгинка ауылының бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-26
approved_by:
- '164014000002'
version_date:
  kaz: 2020-06-03
  rus: 2020-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/137840/kaz/03.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137840/rus/03.06.2020
caused_by:
  code: '143685'
  requisite: Решение маслихата Павлодарского района Павлодарской области от 3 июня 2020 года № 72/318. Зарегистрировано Департаментом юстиции Павлодарской области 9 июня 2020 года № 6843
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 26 декабря 2019 года № 65/288 «О бюджетах сельских округов и села Ольгинка Павлодарского района на 2020 - 2022 годы»
    kaz: Павлодар аудандық мәслихатының 2019 жылғы 26 желтоқсандағы «2020 - 2022 жылдарға арналған Павлодар ауданының ауылдық округтері және Ольгинка ауылының бюджеттері туралы» № 65/288 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143685/rus
