act_code: '162672'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 30 декабря 2021 года № 89/13
title:
  rus: О бюджете сельских округов, сел и поселков города Экибастуза на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '164013000002'
version_date:
  kaz: 2022-12-08
  rus: 2022-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/162672/kaz/08.12.2022
  rus: https://zan.gov.kz/client/#!/doc/162672/rus/08.12.2022
caused_by:
  code: '175006'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 8 декабря 2022 года № 175/24
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 30 декабря 2021 года № 89/13 «О бюджете сельских округов, сел и поселков города Экибастуза на 2022 - 2024 годы»
    kaz: Екібастұз қалалық мәслихатының 2021 жылғы 30 желтоқсандағы № 89/13 «2022 - 2024 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175006/rus
