act_code: '166464'
requisite: Решение Успенского районного маслихата Павлодарской области от 11 апреля 2022 года № 91/14. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 апреля 2022 года № 27582
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Успенского района
  kaz: Успен ауданының елдi мекендеріндегі бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-11
approved_by:
- '164011000002'
version_date:
  kaz: 2022-04-11
  rus: 2022-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/166464/kaz/11.04.2022
  rus: https://zan.gov.kz/client/#!/doc/166464/rus/11.04.2022
