act_code: '204837'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 25 декабря 2024 года № 208/25
title:
  rus: Об Экибастузском городском бюджете на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '164013000002'
version_date:
  kaz: 2025-11-12
  rus: 2025-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204837/kaz/12.11.2025
  rus: https://zan.gov.kz/client/#!/doc/204837/rus/12.11.2025
caused_by:
  code: '217082'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 12 ноября 2025 года № 285/36
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 25 декабря 2024 года № 208/25 «Об Экибастузском городском бюджете на 2025 - 2027 годы»
    kaz: Екібастұз қалалық мәслихатының 2024 жылғы 25 желтоқсандағы № 208/25 «2025 - 2027 жылдарға арналған Екібастұз қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217082/rus
