act_code: '24443'
requisite: Решение Павлодарского областного Маслихата от 30 мая 2005 года № 50/12. Зарегистрировано Департаментом юстиции Павлодарской области 20 июня 2005 года за № 3035
title:
  rus: О плане мероприятий на 2005 год по реализации в Павлодарской области программы по противодействию эпидемии СПИДа в Республике Казахстан на 2001 - 2005 годы
  kaz: Қазақстан Республикасында ЖҚТБ-ның iндетiне Қарсы iс-әрекет жөнiндегi 2001 - 2005 жылдарға арналған Бағдарламаны Павлодар облысында iске асыру жөнiндегi 2005 жылға арналған iс-шаралар жоспары туралы
form: РЕШ
type_codes:
- МРП
- ПРОГ
- РЕШ
approved_on: 2005-05-30
approved_by:
- '164000000002'
version_date:
  kaz: 2009-03-18
  rus: 2009-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/24443/kaz/18.03.2009
  rus: https://zan.gov.kz/client/#!/doc/24443/rus/18.03.2009
