act_code: '68508'
requisite: Решение маслихата Майского района Павлодарской области от 24 октября 2012 года № 5/8. Зарегистрировано Департаментом юстиции Павлодарской области 12 ноября 2012 года № 3252. Утратило силу решением маслихата Майского района Павлодарской области от 21 января 2014 года № 1/28
title:
  rus: О социальной помощи по приобретению топлива
  kaz: Отын сатып алу бойынша әлеуметтік көмек туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-10-24
approved_by:
- '164010000002'
version_date:
  kaz: 2012-10-24
  rus: 2012-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/68508/kaz/24.10.2012
  rus: https://zan.gov.kz/client/#!/doc/68508/rus/24.10.2012
