act_code: '9729'
requisite: Решение Маслихата Павлодарской области от 20 июля 2001 года (ХІІІ сессия, ІІ созыв). Зарегистрировано Управлением юстиции Павлодарской области от 13 августа 2001 года за № 852
title:
  rus: Об изменении границ населенных пунктов некоторых сельских округов Иртышского района
  kaz: Ертіс ауданындағы кейбір селолық округтері елді мекендерінің шекарасын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-07-19
approved_by:
- '164000000002'
version_date:
  kaz: 2001-07-19
  rus: 2001-07-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/9729/kaz/19.07.2001
  rus: https://zan.gov.kz/client/#!/doc/9729/rus/19.07.2001
