act_code: '41472'
requisite: Решение маслихата Железинского района Павлодарской области от 22 августа 2008 года № 96-4/9. Зарегистрировано Управлением юстиции Железинского района Павлодарской области 05 сентября 2016 года № 12-6-59
title:
  rus: Очередная (9-сессия, 4-созыва ) Об утверждении Инструкции по присвоению звания «Почетный гражданин Железинского района»
  kaz: (4-шақырылымның кезекті 9-сессиясы) «Железинка ауданының Құрметті азаматы туралы» атағын беру бойынша Нұсқауды бекіту туралы
form: РЕШ
type_codes:
- ИНСТ
- РЕШ
approved_on: 2008-08-22
approved_by:
- '164006000002'
version_date:
  kaz: 2008-08-22
  rus: 2008-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/41472/kaz/22.08.2008
  rus: https://zan.gov.kz/client/#!/doc/41472/rus/22.08.2008
