act_code: '204848'
requisite: Решение Аксуского городского маслихата Павлодарской области от 25 декабря 2024 года № 172/29
title:
  rus: О бюджете города Аксу на 2025-2027 годы
  kaz: 2025 - 2027 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '164004000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/204848/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204848/rus/25.12.2024
