act_code: '176144'
requisite: Решение Иртышского районного маслихата Павлодарской области от 27 декабря 2022 года № 108-27-7
title:
  rus: О бюджете сёл и сельских округов Иртышского района на 2023 – 2025 годы
  kaz: 2023 – 2025 жылдарға арналған Ертіс ауданының ауылдар және ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '164007000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/176144/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/176144/rus/27.12.2022
