act_code: '36018'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 22 октября 2007 года № 30/2. Зарегистрировано управлением юстиции города Павлодара Павлодарской области 23 ноября 2007 года за № 12-1-96. Утратило силу решением маслихата города Павлодара Павлодарской области от 2 июля 2008 года № 164/8
title:
  rus: О дополнительных категориях граждан, имеющих право на безвозмездное получение в собственность занимаемых ими жилых помещений государственного жилищного фонда
  kaz: Мемлекеттік тұрғын үй қорының өздері тұратын тұрғын үй-жайларын меншікке өтеусіз алуға құқығы бар азаматтардың қосымша санаттары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-10-22
approved_by:
- '164002000002'
version_date:
  kaz: 2008-04-04
  rus: 2008-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/36018/kaz/04.04.2008
  rus: https://zan.gov.kz/client/#!/doc/36018/rus/04.04.2008
caused_by:
  code: '39300'
  requisite: Решение маслихата города Павлодара Павлодарской области от 4 апреля 2008 года № 121/5. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 25 апреля 2008 года за № 12-1-109. Утратило силу решением маслихата города Павлодара Павлодарской области от 2 июля 2008 года № 164/8
  title:
    rus: О внесении дополнения и изменения в решение Павлодарского городского маслихата от 22 октября 2007 года № 30/2 "О дополнительных категориях граждан, имеющих право на безвозмездное получение в собственность занимаемых ими жилых помещений государственного жилого фонда"
    kaz: Павлодар қалалық мәслихатының 2007 жылғы 22 қазандағы "Мемлекеттік тұрғын үй қорының өздері тұратын тұрғын үй-жайларын меншікке өтеусіз алуға құқығы бар азаматтардың қосымша санаттары туралы" № 30/2 шешіміне толықтыру мен өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/39300/rus
