act_code: '92626'
requisite: Решение акима Байзаковского сельского округа Иртышского района Павлодарской области от 07 августа 2015 года № 3
title:
  rus: Об отмене ранее принятого решения акима Байзаковского сельского округа № 2 от 26 мая  2015 года «Об установлении карантина на улице Карла Маркса в селе Исы Байзакова Иртышского района»
  kaz: Бұрын, 2015 жылғы 26 мамырда қабылданған, Байзақов ауылдық округінің «Ертіс ауданы Байзақов ауылдық округінің Иса Байзақов ауылының Карл Маркс  көшесіне карантин орнату туралы» № 2 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-08-07
approved_by:
- '164007004001'
version_date:
  kaz: 2015-08-07
  rus: 2015-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/92626/kaz/07.08.2015
  rus: https://zan.gov.kz/client/#!/doc/92626/rus/07.08.2015
