act_code: '62677'
requisite: Решение маслихата Щербактинского района Павлодарской области от 20 декабря 2011 года № 220/45. Зарегистрировано Департаментом юстиции Павлодарской области 10 января 2012 года № 12-13-136. Утратило силу решением маслихата Щербактинского района Павлодарской области от 30 января 2013 года № 62/19
title:
  rus: О бюджете Щербактинского района на 2012 - 2014 годы
  kaz: 2012 - 2014 жылдарға арналған Шарбақты ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164012000002'
version_date:
  kaz: 2012-04-16
  rus: 2012-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/62677/kaz/16.04.2012
  rus: https://zan.gov.kz/client/#!/doc/62677/rus/16.04.2012
caused_by:
  code: '65109'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 16 апреля 2012 года № 13/5. Зарегистрировано Департаментом юстиции Павлодарской области 25 апреля 2012 года № 12-13-146. Утратило силу решением маслихата Щербактинского района Павлодарской области от 30 января 2013 года № 62/19
  title:
    rus: О внесении изменений и дополнений в решение Щербактинского районного маслихата от 20 декабря 2011 года № 220/45 "О бюджете Щербактинского района на 2012 - 2014 годы"
    kaz: Шарбақты аудандық мәслихатының 2011 жылғы 20 желтоқсандағы № 220/45 "Шарбақты ауданының 2012 - 2014 жылдарға арналған бюджеті туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/65109/rus
