act_code: '118430'
requisite: Решение маслихата Актогайского района Павлодарской области от 12 января 2018 года № 151/27. Зарегистрировано Департаментом юстиции Павлодарской области 23 января 2018 года № 5828
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Актогайскому району на 2018 год
  kaz: Ақтоғай ауданы бойынша 2018 жылға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2018-01-12
approved_by:
- '164003000002'
version_date:
  kaz: 2018-01-12
  rus: 2018-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/118430/kaz/12.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118430/rus/12.01.2018
