act_code: '171110'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 22 августа 2022 года № 135/17. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 сентября 2022 года № 29357
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Баянаульскому району
  kaz: Баянауыл ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-22
approved_by:
- '164005000002'
version_date:
  kaz: 2022-08-22
  rus: 2022-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/171110/kaz/22.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171110/rus/22.08.2022
