act_code: '10510'
requisite: Решение Павлодарского областного Маслихата от 13 марта 2001 года (Х сессия, ІІ созыв). Зарегистрировано Управлением юстиции Павлодарской области 12 апреля 2001 года за № 622
title:
  rus: «О программе комплексного развития Майского района на 2001 – 2003 годы и плане мероприятий по ее реализации на 2001 год»
  kaz: Май ауданының кешенді дамытудың 2001 – 2003 жылдарға арналған бағдарлама мен оны 2001 жылы жүзеге асыру жөніндегі шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-13
approved_by:
- '164000000002'
version_date:
  kaz: 2001-03-13
  rus: 2001-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/10510/kaz/13.03.2001
  rus: https://zan.gov.kz/client/#!/doc/10510/rus/13.03.2001
