act_code: '137874'
requisite: Решение маслихата Баянаульского района Павлодарской области от 30 декабря 2019 года № 304/54. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2020 года № 6702
title:
  rus: О бюджетах сельских округов и поселка Майкаин Баянаульского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Баянауыл ауданының ауылдық округтері және Майқайың кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '164005000002'
version_date:
  kaz: 2020-12-21
  rus: 2020-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/137874/kaz/21.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137874/rus/21.12.2020
caused_by:
  code: '150164'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 21 декабря 2020 года № 366/64. Зарегистрировано Департаментом юстиции Павлодарской области 22 декабря 2020 года № 7103
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 30 декабря 2019 года № 304/54 «О бюджетах сельских округов и поселка Майкаин Баянаульского района на 2020 - 2022 годы»
    kaz: Баянауыл аудандық мәслихатының 2019 жылғы 30 желтоқсандағы «2020 - 2022 жылдарға арналған Баянауыл ауданының ауылдық округтері және Майқайың кентінің бюджеттері туралы» № 304/54 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/150164/rus
