act_code: '162675'
requisite: Решение Аксуского городского маслихата Павлодарской области от 29 декабря 2021 года № 111/15
title:
  rus: О бюджете сельских округов города Аксу на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Ақсу қаласы ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164004000002'
version_date:
  kaz: 2022-11-30
  rus: 2022-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/162675/kaz/30.11.2022
  rus: https://zan.gov.kz/client/#!/doc/162675/rus/30.11.2022
caused_by:
  code: '174506'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 30 ноября 2022 года № 201/30
  title:
    rus: О внесении изменений и дополнения в решение Аксуского городского маслихата от 29 декабря 2021 года № 111/15 «О бюджете сельских округов города Аксу на 2022 - 2024 годы»
    kaz: Ақсу қалалық мәслихатының 2021 жылғы 29 желтоқсандағы «2022 - 2024 жылдарға арналған Ақсу қаласының ауылдық округтерінің бюджеті туралы» № 111/15 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174506/rus
