act_code: '49569'
requisite: Павлодар облысы Май аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 4/21 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2009 жылғы 25 желтоқсанда № 12-10-90 тіркелген
title:
  rus: 2010 - 2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010 - 2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '164010000002'
version_date:
  kaz: 2010-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/49569/kaz/12.02.2010
caused_by:
  code: '50762'
  requisite: Павлодар облысы Май аудандық мәслихатының 2010 жылғы 12 ақпандағы № 3/24 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2010 жылғы 18 ақпанда № 12-10-92 тіркелген
  title:
    rus: Аудандық мәслихатының (IV сайланған XXI кезекті сессия) 2009 жылғы 25 желтоқсандағы "2010 - 2012 жылдарға арналған аудандық бюджет туралы" № 4/21 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихатының (IV сайланған XXI кезекті сессия) 2009 жылғы 25 желтоқсандағы "2010 - 2012 жылдарға арналған аудандық бюджет туралы" № 4/21 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50762/rus
