act_code: '96466'
requisite: Решение маслихата Павлодарской области от 10 декабря 2015 года № 394/46. Зарегистрировано Департаментом юстиции Павлордарской области 22 декабря 2015 года № 4852
title:
  rus: Об областном бюджете на 2016 - 2018 годы
  kaz: 2016 - 2018 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-10
approved_by:
- '164000000002'
version_date:
  kaz: 2016-06-22
  rus: 2016-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/96466/kaz/22.06.2016
  rus: https://zan.gov.kz/client/#!/doc/96466/rus/22.06.2016
caused_by:
  code: '103753'
  requisite: Решение маслихата Павлодарской области от 22 июня 2016 года № 30/4. Зарегистрировано Департаментом юстиции Павлодарской области 29 июня 2016 года № 5150
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата (XLVI сессия, V созыв) от 10 декабря 2015 года № 394/46 «Об областном бюджете на 2016 - 2018 годы»
    kaz: Облыстық мәслихаттың (V сайланған ХLVІ сессиясы) 2015 жылғы 10 желтоқсандағы «2016 - 2018 жылдарға арналған облыстық бюджет туралы» № 394/46 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/103753/rus
