act_code: '117544'
requisite: Решение маслихата Актогайского района Павлодарской области от 28 декабря 2017 года № 144/26. Зарегистрировано Департаментом юстиции Павлодарской области 11 января 2018 года № 5807
title:
  rus: О бюджете Актогайского сельского округа на 2018 - 2020 годы
  kaz: Ақтоғай ауылдық округінің 2018 - 2020 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-28
approved_by:
- '164003000002'
version_date:
  kaz: 2018-12-21
  rus: 2018-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/117544/kaz/21.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117544/rus/21.12.2018
caused_by:
  code: '127745'
  requisite: Решение маслихата Актогайского района Павлодарской области от 21 декабря 2018 года № 216/41. Зарегистрировано Департаментом юстиции Павлодарской области 26 декабря 2018 года № 6189
  title:
    rus: О внесении изменений и дополнения в решение Актогайского районного маслихата от 28 декабря 2017 года № 144/26 «О бюджете Актогайского сельского округа на 2018-2020 годы»
    kaz: Ақтоғай аудандық мәслихатының 2017 жылғы 28 желтоқсандағы «Ақтоғай ауылдық округінің 2018 - 2020 жылдарға арналған бюджеті туралы» № 144/26 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127745/rus
