act_code: '137776'
requisite: Решение маслихата Щербактинского района Павлодарской области от 27 декабря 2019 года № 227/68. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2019 года № 6693
title:
  rus: О бюджете сельских округов Щербактинского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Шарбақты ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '164012000002'
version_date:
  kaz: 2020-03-19
  rus: 2020-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/137776/kaz/19.03.2020
  rus: https://zan.gov.kz/client/#!/doc/137776/rus/19.03.2020
caused_by:
  code: '140586'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 19 марта 2020 года № 240/72. Зарегистрировано Департаментом юстиции Павлодарской области 26 марта 2020 года № 6768
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 27 декабря  2019 года № 227/68 «О бюджете сельских округов Щербактинского района на 2020 – 2022 годы»
    kaz: Шарбақты аудандық мәслихатының 2019 жылғы 27 желтоқсандағы «2020 – 2022 жылдарға арналған Шарбақты ауданының ауылдық округтерінің бюджеті туралы» № 227/68 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140586/rus
