act_code: '194812'
requisite: Решение Майского районного маслихата Павлодарской области от 26 марта 2024 года № 3/12. Зарегистрировано в Департаменте юстиции Павлодарской области 27 марта 2024 года № 7518-14
title:
  rus: Об утверждении ставок туристского взноса для иностранцев по Майскому району на 2024 год
  kaz: 2024 жылға арналған Май ауданы бойынша шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-26
approved_by:
- '164010000002'
version_date:
  kaz: 2024-03-26
  rus: 2024-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/194812/kaz/26.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194812/rus/26.03.2024
