act_code: '162472'
requisite: Решение Иртышского районного маслихата Павлодарской области от 24 декабря 2021 года № 56-12-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26178
title:
  rus: Об Иртышском районном бюджете на 2022 – 2024 годы
  kaz: 2022 – 2024 жылдарға арналған Ертіс аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164007000002'
version_date:
  kaz: 2022-04-15
  rus: 2022-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/162472/kaz/15.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162472/rus/15.04.2022
caused_by:
  code: '166642'
  requisite: Решение Иртышского районного маслихата Павлодарской области от 15 апреля 2022 года № 63-16-7
  title:
    rus: О внесении изменений в решение Иртышского районного маслихата от 24 декабря 2021 года № 56-12-7 «Об Иртышском районном бюджете на 2022 – 2024 годы»
    kaz: Ертіс аудандық мәслихатының 2021 жылғы 24 желтоқсандағы «2022 – 2024 жылдарға арналған Ертіс аудандық бюджеті туралы» № 56-12-7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166642/rus
