act_code: '118733'
requisite: Решение маслихата Железинского района Павлодарской области от 6 февраля 2018 года № 194/6. Зарегистрировано Департаментом юстиции Павлодарской области 13 февраля 2018 года № 5853
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Железинского района в 2018 году
  kaz: 2018 жылға арналған Железин ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-06
approved_by:
- '164006000002'
version_date:
  kaz: 2018-02-06
  rus: 2018-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/118733/kaz/06.02.2018
  rus: https://zan.gov.kz/client/#!/doc/118733/rus/06.02.2018
