act_code: '205018'
requisite: Решение маслихата района Аққулы Павлодарской области от 26 декабря 2024 года № 123/29
title:
  rus: О бюджетах сельских округов района Аққулы на 2025-2027 годы
  kaz: Аққулы ауданының ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '164009000002'
version_date:
  kaz: 2025-06-26
  rus: 2025-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/205018/kaz/26.06.2025
  rus: https://zan.gov.kz/client/#!/doc/205018/rus/26.06.2025
caused_by:
  code: '211826'
  requisite: Решение маслихата района Аққулы Павлодарской области от 26 июня 2025 года № 149/33
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 26 декабря 2024 года № 123/29 «О бюджетах сельских округов района Аққулы на 2025-2027 годы»
    kaz: Аққулы аудандық мәслихатының 2024 жылғы 26 желтоқсандағы «Аққулы ауданының ауылдық округтерінің 2025-2027 жылдарға арналған бюджеттері туралы» № 123/29 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211826/rus
