act_code: '53737'
requisite: Решение маслихата Иртышского района Павлодарской области от 16 июня 2010 года № 173-27-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 27 июля 2010 года № 12-7-105. Утратило силу решением маслихата Иртышского района Павлодарской области от 30 октября 2013 года № 109-23-5
title:
  rus: Об утверждении Правил предоставления жилищной помощи малообеспеченным гражданам на содержание жилья и оплату коммунальных услуг по Иртышскому району
  kaz: Ертіс ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметін төлеуге тұрғын үй көмегін ұсыну ережелерін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-16
approved_by:
- '164007000002'
version_date:
  kaz: 2013-07-17
  rus: 2013-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/53737/kaz/17.07.2013
  rus: https://zan.gov.kz/client/#!/doc/53737/rus/17.07.2013
caused_by:
  code: '74039'
  requisite: Решение маслихата Иртышского района Павлодарской области от 17 июля 2013 года № 87-20-5. Зарегистрировано Департаментом юстиции Павлодарской области 20 августа 2013 года № 3593. Утратило силу решением маслихата Иртышского района Павлодарской области от 30 октября 2013 года № 109-23-5
  title:
    rus: О внесении изменений и дополнений в решение Иртышского районного маслихата (XXVII сессия, IV созыв) от 16 июня 2010 года № 173-27-4 "Об утверждении Правил жилищной помощи малообеспеченным гражданам Иртышского района на содержание жилья и оплаты коммунальных услуг"
    kaz: Ертіс аудандық мәслихатының (IV сайланған, XXVII сессиясы) 2010 жылдың 16 маусымдағы "Ертіс ауданы бойынша аз қамтамасыз етілген азаматтарға тұрғын үйді ұстауға және коммуналдық қызметін төлеуге тұрғын үй көмегін ұсыну ережелерін бекіту туралы" № 173-27-4 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/74039/rus
