act_code: '150536'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 23 декабря 2020 года № 484/63. Зарегистрировано Департаментом юстиции Павлодарской области 25 декабря 2020 года № 7110
title:
  rus: Об Экибастузском городском бюджете на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '164013000002'
version_date:
  kaz: 2021-06-30
  rus: 2021-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/150536/kaz/30.06.2021
  rus: https://zan.gov.kz/client/#!/doc/150536/rus/30.06.2021
caused_by:
  code: '157169'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 30 июня 2021 года № 41/6. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 июля 2021 года № 23663
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 23 декабря 2020 года № 484/63 «Об Экибастузском городском бюджете на 2021 - 2023 годы»
    kaz: Екібастұз қалалық мәслихатының 2020 жылғы 23 желтоқсандағы № 484/63 «2021 - 2023 жылдарға арналған Екібастұз қалалық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/157169/rus
