act_code: '143691'
requisite: Решение акима Шакатского сельского округа Павлодарского района Павлодарской области от 2 июня 2020 года № 1-03-04. Зарегистрировано Департаментом юстиции Павлодарской области 8 июня 2020 года № 6842
title:
  rus: О переименовании улицы села Шакат Шакатского сельского округа Павлодарского района
  kaz: Павлодар ауданы Шақат ауылдық округі Шақат ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-02
approved_by:
- '164014012002'
version_date:
  kaz: 2020-06-02
  rus: 2020-06-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/143691/kaz/02.06.2020
  rus: https://zan.gov.kz/client/#!/doc/143691/rus/02.06.2020
