act_code: '3188'
requisite: Решение Павлодарского областного маслихата от 23 апреля 1999 года XXV сессия I созыва. Зарегистрировано Управлением юстиции Павлодарской области 3 июня 1999 года за № 164
title:
  rus: Об исполнении областного бюджета за 1998 год
  kaz: 1998 жылғы облыстық бюджеттің орындалуы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-22
approved_by:
- '164000000002'
version_date:
  kaz: 1999-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3188/kaz/22.04.1999
