act_code: '135785'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 31 октября 2019 года № 5/49. Зарегистрировано Департаментом юстиции Павлодарской области 5 ноября 2019 года № 6592. Утратило силу решением маслихата района Тереңкөл от 10 октября 2023 года № 3/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей сел для участия в сходе местного сообщества на территории Байконысского сельского округа района Тереңкөл
  kaz: Тереңкөл ауданы Байқоныс ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің тәртібін бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің санын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-31
approved_by:
- '164008000002'
version_date:
  kaz: 2019-10-31
  rus: 2019-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/135785/kaz/31.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135785/rus/31.10.2019
