act_code: '17701'
requisite: Решение маслихата Павлодарской области от 5 сентября 2003 года № 147/28. Зарегистрировано Управлением юстиции Павлодарской области 22 сентября 2003 года за № 2051
title:
  rus: О плане мероприятий на 2003 год по реализации областной программы "Охрана здоровья матери и ребенка на 2002 - 2005 годы"
  kaz: 2002 - 2005 жылдарға арналған ана мен баланың денсаулығын қорғау" облыстық бағдарламаны iске асыру жөнiндегi 2003 жылға арналған iс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-04
approved_by:
- '164000000002'
version_date:
  kaz: 2003-09-04
  rus: 2003-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/17701/kaz/04.09.2003
  rus: https://zan.gov.kz/client/#!/doc/17701/rus/04.09.2003
