act_code: '36538'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2007 жылғы 24 желтоқсандағы № 20/4 шешімі. Павлодар облысының Баянауыл ауданының Әділет басқармасында 2007 жылғы 26 желтоқсанда № 12-5-48 тіркелді
title:
  rus: Баянауыл ауданының 2008 жылға арналған бюджеті туралы
  kaz: Баянауыл ауданының 2008 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '164005000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36538/kaz/24.12.2007
