act_code: '230293'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 8 сентября 2026 года № 502/54
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Баянаульского районного маслихата»
  kaz: «Баянауыл аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-09-08
approved_by:
- '164005000002'
version_date:
  kaz: 2026-09-08
  rus: 2026-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/230293/kaz/08.09.2026
  rus: https://zan.gov.kz/client/#!/doc/230293/rus/08.09.2026
