act_code: '86887'
requisite: Решение акима Евгеньевского сельского округа города Аксу Павлодарской области от 20 февраля 2015 года № 1-09/03. Зарегистрировано Департаментом юстиции Павлодарской области 25 февраля 2015 года № 4316. Утратило силу решением исполняющего обязанности акима Евгеньевского сельского округа города Аксу Павлодарской области от 3 ноября 2015 года № 1-09/05
title:
  rus: Об установлении  ограничительных мероприятий
  kaz: Шектеу іс-шараларын  белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-20
approved_by:
- '164004008001'
version_date:
  kaz: 2015-02-20
  rus: 2015-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/86887/kaz/20.02.2015
  rus: https://zan.gov.kz/client/#!/doc/86887/rus/20.02.2015
