act_code: '162992'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 24 декабря 2021 года № 79/11
title:
  rus: О бюджетах сельских округов и поселка Майкаин Баянаульского района на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Баянауыл ауданының ауылдық округтері және Майқайың кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164005000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162992/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162992/rus/24.12.2021
