act_code: '162992'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 24 декабря 2021 года № 79/11
title:
  rus: О бюджетах сельских округов и поселка Майкаин Баянаульского района на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Баянауыл ауданының ауылдық округтері және Майқайың кентінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164005000002'
version_date:
  kaz: 2022-10-18
  rus: 2022-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/162992/kaz/18.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162992/rus/18.10.2022
caused_by:
  code: '173653'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 18 октября 2022 года № 148/20
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 24 декабря 2021 года № 79/11 «О бюджетах сельских округов и поселка Майкаин Баянаульского района на 2022-2024 годы»
    kaz: Баянауыл аудандық мәслихатының 2021 жылғы 24 желтоқсандағы «2022-2024 жылдарға арналған Баянауыл ауданының ауылдық округтері және Майқайың кентінің бюджеттері туралы» № 79/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173653/rus
