act_code: '168278'
requisite: Решение Иртышского районного маслихата Павлодарской области от 26 мая 2022 года № 72-18-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 мая 2022 года № 28289
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Иртышском районе
  kaz: Ертіс ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-05-26
approved_by:
- '164007000002'
version_date:
  kaz: 2022-11-23
  rus: 2022-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/168278/kaz/23.11.2022
  rus: https://zan.gov.kz/client/#!/doc/168278/rus/23.11.2022
caused_by:
  code: '174105'
  requisite: Решение Иртышского районного маслихата Павлодарской области от 23 ноября 2022 года № 97-24-7. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 ноября 2022 года № 30691
  title:
    rus: О внесении изменений в решение Иртышского районного маслихата от 26 мая 2022 года № 72-18-7 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Иртышском районе»
    kaz: Ертіс аудандық мәслихатының 2022 жылғы 26 мамырдағы № 72-18-7 «Ертіс ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174105/rus
