act_code: '9656'
requisite: Решение Акима Павлодарской области от 24 апреля 2001 года № 101. Зарегистрировано Управлением юстиции Павлодарской области 4 мая 2001 года за № 662. Утратило силу решением акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: О правилах льготного проезда отдельных категорий граждан на территории области
  kaz: Азаматтардың жеке санаттарының облыс аумағында женілдікпен жүру ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2001-04-23
approved_by:
- '164000000003'
version_date:
  kaz: 2001-04-23
  rus: 2001-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/9656/kaz/23.04.2001
  rus: https://zan.gov.kz/client/#!/doc/9656/rus/23.04.2001
