act_code: '44579'
requisite: Решение маслихата города Аксу Павлодарской области от 9 февраля 2009 года № 106/14. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 9 марта 2009 года за № 106. Утратило силу решением маслихата города Аксу Павлодарской области от 10 января 2010 года № 1-07/4
title:
  rus: О предоставлении права льготного проезда некоторым категориям обучающихся и воспитанников учреждений образования города Аксу на городском общественном транспорте (кроме такси) на 2009 год
  kaz: Ақсу қаласының білім беру мекемелерінде оқитын және тәрбиеленетін жекелеген санаттағы балаларға 2009 жылы қалалық қоғамдық қөлікте (таксиден басқа) жеңілдікпен жол жүру құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-09
approved_by:
- '164004000002'
version_date:
  kaz: 2009-02-09
  rus: 2009-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/44579/kaz/09.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44579/rus/09.02.2009
