act_code: '49716'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2009 жылғы 28 желтоқсандағы № 137/20 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2009 жылғы 31 желтоқсанда № 12-5-70 тіркелген
title:
  rus: Баянауыл ауданының 2010 - 2012 жылдарға арналған бюджеті туралы
  kaz: Баянауыл ауданының 2010 - 2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '164005000002'
version_date:
  kaz: 2010-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/49716/kaz/08.02.2010
caused_by:
  code: '50664'
  requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2010 жылғы 8 ақпандағы № 151/22 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2010 жылғы 12 ақпанда № 12-5-72 тіркелген
  title:
    rus: Аудандық мәслихаттың (IV сайланған кезекті XX сессия) 2009 жылғы 28 желтоқсандағы "Баянауыл ауданының 2010 - 2012 жылдарға арналған бюджеті туралы" № 137/20 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың (IV сайланған кезекті XX сессия) 2009 жылғы 28 желтоқсандағы "Баянауыл ауданының 2010 - 2012 жылдарға арналған бюджеті туралы" № 137/20 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50664/rus
