act_code: '3132'
requisite: Павлодар облыстық мәслихаттың 1999 жылғы 23 сәуірдегі XXV сессия, I шақырылым шешімі. Павлодар облысының Әділет басқармасында 1999 жылғы 3 маусымда № 167 тіркелді. Күші жойылды - Павлодар облыстық мәслихаттың 1999 жылғы 13 желтоқсандағы II сайланған, II сессиясының шешімімен
title:
  rus: Облысты басқару нобайы туралы
  kaz: Облысты басқару нобайы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-22
approved_by:
- '164000000002'
version_date:
  kaz: 1999-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3132/kaz/22.04.1999
