act_code: '36831'
requisite: Павлодар облысы Май аудандық мәслихатының 2007 жылғы 24 желтоқсандағы № 3/4 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2007 жылғы 27 желтоқсанда № 12-10-55 тіркелген
title:
  rus: 2008 жылға арналған аудандық бюджетті бекіту туралы
  kaz: 2008 жылға арналған аудандық бюджетті бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '164010000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36831/kaz/24.12.2007
