act_code: '14559'
requisite: Решение Павлодарского областного маслихата (XX сессия II созыв) от 24 июня 2002 года № 43/20. Зарегистрировано Управлением юстиции Павлодарской области 9 июля 2002 года за № 1317. Утратило силу решением маслихата Павлодарской области от 24 июля 2009 года № 222/16
title:
  rus: О повышении на 25 процентов окладов и тарифных ставок специалистов сфер здравоохранения, социального обеспечения, образования, культуры и спорта, работающих в сельской местности и не являющихся государственными служащими
  kaz: Ауылдық жерде жұмыс iстейтiн және мемлекеттiк қызметшiлер болып табылмайтын денсаулық сақтау, әлеуметтiк қамсыздандыру, бiлiм беру, мәдениет және спорт салалары мамандарының айлықақылары мен тарифтiк мөлшерлемелерiн 25 пайызға көтеру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-06-23
approved_by:
- '164000000002'
version_date:
  kaz: 2002-06-23
  rus: 2002-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/14559/kaz/23.06.2002
  rus: https://zan.gov.kz/client/#!/doc/14559/rus/23.06.2002
