act_code: '152992'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 12 февраля 2021 года № 2/16. Зарегистрировано Департаментом юстиции Павлодарской области 19 февраля 2021 года № 7214
title:
  rus: О предоставлении мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов села, сельских округов, прибывшим для работы и проживания в сельские населенные пункты Павлодарского района на 2021 год
  kaz: 2021 жылға арналған Павлодар ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауыл, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне әлеуметтік қолдау шараларын көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-02-12
approved_by:
- '164014000002'
version_date:
  kaz: 2021-02-12
  rus: 2021-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/152992/kaz/12.02.2021
  rus: https://zan.gov.kz/client/#!/doc/152992/rus/12.02.2021
