act_code: '132877'
requisite: Решение маслихата Павлодарской области от 14 июня 2019 года № 352/31. Зарегистрировано Департаментом юстиции Павлодарской области 26 июня 2019 года № 6450. Утратило силу решением Павлодарского областного маслихата от 30 апреля 2025 года № 193/21 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил подготовки и проведения отопительного сезона в Павлодарской области
  kaz: Павлодар облысында жылу беру маусымына дайындық және оны өткізу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2019-06-14
approved_by:
- '164000000002'
version_date:
  kaz: 2019-06-14
  rus: 2019-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/132877/kaz/14.06.2019
  rus: https://zan.gov.kz/client/#!/doc/132877/rus/14.06.2019
