act_code: '161727'
requisite: Решение Павлодарского областного маслихата от 10 декабря 2021 года № 104/9. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 декабря 2021 года № 25797
title:
  rus: Об областном бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '164000000002'
version_date:
  kaz: 2021-12-10
  rus: 2021-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/161727/kaz/10.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161727/rus/10.12.2021
