act_code: '161727'
requisite: Решение Павлодарского областного маслихата от 10 декабря 2021 года № 104/9. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 декабря 2021 года № 25797
title:
  rus: Об областном бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '164000000002'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/161727/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/161727/rus/14.04.2022
caused_by:
  code: '166999'
  requisite: Решение Павлодарского областного маслихата от 14 апреля 2022 года № 138/12. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 апреля 2022 года № 27769
  title:
    rus: О внесении изменений в решение Павлодарского областного маслихата от 10 декабря 2021 года № 104/9 «Об областном бюджете на 2022-2024 годы»
    kaz: Павлодар облыстық мәслихатының 2021 жылғы 10 желтоқсандағы «2022-2024 жылдарға арналған облыстық бюджет туралы» № 104/9 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166999/rus
