act_code: '224315'
requisite: Решение акима Кызылтауского сельского округа Баянаульского района Павлодарской области от 10 апреля 2026 года № 1-21-05
title:
  rus: Об установлении публичного сервитута товариществу с ограниченной ответственностью «Kazmine Limited Liability Partnership»на территории Кызылтауского сельского округа Баянаульского района
  kaz: «Kazmine Limited Liability Partnership» жауапкершілігі шектеулі серіктестігіне Баянауыл ауданы Қызылтау ауылдық округі аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-04-10
approved_by:
- '164005010002'
version_date:
  kaz: 2026-04-10
  rus: 2026-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/224315/kaz/10.04.2026
  rus: https://zan.gov.kz/client/#!/doc/224315/rus/10.04.2026
