act_code: '189677'
requisite: Решение Аксуского городского маслихата Павлодарской области от 5 декабря 2023 года № 76/10. Отменено решением Аксуского городского маслихата Павлодарской области от 25 сентября 2024 года № 152/24 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по городу Аксу на 2023– 2024 годы
  kaz: 2023 – 2024 жылдарға арналған Ақсу қаласы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2023-12-05
approved_by:
- '164004000002'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/189677/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189677/rus/05.12.2023
