act_code: '45278'
requisite: Решение маслихата Актогайского района Павлодарской области от 27 марта 2009 года № 77/12. Зарегистрировано Управлением юстиции Актогайского района Павлодарской области 14 апреля 2009 года за № 12-4-59. Утратило силу решением маслихата Актогайского района Павлодарской области от 21 ноября 2013 года № 93/23
title:
  rus: О ставках земельного налога
  kaz: Жер салығының ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-27
approved_by:
- '164003000002'
version_date:
  kaz: 2009-03-27
  rus: 2009-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/45278/kaz/27.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45278/rus/27.03.2009
