act_code: '84775'
requisite: Решение маслихата Железинского района Павлодарской области от 20 ноября 2014 года № 251-5/31. Зарегистрировано Департаментом юстиции Павлодарской области 03 декабря 2014 года № 4204. Утратило силу решением Железинского районного маслихата Павлодарской области от 24 сентября 2021 года № 53/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Железинском районе
  kaz: Железин ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-20
approved_by:
- '164006000002'
version_date:
  kaz: 2014-11-20
  rus: 2014-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/84775/kaz/20.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84775/rus/20.11.2014
