act_code: '61577'
requisite: Решение от 17.11.2011 №6, Акимат Майского района
title:
  rus: Май ауданының аумағында сайлау учаскелерін құру туралы
  kaz: Май ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-17
approved_by:
- '164010000001'
version_date:
  kaz: 2011-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/61577/kaz/17.11.2011
