act_code: '1595'
requisite: Решение Акима Павлодарской области от 21 августа 1998 года № 270. Зарегистрировано Управлением юстиции Павлодарской области 02 сентября 1998 года за № 72. Утратило силу -  решением акима Павлодарской области от 19 сентября 2000 года № 222
title:
  rus: О комплексной программе профилактики правонарушений среди несовершеннолетних в области на 1998 – 2000 годы
  kaz: 1998 – 2000 жылдарға арналған облыста кәмелетке толмағандардың арасындағы құқық бұзушылықтардың алдын алудың Кешенді бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-08-20
approved_by:
- '164000000003'
version_date:
  kaz: 1998-08-20
  rus: 1998-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/1595/kaz/20.08.1998
  rus: https://zan.gov.kz/client/#!/doc/1595/rus/20.08.1998
