act_code: '56359'
requisite: Павлодар облысы Лебяжі аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 1/25 шешімі. Павлодар облысы Лебяжі ауданының Әділет басқармасында 2010 жылғы 29 желтоқсанда № 12-9-122 тіркелген
title:
  rus: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
  kaz: 2011 - 2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '164009000002'
version_date:
  kaz: 2013-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/56359/kaz/11.10.2013
