act_code: '193566'
requisite: Решение Майского районного маслихата Павлодарской области от 22 февраля 2024 года № 11/11
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества на территории Малайсаринского сельского округа Майского района
  kaz: Май ауданы Малайсары ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-02-22
approved_by:
- '164010000002'
version_date:
  kaz: 2024-02-22
  rus: 2024-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/193566/kaz/22.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193566/rus/22.02.2024
