act_code: '162676'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 29 декабря 2021 года № 19/93
title:
  rus: О бюджете Кенесского сельского округа на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Кеңес ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164014000002'
version_date:
  kaz: 2022-04-14
  rus: 2022-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/162676/kaz/14.04.2022
  rus: https://zan.gov.kz/client/#!/doc/162676/rus/14.04.2022
caused_by:
  code: '166549'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 14 апреля 2022 года № 23/128
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 29 декабря 2021 года № 19/93 «О бюджете Кенесского сельского округа на 2022-2024 годы»
    kaz: Павлодар аудандық мәслихатының 2021 жылғы 29 желтоқсандағы «2022-2024 жылдарға арналған Кеңес ауылдық округінің бюджеті туралы» № 19/93 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166549/rus
