act_code: '53220'
requisite: Решение акима сельского округа имени Мамаита Омарова города Аксу Павлодарской области от 14 июня 2010 года № 1-03. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 21 июня 2010 года № 12-2-142
title:
  rus: О переименовании улиц села имени Мамаита Омарова города Аксу
  kaz: Ақсу қаласы Мәмәйіт Омаров атындағы ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-14
approved_by:
- '164004011001'
version_date:
  kaz: 2010-06-14
  rus: 2010-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/53220/kaz/14.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53220/rus/14.06.2010
