act_code: '118278'
requisite: Решение маслихата города Экибастуза Павлодарской области от 29 декабря 2017 года № 216/25. Зарегистрировано Департаментом юстиции Павлодарской области 23 января 2018 года № 5829. Утратило силу решением Экибастузского городского маслихата Павлодарской области от 7 октября 2021 года № 64/10 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность города Экибастуза
  kaz: Сот шешімімен Екібастұз қаласының коммуналдық меншігіне түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-12-29
approved_by:
- '164013000002'
version_date:
  kaz: 2017-12-29
  rus: 2017-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/118278/kaz/29.12.2017
  rus: https://zan.gov.kz/client/#!/doc/118278/rus/29.12.2017
