act_code: '1757'
requisite: Решение Акима Павлодарской области от 17 сентября 1998 года № 288. Зарегистрировано Управлением юстиции Павлодарской области 23 октября 1998 года за № 79
title:
  rus: О мероприятиях по реализации положений Меморандума Правительства Республики Казахстан по укреплению экономической стабильности
  kaz: Қазақстан Республикасы Үкіметінің экономикалық тұрақтылықты нығайту жөніндегі Меморандумы ережелерін жүзеге асыру жөніндегі іс-шаралар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-09-16
approved_by:
- '164000000003'
version_date:
  kaz: 1998-09-16
  rus: 1998-09-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/1757/kaz/16.09.1998
  rus: https://zan.gov.kz/client/#!/doc/1757/rus/16.09.1998
