act_code: '150598'
requisite: Решение Успенского районного маслихата Павлодарской области от 23 декабря 2020 года № 336/67. Зарегистрировано Департаментом юстиции Павлодарской области 28 декабря 2020 года № 7119
title:
  rus: Об установлении повышенных на двадцать пять процентов окладов и тарифных ставок специалистам в области социального обеспечения и культуры являющимся гражданскими служащими и работающим в сельских населенных пунктах Успенского района
  kaz: Успен ауданының азаматтық қызметшілері болып табылатын және ауылдық елді мекендерде жұмыс істейтін әлеуметтік қамсыздандыру және мәдениет саласының мамандарына жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '164011000002'
version_date:
  kaz: 2020-12-23
  rus: 2020-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/150598/kaz/23.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150598/rus/23.12.2020
