act_code: '30634'
requisite: Павлодар облысы Май аудандық мәслихатының 2006 жылғы 1 желтоқсандағы № 1/30 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2006 жылғы 7 желтоқсанда № 12-10-38 тіркелген
title:
  rus: Ауылдық жерде жұмыс істейтін және мемлекеттік қызметкер болып табылмайтын әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт салалары мамандарының айлық ақылары мен тарифтік мөлшерлемелерін 25 пайызға көтеру туралы
  kaz: Ауылдық жерде жұмыс істейтін және мемлекеттік қызметкер болып табылмайтын әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт салалары мамандарының айлық ақылары мен тарифтік мөлшерлемелерін 25 пайызға көтеру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-01
approved_by:
- '164010000002'
version_date:
  kaz: 2006-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/30634/kaz/01.12.2006
