act_code: '137783'
requisite: Решение маслихата города Аксу Павлодарской области от 27 декабря 2019 года № 383/55. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2019 года № 6694
title:
  rus: О бюджете сельских округов города Аксу на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Ақсу қаласы ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '164004000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137783/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137783/rus/27.12.2019
