act_code: '175805'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 22 декабря 2022 года № 182/25
title:
  rus: Об Экибастузском городском бюджете на 2023 - 2025 годы
  kaz: 2023 - 2025 жылдарға арналған Екібастұз қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-22
approved_by:
- '164013000002'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/175805/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/175805/rus/05.12.2023
caused_by:
  code: '189593'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 5 декабря 2023 года № 98/11
  title:
    rus: О внесении изменений врешение Экибастузского городского маслихата от 22 декабря 2022 года № 182/25 «Об Экибастузском городском бюджете на 2023 - 2025 годы»
    kaz: Екібастұз қалалық мәслихатының 2022 жылғы 22 желтоқсандағы «2023 - 2025 жылдарға арналған Екібастұз қалалық бюджеті туралы» № 182/25 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189593/rus
