act_code: '16913'
requisite: Решение акима города Павлодара от 11 декабря 2002 года № 550. Зарегистрировано Управлением юстиции Павлодарской области 14 января 2003 года за № 1590. Утратило силу - решением акима города Павлодара Павлодарской области от 25 апреля 2007 года № 9
title:
  rus: О добровольных дружинах по охране общественного порядка
  kaz: Қоғамдық тәртiптi сақтау жөнiндегi ерiктi жасақтар туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-11
approved_by:
- '164002000001'
version_date:
  kaz: 2003-02-10
  rus: 2003-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/16913/kaz/10.02.2003
  rus: https://zan.gov.kz/client/#!/doc/16913/rus/10.02.2003
caused_by:
  code: '17648'
  requisite: Решение акима города Павлодара от 10 февраля 2003 года № 71. Зарегистрировано управлением юстиции Павлодарской области 19 февраля 2003 года за № 1634. Утратило силу - решением акима города Павлодара Павлодарской области от 25 апреля 2007 года № 9
  title:
    rus: О внесении изменений и дополнений в решение акима города Павлодара от 11 декабря 2002 года № 550 "О добровольных дружинах по охране общественного порядка" (НГР 1590 от 14 января 2003 года)
    kaz: Павлодар қаласы әкiмiнiң 2002 жылғы 11 желтоқсандағы "Қоғамдық тәртiптi сақтау жөнiндегi ерiктi жасақтар туралы" № 550 шешiмiне өзгерiстер мен толықтырулар енгiзу туралы (2003 жылғы 14 қаңтардағы МТН 1590)
  link: https://zan.gov.kz/client/#!/doc/17648/rus
