act_code: '43296'
requisite: Павлодар облысы Май аудандық мәслихатының 2008 жылғы 19 желтоқсандағы № 14 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2008 жылғы 8 қаңтарда № 77 тіркелген
title:
  rus: 1992 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 1992 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-19
approved_by:
- '164010000002'
version_date:
  kaz: 2008-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/43296/kaz/19.12.2008
