act_code: '90069'
requisite: Решение маслихата Павлодарской области от 4 мая 2015 года № 349/41. Зарегистрировано Департаментом юстиции Павлодарской области 02 июня 2015 года № 4506. Утратило силу решением маслихата Павлодарской области от 13 декабря 2018 года № 297/26 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении  Положения о государственном  учреждении «Ревизионная комиссия по Павлодарской области»
  kaz: «Павлодар облысы бойынша тексеру комиссиясы» мемлекеттік мекемесі туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-05-04
approved_by:
- '164000000002'
version_date:
  kaz: 2015-05-04
  rus: 2015-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/90069/kaz/04.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90069/rus/04.05.2015
