act_code: '137878'
requisite: Решение маслихата города Экибастуза Павлодарской области от 27 декабря 2019 года № 410/51. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2020 года № 6705
title:
  rus: О бюджете сельских округов, сел и поселков города Экибастуза на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '164013000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/137878/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137878/rus/09.12.2020
caused_by:
  code: '149956'
  requisite: Решение Экибастузского городского маслихата Павлодарской области от 9 декабря 2020 года № 480/62. Зарегистрировано Департаментом юстиции Павлодарской области 20 декабря 2020 года № 7097
  title:
    rus: О внесении изменений в решение Экибастузского городского маслихата от 27 декабря 2019 года № 410/51 «О бюджете сельских округов, сел и поселков города Экибастуза на 2020 - 2022 годы»
    kaz: Екібастұз қалалық мәслихатының 2019 жылғы 27 желтоқсандағы «2020 - 2022 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы» № 410/51 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149956/rus
