act_code: '137878'
requisite: Решение маслихата города Экибастуза Павлодарской области от 27 декабря 2019 года № 410/51. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2020 года № 6705
title:
  rus: О бюджете сельских округов, сел и поселков города Экибастуза на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Екібастұз қаласының ауылдық округтерінің, ауылдарының және поселкелерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-27
approved_by:
- '164013000002'
version_date:
  kaz: 2019-12-27
  rus: 2019-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/137878/kaz/27.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137878/rus/27.12.2019
