act_code: '194133'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 6 марта 2024 года № 122/16. Зарегистрировано в Департаменте юстиции Павлодарской области 11 марта 2024 года № 7502-14. Утратило силу решением Баянаульского районного маслихата Павлодарской области от 19 декабря 2025 года № 409/42 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Баянаульском районе
  kaz: Баянауыл ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салықтар мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-06
approved_by:
- '164005000002'
version_date:
  kaz: 2024-03-06
  rus: 2024-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/194133/kaz/06.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194133/rus/06.03.2024
repealed_on: 2026-01-01
repealed_by:
  code: '219141'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 19 декабря 2025 года № 409/42. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 декабря 2025 года № 37642
  title:
    rus: О признании утратившим силу решение Баянаульского районного маслихата от 6 марта 2024 года № 122/16 «О понижении размера ставки налогов при применении специального налогового режима розничного налога в Баянаульском районе»
    kaz: Баянауыл аудандық мәслихатының «Баянауыл ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салықтар мөлшерлемесінің мөлшерін төмендету туралы» 2024 жылғы 6 наурыздағы № 122/16 шешімінің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/219141/rus
