act_code: '27828'
requisite: Решение Маслихата Павлодарского района от 21 марта 2006 года № 22/119. Зарегистрировано Управлением юстиции Павлодарского района 28 марта 2006 года № 12-11-24
title:
  rus: О ставках разовых талонов по выпасу домашних животных и птиц, реализации кормов для животных и птиц, веников, метел, лесных ягод, меда, грибов и рыбы
  kaz: Үй жануарлары мен құстарды бағу, жануарлар мен құстардың жемдерін, сыпыртқы, орман жемістерін, балды,саңырауқұлақ пен балықтарды өткізу үшін берілетін бір жолғы талондардың құны туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-03-21
approved_by:
- '164014000002'
version_date:
  kaz: 2006-03-21
  rus: 2006-03-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/27828/kaz/21.03.2006
  rus: https://zan.gov.kz/client/#!/doc/27828/rus/21.03.2006
