act_code: '39166'
requisite: Решение маслихата Иртышского района Павлодарской области от 31 марта 2008 года № 36-6-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 24 апреля 2008 года № 12-7-68
title:
  rus: Об утверждении стоимости талонов и ставок фиксированного суммарного налога по отдельным видам предпринимательской деятельности
  kaz: Кәсіпкерлік қызметтің жеке түрлері бойынша талондардың құнын және жалпы бағалы салықтың мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-31
approved_by:
- '164007000002'
version_date:
  kaz: 2008-03-31
  rus: 2008-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/39166/kaz/31.03.2008
  rus: https://zan.gov.kz/client/#!/doc/39166/rus/31.03.2008
