act_code: '56126'
requisite: Решение маслихата Павлодарской области от 13 декабря 2010 года № 321/29. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2010 года № 3178
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2011 год по Павлодарской области
  kaz: Павлодар облысы бойынша қоршаған ортаға эмиссиялар үшін 2011 жылға арналған төлемақы мөлшермелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-13
approved_by:
- '164000000002'
version_date:
  kaz: 2014-09-03
  rus: 2014-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/56126/kaz/03.09.2014
  rus: https://zan.gov.kz/client/#!/doc/56126/rus/03.09.2014
