act_code: '150530'
requisite: Решение Аксуского городского маслихата Павлодарской области от 23 декабря 2020 года № 475/71. Зарегистрировано Департаментом юстиции Павлодарской области 25 декабря 2020 года № 7107
title:
  rus: О бюджете города Аксу на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '164004000002'
version_date:
  kaz: 2021-04-16
  rus: 2021-04-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/150530/kaz/16.04.2021
  rus: https://zan.gov.kz/client/#!/doc/150530/rus/16.04.2021
caused_by:
  code: '154911'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 16 апреля 2021 года № 30/4. Зарегистрировано Департаментом юстиции Павлодарской области 21 апреля 2021 года № 7255
  title:
    rus: О внесении изменений и дополнений в решение Аксуского городского маслихата от 23 декабря 2020 года № 475/71 «О бюджете города Аксу на 2021 - 2023 годы»
    kaz: Ақсу қалалық мәслихатының 2020 жылғы 23 желтоқсандағы «2021 - 2023 жылдарға арналған Ақсу қаласының бюджеті туралы» № 475/71 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154911/rus
