act_code: '66610'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2012 жылғы 18 маусымдағы № 33/6 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 12 шілдеде № 12-5-111 тіркелді. Күші жойылды - Павлодар облысы Баянауыл аудандық мәслихатының 2013 жылғы 26 наурыздағы № 81/14 шешімімен
title:
  rus: Баянауыл ауданы мұқтаж азаматтарының жекелеген санаттарына әлеуметтік көмек тағайындау туралы
  kaz: Баянауыл ауданы мұқтаж азаматтарының жекелеген санаттарына әлеуметтік көмек тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-06-18
approved_by:
- '164005000002'
version_date:
  kaz: 2012-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/66610/kaz/18.06.2012
