act_code: '83037'
requisite: Решение маслихата города Аксу Павлодарской области от 11 августа 2014 года № 253/36. Зарегистрировано Департаментом юстиции Павлодарской области 9 сентября 2014 года № 4000. Утратило силу решением Аксуского городского маслихата Павлодарской области от 4 декабря 2020 года № 473/70 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении количества представителей жителей сел для участия в сходе местного сообщества и правил проведения раздельных сходов местного сообщества на территории сельского округа имени Мамаита Омарова города Аксу
  kaz: Ақсу қаласы Мәмәйіт Омаров атындағы селолық округі аумағында жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің санын және бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-08-11
approved_by:
- '164004000002'
version_date:
  kaz: 2014-08-11
  rus: 2014-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/83037/kaz/11.08.2014
  rus: https://zan.gov.kz/client/#!/doc/83037/rus/11.08.2014
