act_code: '30842'
requisite: Павлодар облысы Май аудандық мәслихатының 2006 жылғы 20 желтоқсандағы № 3/31 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2006 жылғы 22 желтоқсанда № 12-10-39 тіркелген
title:
  rus: 2007 жылға арналған аудандық бюджетті бекіту туралы
  kaz: 2007 жылға арналған аудандық бюджетті бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-20
approved_by:
- '164010000002'
version_date:
  kaz: 2006-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/30842/kaz/20.12.2006
