act_code: '195129'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 27 марта 2024 года № 72/22. Зарегистрировано в Департаменте юстиции Павлодарской области 2 апреля 2024 года № 7530-14
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Щербактинском районе
  kaz: Шарбақты ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '164012000002'
version_date:
  kaz: 2026-05-08
  rus: 2026-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/195129/kaz/08.05.2026
  rus: https://zan.gov.kz/client/#!/doc/195129/rus/08.05.2026
caused_by:
  code: '225156'
  requisite: Решение Щербактинского районного маслихата Павлодарской области от 8 мая 2026 года № 178/60. Зарегистрировано в Министерстве юстиции Республики Казахстан 13 мая 2026 года № 38704
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата Павлодарской области от 27 марта 2024 года № 72/22 «Об определении размера и порядка оказания жилищной помощи в Щербактинском районе»
    kaz: Павлодар облысы Шарбақты аудандық мәслихатының 2024 жылғы 27 наурыздағы «Шарбақты ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» № 72/22 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225156/rus
