act_code: '3128'
requisite: Решение акима Павлодарской области от 26 апреля 1999 года № 82. Зарегистрировано Управлением юстиции Павлодарской области 1 июня 1999 года № 162
title:
  rus: О реализации мероприятий Государственной программы развития и поддержки малого предпринимательства в Республике Казахстан на 1999 - 2000 годы
  kaz: Қазақстан Республикасында шағын кәсіпкерлікті дамыту және қолдаудың 1999 - 2000 жылдарға арналған мемлекеттік Бағдарламасының іс-шараларын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-25
approved_by:
- '164000000001'
version_date:
  kaz: 1999-04-25
  rus: 1999-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/3128/kaz/25.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3128/rus/25.04.1999
