act_code: '151310'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 29 декабря 2020 года № 563/74. Зарегистрировано Департаментом юстиции Павлодарской области 6 января 2021 года № 7155
title:
  rus: О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2021 – 2023 годы
  kaz: 2021 – 2023 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-29
approved_by:
- '164002000002'
version_date:
  kaz: 2021-05-14
  rus: 2021-05-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/151310/kaz/14.05.2021
  rus: https://zan.gov.kz/client/#!/doc/151310/rus/14.05.2021
caused_by:
  code: '156532'
  requisite: Решение Павлодарского городского маслихата Павлодарской области от 14 мая 2021 года № 34/4. Зарегистрирован в Министерстве юстиции Республики Казахстан 21 июня 2021 года № 23134
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата от 29 декабря 2020 года № 563/74 «О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2021 – 2023 годы»
    kaz: Павлодар қалалық мәслихатының 2020 жылғы 29 желтоқсандағы «2021 – 2023 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы» № 563/74 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156532/rus
