act_code: '198329'
requisite: Решение акима города Экибастуза Павлодарской области от 1 июля 2024 года № 9
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера объектового масштаба
  kaz: Объектілік ауқымдағы техногендік сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-01
approved_by:
- '164013000003'
version_date:
  kaz: 2024-07-01
  rus: 2024-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/198329/kaz/01.07.2024
  rus: https://zan.gov.kz/client/#!/doc/198329/rus/01.07.2024
