act_code: '63671'
requisite: Павлодар облысы Лебяжі аудандық мәслихатының 2012 жылғы 30 қаңтардағы № 3/2 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 16 ақпанда № 12-9-157 тіркелді
title:
  rus: Лебяжі ауданы бойынша 2012 жылғы әлеуметтік көмекке құқығы бар азаматтардың санаттары туралы
  kaz: Лебяжі ауданы бойынша 2012 жылғы әлеуметтік көмекке құқығы бар азаматтардың санаттары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-30
approved_by:
- '164009000002'
version_date:
  kaz: 2012-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/63671/kaz/30.01.2012
