act_code: '223985'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 10 апреля 2026 года № 45/366
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Павлодарского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшелерін белгілеудің және Павлодар ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-04-10
approved_by:
- '164014000002'
version_date:
  kaz: 2026-08-13
  rus: 2026-08-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/223985/kaz/13.08.2026
  rus: https://zan.gov.kz/client/#!/doc/223985/rus/13.08.2026
caused_by:
  code: '228880'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 13 августа 2026 года № 48/400
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата Павлодарской области от 10 апреля 2026 года № 45/366 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Павлодарского района»
    kaz: Павлодар облысы Павлодар аудандық мәслихатының 2026 жылғы 10 сәуірдегі «Әлеуметтік көмек көрсетудің, оның мөлшелерін белгілеудің және Павлодар ауданы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» № 45/366 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228880/rus
