act_code: '208526'
requisite: Решение Успенского районного маслихата Павлодарской области от 18 марта 2025 года № 146/30
title:
  rus: Об утверждении программы по управлению коммунальными отходами Успенского района Павлодарской области на 2025-2029 годы
  kaz: 2025-2029 жылдарға арналған Павлодар облысы Успен ауданының коммуналдық қалдықтарын басқару жөніндегі бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2025-03-18
approved_by:
- '164011000002'
version_date:
  kaz: 2025-03-18
  rus: 2025-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/208526/kaz/18.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208526/rus/18.03.2025
