act_code: '135286'
requisite: Решение маслихата Павлодарской области от 27 сентября 2019 года № 380/34. Зарегистрировано Департаментом юстиции Павлодарской области 14 октября 2019 года № 6575
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников Павлодарской области на 2019 год
  kaz: Павлодар облысының жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін 2019 жылға арналған төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-09-27
approved_by:
- '164000000002'
version_date:
  kaz: 2019-09-27
  rus: 2019-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/135286/kaz/27.09.2019
  rus: https://zan.gov.kz/client/#!/doc/135286/rus/27.09.2019
