act_code: '9300'
requisite: Решение Акима Павлодарской области от 24 апреля 2001 года № 99. Зарегистрировано Управлением юстиции 4 мая 2001 года за № 660. Утратило силу решением Акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: О вопросах областного центра реабилитации
  kaz: Облыстық сауықтыру орталығының мәселелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-23
approved_by:
- '164000000003'
version_date:
  kaz: 2001-04-23
  rus: 2001-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/9300/kaz/23.04.2001
  rus: https://zan.gov.kz/client/#!/doc/9300/rus/23.04.2001
