act_code: '162606'
requisite: Решение Аксуского городского маслихата Павлодарской области от 23 декабря 2021 года № 108/14
title:
  rus: Об утверждении Положения о государственном учреждении «Аппарат маслихата города Аксу»
  kaz: «Ақсу қалалық мәслихатының аппараты» мемлекеттік мекемесі туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2021-12-23
approved_by:
- '164004000002'
version_date:
  kaz: 2021-12-23
  rus: 2021-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/162606/kaz/23.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162606/rus/23.12.2021
