act_code: '128115'
requisite: Решение маслихата города Аксу Павлодарской области от 29 декабря 2018 года № 285/37. Зарегистрировано Департаментом юстиции Павлодарской области 3 января 2019 года № 6217
title:
  rus: О бюджете сельских округов на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған селолық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '164004000002'
version_date:
  kaz: 2018-12-29
  rus: 2018-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/128115/kaz/29.12.2018
  rus: https://zan.gov.kz/client/#!/doc/128115/rus/29.12.2018
