act_code: '56124'
requisite: Решение маслихата Железинского района Павлодарской области от 23 декабря 2010 года № 231-4/30. Зарегистрировано Департаментом юстиции Павлодарской области 24 декабря 2010 года № 12-6-103
title:
  rus: О районном бюджете на 2011 - 2013 годы
  kaz: 2011 - 2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '164006000002'
version_date:
  kaz: 2011-10-25
  rus: 2011-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/56124/kaz/25.10.2011
  rus: https://zan.gov.kz/client/#!/doc/56124/rus/25.10.2011
caused_by:
  code: '61209'
  requisite: Решение маслихата Железинского района Павлодарской области от 25 октября 2011 года № 299-4/38. Зарегистрировано Департаментом юстиции Павлодарской области 09 ноября 2011 года № 12-6-123
  title:
    rus: О внесении изменений в решение районного маслихата (XXX - сессия IY - созыв) от 23 декабря 2010 года № 231-4/30 "О районном бюджете на 2011 - 2013 годы"
    kaz: Аудандық мәслихаттың (IY сайланған XXX сессиясы) 2010 жылғы 23 желтоқсандағы № 231-4/30 "2011 - 2013 жылдарға арналған аудан бюджеті туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/61209/rus
