act_code: '163327'
requisite: Решение Иртышского районного маслихата Павлодарской области от 29 декабря 2021 года № 57-13-7
title:
  rus: О бюджете сёл и сельских округов Иртышского района на 2022–2024 годы
  kaz: 2022–2024 жылдарға арналған Ертіс ауданының ауылдар және ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164007000002'
version_date:
  kaz: 2022-12-01
  rus: 2022-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/163327/kaz/01.12.2022
  rus: https://zan.gov.kz/client/#!/doc/163327/rus/01.12.2022
caused_by:
  code: '174627'
  requisite: Решение Иртышского районного маслихата Павлодарской области от 1 декабря 2022 года № 102-25-7
  title:
    rus: О внесении изменений в решение Иртышского районного маслихата «О бюджете сёл и сельских округов Иртышского района на 2022 – 2024 годы» от 29 декабря 2021 года № 57-13-7
    kaz: Ертіс аудандық мәслихатының 2021 жылғы 29 желтоқсандағы № 57-13-7 «2022 – 2024 жылдарға арналған Ертіс ауданының ауылдар және ауылдық округтерінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174627/rus
