act_code: '172838'
requisite: Решение Майского районного маслихата Павлодарской области от 14 октября 2022 года № 3/19. Утратило силу решением Майского районного маслихата Павлодарской области от 30 ноября 2023 года № 3/6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения сходов местного сообщества и определения количества представителей жителей села для участия в сходе местного сообщества на территории села Акжар Майского района
  kaz: Май ауданы Ақжар ауылының аумағында жергілікті қоғамдастықтың жиындарын өткізудің және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын айқындаудың тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-10-14
approved_by:
- '164010000002'
version_date:
  kaz: 2022-10-14
  rus: 2022-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/172838/kaz/14.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172838/rus/14.10.2022
