act_code: '16774'
requisite: Решение Павлодарского городского Маслихата от 4 июля 2003 года № 62/32. Зарегистрировано Управлением юстиции Павлодарской области 15 августа 2003 года за № 1999. Утратило силу решением маслихата города Павлодара Павлодарской области от 19 июня 2008 года № 148/7
title:
  rus: Об утверждении "Правил оказания жилищной помощи малообеспеченным гражданам по оплате содержания жилища и потребления коммунальных услуг из бюджета города Павлодара"
  kaz: '"Павлодар қаласы бюджетiнен аз қамтамасыз етiлген азаматтарға тұрғын үйдi ұстау және коммуналдық қызметтi тұтыну төлемақысы бойынша тұрғын үй көмегі көрсету жөнiндегi қағиданы" бекiту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2003-07-03
approved_by:
- '164002000002'
version_date:
  kaz: 2007-03-28
  rus: 2007-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/16774/kaz/28.03.2007
  rus: https://zan.gov.kz/client/#!/doc/16774/rus/28.03.2007
caused_by:
  code: '32685'
  requisite: Решение маслихата города Павлодара Павлодарской области № 29/31. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 5 апреля 2007 года № 12-1-85
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата 4 июля 2003 года № 62/32 "Об утверждении «Правил оказания жилищных субсидий малообеспеченным гражданам по оплате содержания жилья и потребления коммунальных услуг из бюджета города Павлодара» ( 31 очередная сессия 3 созыва)
    kaz: Павлодар қалалык мәслихатының жылғы 4 шілдедегі «Павлодар қаласы бюджетінен аз қамтамасыз ен азаматтарға тұрғын үйді ұстау коммуналдык қызметті тұтыну төлемақысы  бойынша тұрғын үй жәрдемақысын көрсету қағидасын» бекіту туралы» № 62/32 шешіміне өзгерістер енгізу туралы (3 сайланған 31 кезекті сессия)
  link: https://zan.gov.kz/client/#!/doc/32685/rus
