act_code: '132306'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 30 мая 2019 года № 379/52. Зарегистрировано Департаментом юстиции Павлодарской области 10 июня 2019 года № 6410. Утратило силу решением Павлодарского городского маслихата Павлодарской области от 30 марта 2021 года № 9/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об установлении категорий автостоянок (паркингов) и увеличении базовой ставки налога на земли, занятые под автостоянки (паркинги)
  kaz: Автотұрақтар (паркингтер) санаттарын белгілеу және автотұрақтар (паркингтер) орналасқан жерлерге арналған базалық салық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-30
approved_by:
- '164002000002'
version_date:
  kaz: 2019-05-30
  rus: 2019-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/132306/kaz/30.05.2019
  rus: https://zan.gov.kz/client/#!/doc/132306/rus/30.05.2019
