act_code: '10221'
requisite: Решение Павлодарского областного маслихата (ХІІ сессия, ІІ созыв) от 25 мая 2001 года. Зарегистрировано Управлением юстиции Павлодарской области 26 июня 2001 года за № 771
title:
  rus: Об областной программе развития и государственной поддержки малого предпринимательства на 2001 – 2002 годы
  kaz: Шағын кәсіпкерлікті мемлекеттік қолдау мен дамытудың 2001 – 2002 жылдарғы арналған облыстық бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-24
approved_by:
- '164000000002'
version_date:
  kaz: 2001-05-24
  rus: 2001-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/10221/kaz/24.05.2001
  rus: https://zan.gov.kz/client/#!/doc/10221/rus/24.05.2001
