act_code: '137869'
requisite: Решение маслихата Актогайского района Павлодарской области от 30 декабря 2019 года № 284/60. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2020 года № 6701
title:
  rus: О бюджете сельских округов Актогайского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Ақтоғай ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '164003000002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/137869/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/137869/rus/15.12.2020
caused_by:
  code: '149965'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 15 декабря 2020 года № 334/71. Зарегистрировано Департаментом юстиции Павлодарской области 20 декабря 2020 года № 7098
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 30 декабря 2019 года № 284/60 «О бюджете сельских округов Актогайского района на 2020 - 2022 годы»
    kaz: Ақтоғай аудандық мәслихатының 2019 жылғы 30 желтоқсандағы «2020 - 2022 жылдарға арналған Ақтоғай ауданының ауылдық округтерінің бюджеті туралы» № 284/60 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149965/rus
