act_code: '137869'
requisite: Решение маслихата Актогайского района Павлодарской области от 30 декабря 2019 года № 284/60. Зарегистрировано Департаментом юстиции Павлодарской области 5 января 2020 года № 6701
title:
  rus: О бюджете сельских округов Актогайского района на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Ақтоғай ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '164003000002'
version_date:
  kaz: 2019-12-30
  rus: 2019-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137869/kaz/30.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137869/rus/30.12.2019
