act_code: '81262'
requisite: Решение маслихата Павлодарского района Павлодарской области от 13 июня 2014 года № 34/252. Зарегистрировано Департаментом юстиции Павлодарской области 11 июля 2014 года № 3868. Утратило силу решением маслихата Павлодарского района Павлодарской области от 15 сентября 2015 года № 51/393 (вводится в действие со дня первого официального опубликования)
title:
  rus: Об утверждении Регламента Павлодарского районного маслихата
  kaz: Павлодар аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-06-13
approved_by:
- '164014000002'
version_date:
  kaz: 2014-06-13
  rus: 2014-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/81262/kaz/13.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81262/rus/13.06.2014
