act_code: '159718'
requisite: Решение Успенского районного маслихата Павлодарской области от 6 октября 2021 года № 52/8. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 октября 2021 года № 24872
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Успенском районе
  kaz: Успен ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-06
approved_by:
- '164011000002'
version_date:
  kaz: 2023-08-09
  rus: 2023-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/159718/kaz/09.08.2023
  rus: https://zan.gov.kz/client/#!/doc/159718/rus/09.08.2023
caused_by:
  code: '185151'
  requisite: Решение Успенского районного маслихата Павлодарской области от 9 августа 2023 года № 28/5. Зарегистрировано в Департаменте юстиции Павлодарской области 18 августа 2023 года № 7385-14
  title:
    rus: О внесении изменений в решение Успенского районного маслихата от 6 октября 2021 года № 52/8 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Успенском районе»
    kaz: Успен аудандық мәслихатының 2021 жылғы 6 қазандағы № 52/8 «Успен ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185151/rus
