act_code: '204615'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 24 декабря 2024 года № 108/37
title:
  rus: О Щербактинском районном бюджете на 2025 – 2027 годы
  kaz: 2025 – 2027 жылдарға арналған Шарбақты аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '164012000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/204615/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204615/rus/24.12.2024
