act_code: '140592'
requisite: Решение акима Алгабасского сельского округа города Аксу Павлодарской области от 13 марта 2020 года № 1-03/02. Зарегистрировано Департаментом юстиции Павлодарской области 26 марта 2020 года № 6770
title:
  rus: О переименовании некоторых улиц села Айнаколь Алгабасского сельского округа города Аксу
  kaz: Ақсу қаласы Алғабас ауылдық округінің Айнакөл ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-13
approved_by:
- '164004003001'
version_date:
  kaz: 2020-03-13
  rus: 2020-03-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/140592/kaz/13.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140592/rus/13.03.2020
