act_code: '188554'
requisite: Решение Железинского районного маслихата Павлодарской области от 16 ноября 2023 года № 63/8. Зарегистрировано в Департаменте юстиции Павлодарской области 20 ноября 2023 года № 7418-14. Утратило силу решением Железинского районного маслихата Павлодарской области от 13 июля 2026 года № 245/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Железинского района
  kaz: Железин ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерінбелгілеудің және мұқтаж азаматтардыңжекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-16
approved_by:
- '164006000002'
version_date:
  kaz: 2024-08-29
  rus: 2024-08-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/188554/kaz/29.08.2024
  rus: https://zan.gov.kz/client/#!/doc/188554/rus/29.08.2024
caused_by:
  code: '200603'
  requisite: Решение Железинского районного маслихата Павлодарской области от 29 августа 2024 года № 131/8. Зарегистрировано в Департаменте юстиции Павлодарской области 13 сентября 2024 года № 7595-14. Утратило силу решением Железинского районного маслихата Павлодарской области от 13 июля 2026 года № 245/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 16 ноября 2023 года № 63/8 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Железинского района»
    kaz: Железин аудандық мәслихатының 2023 жылғы 16 қарашадагы № 63/8 «Железин ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200603/rus
