act_code: '188554'
requisite: Решение Железинского районного маслихата Павлодарской области от 16 ноября 2023 года № 63/8. Зарегистрировано в Департаменте юстиции Павлодарской области 20 ноября 2023 года № 7418-14. Утратило силу решением Железинского районного маслихата Павлодарской области от 13 июля 2026 года № 245/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Железинского района
  kaz: Железин ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерінбелгілеудің және мұқтаж азаматтардыңжекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-16
approved_by:
- '164006000002'
version_date:
  kaz: 2025-05-19
  rus: 2025-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/188554/kaz/19.05.2025
  rus: https://zan.gov.kz/client/#!/doc/188554/rus/19.05.2025
caused_by:
  code: '210402'
  requisite: Решение Железинского районного маслихата Павлодарской области от 19 мая 2025 года № 176/8. Зарегистрировано в Департаменте юстиции Павлодарской области 21 мая 2025 года № 7669-14. Утратило силу решением Железинского районного маслихата Павлодарской области от 13 июля 2026 года № 245/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Железинского районного маслихата от 16 ноября 2023 года № 63/8 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Железинского района»
    kaz: Железин аудандық мәслихатының 2023 жылғы 16 қарашадагы № 63/8 «Железин ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210402/rus
