act_code: '219138'
requisite: Решение Железинского районного маслихата Павлодарской области от 19 декабря 2025 года № 215/8
title:
  rus: О бюджете сельских округов Железинского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '164006000002'
version_date:
  kaz: 2026-03-06
  rus: 2026-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/219138/kaz/06.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219138/rus/06.03.2026
caused_by:
  code: '222845'
  requisite: Решение Железинского районного маслихата Павлодарской области от 6 марта 2026 года № 226/8
  title:
    rus: О внесении изменений в решение Железинского районного маслихата от 19 декабря 2025 года № 215/8 «О бюджете сельских округов Железинского района на 2026-2028 годы»
    kaz: Железин аудандық мәслихатының 2025 жылғы 19 желтоқсандағы «2026-2028 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы» № 215/8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222845/rus
