act_code: '3187'
requisite: Решение акима Павлодарской области от 28 апреля 1999 года № 88. Зарегистрировано Управлением юстиции Павлодарской области 25 мая 1999 года за № 159
title:
  rus: О программе функционирования и развития языков в области на 1999 – 2000 годы
  kaz: 1999 - 2000 жылдары облыста тілдерді қолдану мен дамытудың бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-27
approved_by:
- '164000000003'
version_date:
  kaz: 1999-04-27
  rus: 1999-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/3187/kaz/27.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3187/rus/27.04.1999
