act_code: '5132'
requisite: Решение Акима Павлодарской области от 19 января 2000 года № 18. Зарегистрировано Управлением юстиции Павлодарской области 21 января 2000 года № 205. Утратило силу решением акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: О правилах обеспечения периодичности бюджетных изъятий из бюджетов городов и районов в областной бюджет
  kaz: Қалалар мен аудандардың бюджеттерінен облыстық бюджетке бюджеттік алулардың мерзімдігін қамтамасыз етудің тәртібі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-01-19
approved_by:
- '164000000003'
version_date:
  kaz: 2000-01-19
  rus: 2000-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/5132/kaz/19.01.2000
  rus: https://zan.gov.kz/client/#!/doc/5132/rus/19.01.2000
