act_code: '61090'
requisite: Павлодар облысы Лебяжі ауданы Жамбыл ауылдық округ әкімінің 2011 жылғы 30 қыркүйектегі № 6 шешімі. Павлодар облысы Лебяжі аудандық Әділет басқармасында 2011 жылғы 03 қарашада № 12-9-141 тіркелді
title:
  rus: Лебяжі ауданының Жамбыл ауылдық округіне қарасты Жамбыл, Жаңатаң, Әйтей, Широкое ауылдарының көше атауларын бекіту туралы
  kaz: Лебяжі ауданының Жамбыл ауылдық округіне қарасты Жамбыл, Жаңатаң, Әйтей, Широкое ауылдарының көше атауларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-30
approved_by:
- '164009003002'
version_date:
  kaz: 2011-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/61090/kaz/30.09.2011
