act_code: '195659'
requisite: Решение Павлодарского областного маслихата от 11 апреля 2024 года № 121/11. Зарегистрировано в Департаменте юстиции Павлодарской области 16 апреля 2024 года № 7533-14
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников по Павлодарской области на 2024 год
  kaz: Павлодар облысы бойынша жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін 2024 жылға арналған төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-11
approved_by:
- '164000000002'
version_date:
  kaz: 2024-04-11
  rus: 2024-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/195659/kaz/11.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195659/rus/11.04.2024
