act_code: '83574'
requisite: Решение маслихата Щербактинского района Павлодарской области от 24 сентября 2014 года № 148/48. Зарегистрировано Департаментом юстиции Павлодарской области 8 октября 2014 года № 4071. Утратило силу решением маслихата Щербактинского района Павлодарской области от 19 июня 2019 года № 196/58 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количества представителей жителей села для участия в сходе местного сообщества на территории Красиловского сельского округа Щербактинского района
  kaz: Шарбақты ауданы Красиловка ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-09-24
approved_by:
- '164012000002'
version_date:
  kaz: 2014-09-24
  rus: 2014-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/83574/kaz/24.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83574/rus/24.09.2014
