act_code: '193570'
requisite: Решение Железинского районного маслихата Павлодарской области от 15 февраля 2024 года № 93/8. Зарегистрировано в Департаменте юстиции Павлодарской области 23 февраля 2024 года № 7485-14
title:
  rus: Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан Железинского района к 35 - летию вывода ограниченного контингента советских войск из Демократической Республики Афганистан
  kaz: Кеңес әскерлерінің шектеулі контингентін Ауғанстан Демократиялық Республикасынан шығарудың 35 жылдығына орай Железин ауданының мұқтаж азаматтарының жекелеген санаттарына қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-15
approved_by:
- '164006000002'
version_date:
  kaz: 2024-02-15
  rus: 2024-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/193570/kaz/15.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193570/rus/15.02.2024
