act_code: '10336'
requisite: Решение Акима Павлодарской области от 8 января 2001 года № 1. Зарегистрировано Управлением юстиции Павлодарской области 5 февраля 2001 года за № 564
title:
  rus: О приписке граждан к призывным участкам на территории области
  kaz: Азаматтарды облыс аумағында әскерге шақыру учаскелеріне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-01-08
approved_by:
- '164000000003'
version_date:
  kaz: 2001-01-08
  rus: 2001-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/10336/kaz/08.01.2001
  rus: https://zan.gov.kz/client/#!/doc/10336/rus/08.01.2001
