act_code: '62592'
requisite: Решение маслихата города Аксу Павлодарской области от 20 декабря 2011 года № 365/42. Зарегистрировано Департаментом юстиции Павлодарской области 09 января 2012 года № 12-2-189
title:
  rus: О бюджете города Аксу на 2012 - 2014 годы
  kaz: 2012 - 2014 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164004000002'
version_date:
  rus: 2012-04-02
source:
  rus: https://zan.gov.kz/client/#!/doc/62592/rus/02.04.2012
