act_code: '160674'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 16 ноября 2021 года № 56/17. Зарегистрировано в Министерстве юстиции Республики Казахстан 25 ноября 2021 года № 25392
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Щербактинском районе
  kaz: Шарбақты ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-16
approved_by:
- '164012000002'
version_date:
  kaz: 2023-06-27
  rus: 2023-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/160674/kaz/27.06.2023
  rus: https://zan.gov.kz/client/#!/doc/160674/rus/27.06.2023
caused_by:
  code: '183321'
  requisite: Решение Щербактинского районного маслихата Павлодарской области от 27 июня 2023 года № 24/7. Зарегистрировано Департаментом юстиции Павлодарской области 27 июня 2023 года № 7361-14
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 16 ноября 2021 года № 56/17 «Об определении порядка и размера возмещения затрат на обучение на дому детей  с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Щербактинском районе»
    kaz: Шарбақты аудандық мәслихатының 2021 жылғы 16 қарашадағы № 56/17 «Шарбақты ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183321/rus
