act_code: '86748'
requisite: Решение маслихата Щербактинского района Павлодарской области от 10 февраля 2015 года № 183/54. Зарегистрировано Департаментом юстиции Павлодарской области 17 февраля 2015 года № 4312. Утратило силу решением маслихата Щербактинского района Павлодарской области от 21 ноября 2019 года № 211/64 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования).
title:
  rus: О предоставлении социальной  помощи на приобретение топлива специалистам государственных организаций социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Щербактинского района
  kaz: Шарбақты ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария  мемлекеттік ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-10
approved_by:
- '164012000002'
version_date:
  kaz: 2015-02-10
  rus: 2015-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/86748/kaz/10.02.2015
  rus: https://zan.gov.kz/client/#!/doc/86748/rus/10.02.2015
