act_code: '149450'
requisite: Решение Железинского районного маслихата Павлодарской области от 30 ноября 2020 года № 499/6. Зарегистрировано Департаментом юстиции Павлодарской области 8 декабря 2020 года № 7081
title:
  rus: Об утверждении проекта (схемы) зонирования земель и о повышении ставок земельного налога Железинского района
  kaz: Железин ауданының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту және жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2020-11-30
approved_by:
- '164006000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/149450/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/149450/rus/29.12.2021
caused_by:
  code: '164230'
  requisite: Решение Железинского районного маслихата Павлодарской области от 29 декабря 2021 года № 103/7. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 февраля 2022 года № 26710
  title:
    rus: О внесении изменения в решение Железинского районного маслихата от 30 ноября 2020 года № 499/6 «Об утверждении проекта (схемы) зонирования земель и о повышении ставок земельного налога Железинского района»
    kaz: Железин аудандық мәслихатының 2020 жылғы 30 қарашадағы № 499/6 «Железин ауданының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту және жер салығының мөлшерлемелерін арттыру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164230/rus
