act_code: '42980'
requisite: Павлодар облысы Лебяжі аудандық мәслихатының 2008 жылғы 25 желтоқсандағы № 2/8 шешімі. Павлодар облысы Лебяжі ауданының Әділет басқармасында 2008 жылғы 25 желтоқсанда № 82 тіркелген
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-25
approved_by:
- '164009000002'
version_date:
  kaz: 2009-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/42980/kaz/26.11.2009
caused_by:
  code: '49009'
  requisite: Павлодар облысы Лебяжі аудандық мәслихатының 2009 жылғы 26 қарашадағы № 1/15 шешімі. Павлодар облысы Лебяжі ауданының Әділет басқармасында 2009 жылғы 1 желтоқсанда № 12-9-99 тіркелген
  title:
    rus: Аудандық мәслихаттың 2008 жылғы 25 желтоқсандағы (VIII сессиясы IV шақырылған) "2009 жылға арналған аудандық бюджет туралы" № 2/8 шешіміне өзгерістер мен толықтырулар енгізу туралы
    kaz: Аудандық мәслихаттың 2008 жылғы 25 желтоқсандағы (VIII сессиясы IV шақырылған) "2009 жылға арналған аудандық бюджет туралы" № 2/8 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/49009/rus
