act_code: '33222'
requisite: Решение маслихата Иртышского района Павлодарской области от 18 апреля 2007 года № 186-37-3. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 08 мая 2007 года № 12-7-49
title:
  rus: О правилах предоставления малообеспеченным гражданам жилищных пособий на содержание жилья и оплату коммунальных услуг
  kaz: Аз қамтамасыз етілген азаматтарға коммуналдық қызметінің төлемі мен тұрғын үйді ұстауға тұрғын үй жәрдемақыларын беру ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-04-18
approved_by:
- '164007000002'
version_date:
  kaz: 2007-04-18
  rus: 2007-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/33222/kaz/18.04.2007
  rus: https://zan.gov.kz/client/#!/doc/33222/rus/18.04.2007
