act_code: '65309'
requisite: Решение акима села Богатырь Успенского района Павлодарской области от 04 апреля 2012 года № 1. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 04 мая 2012 года № 12-12-128
title:
  rus: О присвоении наименований улицам села Богатырь Успенского района
  kaz: Успен ауданының Богатырь ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-04
approved_by:
- '164011002001'
version_date:
  kaz: 2012-04-04
  rus: 2012-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/65309/kaz/04.04.2012
  rus: https://zan.gov.kz/client/#!/doc/65309/rus/04.04.2012
