act_code: '109604'
requisite: Решение акима Жанакурлысского сельского округа Качирского района Павлодарской области от 24 января 2017 года № 2. Зарегистрировано Департаментом юстиции Павлодарской области 31 января 2017 года № 5355
title:
  rus: О переименовании улиц села Трофимовка Жанакурлысского сельского округа Качирского района
  kaz: Качир ауданы Жаңақұрылыс ауылдық округі Трофимовка ауылы көшелерінің атауларын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-01-24
approved_by:
- '164008007001'
version_date:
  kaz: 2017-01-24
  rus: 2017-01-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/109604/kaz/24.01.2017
  rus: https://zan.gov.kz/client/#!/doc/109604/rus/24.01.2017
