act_code: '120124'
requisite: Решение маслихата Баянаульского района Павлодарской области от 16 марта 2018 года № 154/25. Зарегистрировано Департаментом юстиции Павлодарской области 3 апреля 2018 года № 5939. Утратило силу решением маслихата Баянаульского района Павлодарской области от 25 июня 2018 года № 180/30 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Регламента собрания местного сообщества поселка Майкаин Баянаульского района
  kaz: Баянауыл ауданы Майқайың кентінің жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-03-16
approved_by:
- '164005000002'
version_date:
  kaz: 2018-03-16
  rus: 2018-03-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/120124/kaz/16.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120124/rus/16.03.2018
