act_code: '10450'
requisite: Решение Маслихата Павлодарской области от 25 мая 2001 года (ХІІ сессия, ІІ созыв). Зарегистрировано Управлением юстиции Павлодарской области 25 июня 2001 года за № 766
title:
  rus: Об областной программе по обеспечению спортивным инвентарем и реконструкции комплексных спортивных площадок учреждений образования области на 2001 – 2003 годы
  kaz: Облыстық 2001 – 2003 жылдарға арналған облыс оқу орындарын спорттық керек-жарақпен қамтамасыз ету және кешендік спорт алаңдарын қайта жаңарту жөніндегі бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-24
approved_by:
- '164000000002'
version_date:
  kaz: 2001-05-24
  rus: 2001-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/10450/kaz/24.05.2001
  rus: https://zan.gov.kz/client/#!/doc/10450/rus/24.05.2001
