act_code: '127836'
requisite: Решение маслихата Баянаульского района Павлодарской области от 25 декабря 2018 года № 220/39. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2018 года № 6203
title:
  rus: О Баянаульском районном бюджете на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Баянауыл аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '164005000002'
version_date:
  kaz: 2019-06-20
  rus: 2019-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/127836/kaz/20.06.2019
  rus: https://zan.gov.kz/client/#!/doc/127836/rus/20.06.2019
caused_by:
  code: '132993'
  requisite: Решение маслихата Баянаульского района Павлодарской области от 20 июня 2019 года № 253/45. Зарегистрировано Департаментом юстиции Павлодарской области 21 июня 2019 года № 6433
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 25 декабря 2018 года № 220/39 «О Баянаульском районном бюджете на 2019 - 2021 годы»
    kaz: Баянауыл аудандық мәслихатының 2018 жылғы 25 желтоқсандағы «2019 - 2021 жылдарға арналған Баянауыл аудандық бюджеті туралы» № 220/39 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132993/rus
