act_code: '186653'
requisite: Решение акима Октябрьского сельского округа района Тереңкөл Павлодарской области от 29 сентября 2023 года № 1-04/02
title:
  rus: О переименовании улицы села Октябрьское Октябрьского сельского округа района Тереңкөл
  kaz: Тереңкөл ауданы Октябрь ауылдық округі Октябрь ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-29
approved_by:
- '164008005002'
version_date:
  kaz: 2023-09-29
  rus: 2023-09-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/186653/kaz/29.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186653/rus/29.09.2023
