act_code: '162652'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 24 декабря 2021 года № 77/20. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 декабря 2021 года № 26227
title:
  rus: О Щербактинском районном бюджете на 2022 – 2024 годы
  kaz: 2022 – 2024 жылдарға арналған Шарбақты аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164012000002'
version_date:
  kaz: 2022-03-29
  rus: 2022-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/162652/kaz/29.03.2022
  rus: https://zan.gov.kz/client/#!/doc/162652/rus/29.03.2022
caused_by:
  code: '165661'
  requisite: Решение Щербактинского районного маслихата Павлодарской области от 29 марта 2022 года № 90/25
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 24 декабря 2021 года № 77/20 «О Щербактинском районном бюджете на 2022 – 2024 годы»
    kaz: Шарбақты аудандық мәслихатының 2021 жылғы 24 желтоқсандағы № 77/20 «2022 – 2024 жылдарға арналған Шарбақты аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165661/rus
