act_code: '119222'
requisite: Решение исполняющего обязанности акима села Шикылдак города Экибастуза Павлодарской области от 26 февраля 2018 года № 1. Зарегистрировано Департаментом юстиции Павлодарской области 3 марта 2018 года № 5883
title:
  rus: О переименовании некоторых улиц села Шикылдак города Экибастуза
  kaz: Екібастұз қаласы Шиқылдақ ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-02-26
approved_by:
- '164013005002'
version_date:
  kaz: 2018-02-26
  rus: 2018-02-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/119222/kaz/26.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119222/rus/26.02.2018
