act_code: '88692'
requisite: Решение маслихата Качирского района Павлодарской области от 30 марта 2015 года № 11/41. Зарегистрировано Департаментом юстиции Павлодарской области 14 апреля 2015 года № 4421. Утратило силу решением маслихата Качирского района Павлодарской области от 13 июня 2016 года № 1/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Качирском районе
  kaz: Качир ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-30
approved_by:
- '164008000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/88692/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/88692/rus/30.03.2015
