act_code: '221236'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 19 декабря 2025 года № 396/42
title:
  rus: О бюджете Баянаульского сельского округа на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Баянауыл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-19
approved_by:
- '164005000002'
version_date:
  kaz: 2026-04-22
  rus: 2026-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/221236/kaz/22.04.2026
  rus: https://zan.gov.kz/client/#!/doc/221236/rus/22.04.2026
caused_by:
  code: '224633'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 22 апреля 2026 года № 438/48
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 19 декабря 2025 года № 396/42 «О бюджете Баянаульского сельского округа на 2026-2028 годы»
    kaz: Баянауыл аудандық мәслихатының 2025 жылғы 19 желтоқсандағы «2026-2028 жылдарға арналған Баянауыл ауылдық округінің бюджеті туралы» № 396/42 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224633/rus
