act_code: '12318'
requisite: Решение маслихата Павлодарской области от 18 марта 2002 года № 14/18. Зарегистрировано Управлением юстиции Павлодарской области 19 апреля 2002 года за № 1185
title:
  rus: О программе развития физической культуры и спорта в области на 2002 – 2005 годы
  kaz: О программе развития физической культуры и спорта в области на 2002 – 2005 годы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-03-18
approved_by:
- '164000000002'
version_date:
  rus: 2002-03-18
source:
  rus: https://zan.gov.kz/client/#!/doc/12318/rus/18.03.2002
