act_code: '94769'
requisite: Решение акима Панфиловского сельского округа Иртышского района Павлодарской области от 06 октября 2015 года № 4. Зарегистрировано Департаментом юстиции Павлодарской области 22 октября 2015 года № 4764. Утратило силу решением акима Панфиловского сельского округа Иртышского района Павлодарской области от 05 января 2016 года № 2
title:
  rus: Об установлении ограничительных мероприятий на улице имени Муткенова в селе Панфилово Панфиловского сельского округа Иртышского района
  kaz: Ертіс ауданы Панфилов ауылдық округі Панфилов ауылындағы Мүткенов атындағы көшесіне шектеулі іс-шаралар белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-06
approved_by:
- '164007013001'
version_date:
  kaz: 2015-10-06
  rus: 2015-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/94769/kaz/06.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94769/rus/06.10.2015
