act_code: '17322'
requisite: Май аудандық әкімінің 2003 жылғы 4 қыркүйектегі № 71 шешімі. Павлодар облысының Әділет басқармасында 2003 жылғы 10 қазанда № 2072 тіркелді. Күші жойылды - Павлодар облысы Май аудандық әкімінің 2009 жылғы 7 тамыздағы № 04 шешімімен
title:
  rus: Май ауданы өкiлеттi органдарының шешiмi бойынша азаматтардың жекелеген категорияларына берiлетiн әлеуметтiк көмектi тағайындау туралы
  kaz: Май ауданы өкiлеттi органдарының шешiмi бойынша азаматтардың жекелеген категорияларына берiлетiн әлеуметтiк көмектi тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-09-03
approved_by:
- '164010000003'
version_date:
  kaz: 2003-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/17322/kaz/03.09.2003
