act_code: '137439'
requisite: Решение маслихата Успенского района Павлодарской области от 24 декабря 2019 года № 252/53. Зарегистрировано Департаментом юстиции Павлодарской области 26 декабря 2019 года № 6678
title:
  rus: Об Успенском районном бюджете на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Успен аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '164011000002'
version_date:
  kaz: 2020-11-20
  rus: 2020-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/137439/kaz/20.11.2020
  rus: https://zan.gov.kz/client/#!/doc/137439/rus/20.11.2020
caused_by:
  code: '149076'
  requisite: Решение Успенского районного маслихата Павлодарской области от 20 ноября 2020 года № 326/65. Зарегистрировано Департаментом юстиции Павлодарской области 27 ноября 2020 года № 7047
  title:
    rus: О внесении изменений в решение Успенского районного маслихата от 24 декабря 2019 года № 252/53 «Об Успенском районном бюджете на 2020 - 2022 годы»
    kaz: Успен аудандық мәслихатының 2019 жылғы 24 желтоқсандағы «2020 - 2022 жылдарға арналған Успен аудандық бюджеті туралы» № 252/53 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149076/rus
