act_code: '150538'
requisite: Решение Успенского районного маслихата Павлодарской области от 23 декабря 2020 года № 335/67. Зарегистрировано Департаментом юстиции Павлодарской области 25 декабря 2020 года № 7111
title:
  rus: Об Успенском районном бюджете на 2021 - 2023 годы
  kaz: 2021 - 2023 жылдарға арналған Успен аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-23
approved_by:
- '164011000002'
version_date:
  kaz: 2021-05-24
  rus: 2021-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/150538/kaz/24.05.2021
  rus: https://zan.gov.kz/client/#!/doc/150538/rus/24.05.2021
caused_by:
  code: '156201'
  requisite: Решение Успенского районного маслихата Павлодарской области от 24 мая 2021 года № 43/5. Зарегистрировано Департаментом юстиции Павлодарской области 28 мая 2021 года № 7298
  title:
    rus: О внесении изменений и дополнения в решение Успенского районного маслихата от 23 декабря 2020 года № 335/67 «Об Успенском районном бюджете на 2021 - 2023 годы»
    kaz: Успен аудандық мәслихатының 2020 жылғы 23 желтоқсандағы «2021 - 2023 жылдарға арналған Успен аудандық бюджеті туралы» № 335/67 шешіміне өзгерістер және толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156201/rus
