act_code: '56931'
requisite: Павлодар облысы Май ауданы әкімінің 2010 жылғы 31 желтоқсандағы № 6 шешімі. Павлодар облысының Әділет департаментінде 2011 жылғы 21 қаңтарда № 12-10-102 тіркелді
title:
  rus: 1994 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 1994 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-31
approved_by:
- '164010000001'
version_date:
  kaz: 2010-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/56931/kaz/31.12.2010
