act_code: '162548'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 29 декабря 2021 года № 19/97
title:
  rus: О бюджете сельского округа Кемеңгер на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Кемеңгер ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164014000002'
version_date:
  kaz: 2022-09-22
  rus: 2022-09-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/162548/kaz/22.09.2022
  rus: https://zan.gov.kz/client/#!/doc/162548/rus/22.09.2022
caused_by:
  code: '171951'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 22 сентября 2022 года № 28/160
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 29 декабря 2021 года № 19/97 «О бюджете сельского округа Кемеңгер на 2022-2024 годы»
    kaz: Павлодар аудандық мәслихатының 2021 жылғы 29 желтоқсандағы «2022-2024 жылдарға арналған Кемеңгер ауылдық округінің бюджеті туралы» № 19/97 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171951/rus
