act_code: '8738'
requisite: Решение Акима Павлодарской области от 23 января 2001 года № 19. Зарегистрировано Управлением юстиции Павлодарской области 31 января 2001 года за № 563
title:
  rus: Об утверждении плана и сметы распределения средств Павлодарского областного Фонда охраны окружающей среды на 2001 год
  kaz: Павлодар облыстық қоршаған ортаны қорғау Қорының 2001 жылға арналған қаржысын бөлудің жоспары мен сметасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-01-23
approved_by:
- '164000000003'
version_date:
  kaz: 2001-01-23
  rus: 2001-01-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/8738/kaz/23.01.2001
  rus: https://zan.gov.kz/client/#!/doc/8738/rus/23.01.2001
