act_code: '108325'
requisite: Решение маслихата Павлодарской области от 12 декабря 2016 года № 76/10. Зарегистрировано Департаментом юстиции Павлодарской области 21 декабря 2016 года № 5298
title:
  rus: Об областном бюджете на 2017 - 2019 годы
  kaz: 2017 - 2019 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-12-12
approved_by:
- '164000000002'
version_date:
  kaz: 2016-12-12
  rus: 2016-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/108325/kaz/12.12.2016
  rus: https://zan.gov.kz/client/#!/doc/108325/rus/12.12.2016
