act_code: '92980'
requisite: Решение маслихата города Экибастуза Павлодарской области от 29 июля 2015 года № 338/40. Зарегистрировано Департаментом юстиции Павлодарской области 19 августа 2015 года № 4669. Утратило силу решением маслихата города Экибастуза Павлодарской области от 2 февраля 2016 года № 380/47 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса  «Б» аппарата маслихата города Экибастуза»
  kaz: Екібастұз қаласы мәслихат аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-07-29
approved_by:
- '164013000002'
version_date:
  kaz: 2015-07-29
  rus: 2015-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/92980/kaz/29.07.2015
  rus: https://zan.gov.kz/client/#!/doc/92980/rus/29.07.2015
