act_code: '162249'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 24 декабря 2021 года № 106/13. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26060
title:
  rus: О Павлодарском городском бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Павлодар қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164002000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162249/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162249/rus/24.12.2021
