act_code: '162249'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 24 декабря 2021 года № 106/13. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26060
title:
  rus: О Павлодарском городском бюджете на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Павлодар қалалық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '164002000002'
version_date:
  kaz: 2022-12-13
  rus: 2022-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/162249/kaz/13.12.2022
  rus: https://zan.gov.kz/client/#!/doc/162249/rus/13.12.2022
caused_by:
  code: '175436'
  requisite: Решение Павлодарского городского маслихата Павлодарской области от 13 декабря 2022 года № 188/25
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата «О Павлодарском городском бюджете на 2022 – 2024 годы» от 24 декабря 2021 года № 106/13
    kaz: Павлодар қалалық мәслихатының «2022 - 2024 жылдарға арналған Павлодар қалалық бюджеті туралы» 2021 жылғы 24 желтоқсандағы № 106/13 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/175436/rus
