act_code: '180493'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 27 апреля 2023 года № 27/2
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Павлодарского городского маслихата»
  kaz: «Павлодар қалалық мәслихат аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-04-27
approved_by:
- '164002000002'
version_date:
  kaz: 2026-08-11
  rus: 2026-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/180493/kaz/11.08.2026
  rus: https://zan.gov.kz/client/#!/doc/180493/rus/11.08.2026
caused_by:
  code: '229166'
  requisite: Решение Павлодарского городского маслихата Павлодарской области от 11 августа 2026 года № 342/45
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата от 27 апреля 2023 года № 27/2 «Об утверждении Положения государственного учреждения «Аппарат Павлодарского городского маслихата»
    kaz: Павлодар қалалық мәслихатының 2023 жылғы 27 сәуірдегі «Павлодар қалалық мәслихат аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы» № 27/2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229166/rus
