act_code: '162469'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 29 декабря 2021 года № 114/14
title:
  rus: О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2022 – 2024 годы
  kaz: 2022 – 2024 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '164002000002'
version_date:
  kaz: 2022-05-26
  rus: 2022-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/162469/kaz/26.05.2022
  rus: https://zan.gov.kz/client/#!/doc/162469/rus/26.05.2022
caused_by:
  code: '168154'
  requisite: Решение Павлодарского городского маслихата Павлодарской области от 26 мая 2022 года № 138/19
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата «О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2022 – 2024 годы» от 29 декабря 2021 года № 114/14
    kaz: Павлодар қалалық мәслихатының «2022 – 2024 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы» 2021 жылғы 29 желтоқсандағы № 114/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168154/rus
