act_code: '101132'
requisite: Решение маслихата Павлодарского района Павлодарской области от 4 марта 2016 года № 58/424. Зарегистрировано Департаментом юстиции Павлодарской области 11 апреля 2016 года № 5062
title:
  rus: Об утверждении проектов (схем) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Павлодарского района Павлодарской области
  kaz: Павлодар облысы Павлодар ауданының елді мекендерінің жер учаскелеріне бағалау аймақтарының шекараларын және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерiн, жерді аймақтарға бөлу жобаларын (схемаларын) бекіту туралы
form: РЕШ
type_codes:
- ПРОЕ
- РЕШ
- СХЕМ
approved_on: 2016-03-04
approved_by:
- '164014000002'
version_date:
  kaz: 2016-03-04
  rus: 2016-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/101132/kaz/04.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101132/rus/04.03.2016
