act_code: '162154'
requisite: Решение Аксуского городского маслихата Павлодарской области от 23 декабря 2021 года № 95/14. Зарегистрировано в Министерстве юстиции Республики Казахстан 24 декабря 2021 года № 26017
title:
  rus: О бюджете города Аксу на 2022 - 2024 годы
  kaz: 2022 - 2024 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-23
approved_by:
- '164004000002'
version_date:
  kaz: 2022-10-28
  rus: 2022-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/162154/kaz/28.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162154/rus/28.10.2022
caused_by:
  code: '173416'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 28 октября 2022 года № 196/29
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 23 декабря 2021 года № 95/14 «О бюджете города Аксу на 2022-2024 годы»
    kaz: Ақсу қалалық мәслихатының 2021 жылғы 23 желтоқсандағы «2022-2024 жылдарға арналған Ақсу қаласының бюджеті туралы» № 95/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173416/rus
