act_code: '124027'
requisite: Решение маслихата Качирского района Павлодарской области от 27 июля 2018 года № 4/31. Зарегистрировано Департаментом юстиции Павлодарской области 8 августа 2018 года № 6036. Утратило силу решением маслихата района Тереңкөл Павлодарской области от 13 июня 2019 года № 6/45 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата Качирского района»
  kaz: «Качир аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-07-27
approved_by:
- '164008000002'
version_date:
  kaz: 2018-07-27
  rus: 2018-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/124027/kaz/27.07.2018
  rus: https://zan.gov.kz/client/#!/doc/124027/rus/27.07.2018
