act_code: '30762'
requisite: Решение маслихата Павлодарского района от 14 декабря 2006 года № 27/156. Зарегистрировано управлением юстиции Павлодарского района 20 декабря 2006 года № 12-11-35
title:
  rus: «О районном бюджете на 2007 год»
  kaz: «2007 жылға арналған аудандық бюджет туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-14
approved_by:
- '164014000002'
version_date:
  kaz: 2006-12-14
  rus: 2006-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/30762/kaz/14.12.2006
  rus: https://zan.gov.kz/client/#!/doc/30762/rus/14.12.2006
