act_code: '56218'
requisite: Решение маслихата города Павлодара Павлодарской области от 24 декабря 2010 года № 79/29. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 28 декабря 2010 года № 12-1-165
title:
  rus: О бюджете города Павлодара на 2011 - 2013 годы
  kaz: Павлодар қаласының 2011 - 2013 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '164002000002'
version_date:
  kaz: 2011-07-01
  rus: 2011-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/56218/kaz/01.07.2011
  rus: https://zan.gov.kz/client/#!/doc/56218/rus/01.07.2011
caused_by:
  code: '59475'
  requisite: Решение маслихата города Павлодара Павлодарской области от 01 июля 2011 года № 34/34. Зарегистрировано Департаментом юстиции Павлодарской области 07 июля 2011 года № 12-1-173
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата от 24 декабря 2010 года № 79/29 "О бюджете города Павлодара на 2011 - 2013 годы"
    kaz: Павлодар қалалық мәслихатының 2010 жылғы 24 желтоқсандағы "Павлодар қаласының 2011 - 2013 жылдарға арналған бюджеті туралы" № 79/29 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59475/rus
