act_code: '36583'
requisite: Постановление акимата Успенского района Павлодарской области от 3 декабря 2007 года № 22. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 21 декабря 2007 года № 12-12-44
title:
  rus: О проведении приписки граждан 1991 года рождения к призывному участку Успенского района в январе-марте 2008 года
  kaz: 2008 жылдың қаңтар-наурыз айларында Успен ауданының шақыру учаскесінде 1991 жылы туған азаматтарды тізімге алуды өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-03
approved_by:
- '164011000003'
version_date:
  kaz: 2007-12-03
  rus: 2007-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/36583/kaz/03.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36583/rus/03.12.2007
