act_code: '207673'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 4 марта 2025 года № 28/245
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в Павлодарском районе на 2025 - 2029 годы
  kaz: Павлодар ауданында 2025 - 2029 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-04
approved_by:
- '164014000002'
version_date:
  kaz: 2025-03-04
  rus: 2025-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/207673/kaz/04.03.2025
  rus: https://zan.gov.kz/client/#!/doc/207673/rus/04.03.2025
