act_code: '12300'
requisite: Павлодар облыстық мәслихаттың II сайланған XIX (кезектен тыс)  сессиясы 2002 жылғы 25 сәуірдегі № 31/19 шешімі. Павлодар облысының Әділет басқармасында 2002 жылғы 16 мамырда № 1210 тіркелді
title:
  rus: 2001 – 2003 жылдарға арналған облыстық «Ауыз су» бағдарламасын жүзеге асыру жөніндегі 2002 жылға арналған іс-шаралар жоспары туралы
  kaz: 2001 – 2003 жылдарға арналған облыстық «Ауыз су» бағдарламасын жүзеге асыру жөніндегі 2002 жылға арналған іс-шаралар жоспары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-04-24
approved_by:
- '164000000002'
version_date:
  kaz: 2002-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/12300/kaz/24.04.2002
