act_code: '167046'
requisite: Решение Майского районного маслихата Павлодарской области от 13 апреля 2022 года № 2/14. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 апреля 2022 года № 27773
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченным возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Майском районе
  kaz: Май ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-13
approved_by:
- '164010000002'
version_date:
  kaz: 2022-12-23
  rus: 2022-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/167046/kaz/23.12.2022
  rus: https://zan.gov.kz/client/#!/doc/167046/rus/23.12.2022
caused_by:
  code: '176973'
  requisite: Решение Майского районного маслихата Павлодарской области от 23 декабря 2022 года № 4/23. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 января 2023 года № 31616
  title:
    rus: О внесении изменений в решение маслихата от 13 апреля 2022 года № 2/14 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Майском районе»
    kaz: Май аудандық мәслихатының 2022 жылғы 13 сәуірдегі № 2/14 «Май ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/176973/rus
