act_code: '24524'
requisite: Решение Павлодарского областного Маслихата от 30 мая 2005 года № 51/12. Зарегистрировано Департаментом юстиции Павлодарской области 24 июня 2005 года за № 3037
title:
  rus: О плане мероприятий на 2005 год по реализации программы стабилизации цен на основные продовольственные товары в области на 2004 - 2005 годы
  kaz: Облыста негiзгi азық-түлiк товарларына бағаларды тұрақтандырудың 2004 - 2005 жылдарға арналған бағдарламасын iске асыру жөнiндегi 2005 жылға арналған iс-шаралар туралы
form: РЕШ
type_codes:
- МРП
- ПЛАН
- РЕШ
approved_on: 2005-05-30
approved_by:
- '164000000002'
version_date:
  kaz: 2009-03-18
  rus: 2009-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/24524/kaz/18.03.2009
  rus: https://zan.gov.kz/client/#!/doc/24524/rus/18.03.2009
