act_code: '79487'
requisite: Решение маслихата Иртышского района Павлодарской области от 30 апреля 2014 года № 134-30-5. Зарегистрировано Департаментом юстиции Павлодарской области 30 апреля 2014 года № 3786. Утратило силу решением Иртышского районного маслихата Павлодарской области от 14 декабря 2020 года № 264-60-6 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням
  kaz: Атаулы және мереке күндеріне жеке алынған санаттағы алушылар үшін әлеуметтік көмек мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-30
approved_by:
- '164007000002'
version_date:
  kaz: 2019-09-06
  rus: 2019-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/79487/kaz/06.09.2019
  rus: https://zan.gov.kz/client/#!/doc/79487/rus/06.09.2019
caused_by:
  code: '134820'
  requisite: Решение маслихата Иртышского района Павлодарской области от 6 сентября 2019 года № 189-44-6. Зарегистрировано Департаментом юстиции Павлодарской области 23 сентября 2019 года № 6543. Утратило силу решением Иртышского районного маслихата Павлодарской области от 14 декабря 2020 года № 264-60-6 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Иртышского районного маслихата от 30 апреля 2014 года № 134-30-5 «Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням»
    kaz: Ертіс аудандық мәслихатының 2014 жылғы 30 сәуірдегі «Атаулы және мереке күндеріне жеке алынған санаттағы алушылар үшін әлеуметтік көмек мөлшерлерін белгілеу туралы» № 134-30-5 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134820/rus
