act_code: '227042'
requisite: Решение Успенского районного маслихата Павлодарской области от 26 июня 2026 года № 239/53
title:
  rus: Об утверждении ставок туристского взноса для иностранцев по Успенскому району на 2026 год
  kaz: 2026 жылға арналған Успен ауданы бойынша шетелдіктер үшін туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-06-26
approved_by:
- '164011000002'
version_date:
  kaz: 2026-06-26
  rus: 2026-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/227042/kaz/26.06.2026
  rus: https://zan.gov.kz/client/#!/doc/227042/rus/26.06.2026
