act_code: '218803'
requisite: Решение Успенского районного маслихата Павлодарской области от 17 декабря 2025 года № 204/44
title:
  rus: Об Успенском районном бюджете на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Успен аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-17
approved_by:
- '164011000002'
version_date:
  kaz: 2025-12-17
  rus: 2025-12-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/218803/kaz/17.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218803/rus/17.12.2025
