act_code: '192867'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 25 января 2024 года № 63/19
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в Щербактинском районе
  kaz: Шарбақты ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-01-25
approved_by:
- '164012000002'
version_date:
  kaz: 2024-01-25
  rus: 2024-01-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/192867/kaz/25.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192867/rus/25.01.2024
