act_code: '3018'
requisite: Решение акима Павлодарской области от 21 апреля 1999 года № 75. Зарегистрировано Управлением юстиции Павлодарской области 19 мая 1999 года за № 149. Утратило силу решением акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: О создании зон цивилизованной охоты и рыбной ловли
  kaz: Аңшылық пен балық аулаудың өркениетті аймақтарын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-20
approved_by:
- '164000000003'
version_date:
  kaz: 1999-04-20
  rus: 1999-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/3018/kaz/20.04.1999
  rus: https://zan.gov.kz/client/#!/doc/3018/rus/20.04.1999
