act_code: '219291'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 22 декабря 2025 года № 293/36
title:
  rus: О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2026 – 2028 годы
  kaz: 2026 – 2028 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '164002000002'
version_date:
  kaz: 2026-03-30
  rus: 2026-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/219291/kaz/30.03.2026
  rus: https://zan.gov.kz/client/#!/doc/219291/rus/30.03.2026
caused_by:
  code: '223834'
  requisite: Решение Павлодарского городского маслихата Павлодарской области от 30 марта 2026 года № 311/40
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата «О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2026 – 2028 годы» от 22 декабря 2025 года № 293/36
    kaz: Павлодар қалалық мәслихатының 2025 жылғы 22 желтоқсандағы «2026 – 2028 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы» № 293/36 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/223834/rus
