act_code: '120122'
requisite: Решение маслихата Баянаульского района Павлодарской области от 16 марта 2018 года № 152/25. Зарегистрировано Департаментом юстиции Павлодарской области 2 апреля 2018 года № 5937. Утратило силу решением Баянаульского районного маслихата Павлодарской области от 29 декабря 2025 года № 415/43 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Баянаульского районного маслихата»
  kaz: «Баянауыл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-03-16
approved_by:
- '164005000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/120122/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/120122/rus/28.04.2023
caused_by:
  code: '181060'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 28 апреля 2023 года № 32/3. Утратило силу решением Баянаульского районного маслихата Павлодарской области от 29 декабря 2025 года № 415/43 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Баянаульского районного маслихата от 16 марта 2018 года № 152/25 «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Баянаульского районного маслихата»
    kaz: Баянауыл аудандық мәслихатының 2018 жылғы 16 наурыздағы «Баянауыл аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» № 152/25 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/181060/rus
