act_code: '69050'
requisite: Решение маслихата Щербактинского района Павлодарской области от 21 ноября 2012 года № 49/15. Зарегистрировано Департаментом юстиции Павлодарской области 11 декабря 2012 года № 3276
title:
  rus: О предоставлении единовременной денежной компенсации на приобретение топлива для отопления жилых помещений педагогическим работникам образования Щербактинского района в 2012 году
  kaz: 2012 жылы Шарбақты ауданының білім берудегі педагог қызметкерлеріне тұрғын үй-жайларын жылыту үшін отын сатып алуға бір жолғы ақшалай өтемақы беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-21
approved_by:
- '164012000002'
version_date:
  kaz: 2012-11-21
  rus: 2012-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/69050/kaz/21.11.2012
  rus: https://zan.gov.kz/client/#!/doc/69050/rus/21.11.2012
