act_code: '123529'
requisite: Решение маслихата Павлодарского района Павлодарской области от 29 июня 2018 года № 35/183. Зарегистрировано Департаментом юстиции Павлодарской области 17 июля 2018 года № 6020. Утратило силу решением Павлодарского районного маслихата Павлодарской области от 14 апреля 2023 года № 2/15 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента собрания местного сообщества села Ольгинка, сельских округов Павлодарского района
  kaz: Павлодар ауданы Ольгинка ауылының, ауылдық округтерінің  жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2018-06-29
approved_by:
- '164014000002'
version_date:
  kaz: 2021-10-06
  rus: 2021-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/123529/kaz/06.10.2021
  rus: https://zan.gov.kz/client/#!/doc/123529/rus/06.10.2021
caused_by:
  code: '159234'
  requisite: Решение Павлодарского районного маслихата Павлодарской области от 6 октября 2021 года № 12/59
  title:
    rus: О внесении изменений в решение Павлодарского районного маслихата от 29 июня 2018 года № 35/183 «Об утверждении регламента собрания местного сообщества села Ольгинка, сельских округов Павлодарского района»
    kaz: Павлодар аудандық мәслихатының 2018 жылғы 29 маусымдағы «Павлодар ауданы Ольгинка ауылының, ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы» № 35/183 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159234/rus
