act_code: '116129'
requisite: Решение маслихата города Аксу Павлодарской области от 3 ноября 2017 года № 143/17. Зарегистрировано Департаментом юстиции Павлодарской области 21 ноября 2017 года № 5695. Утратило силу решением маслихата города Аксу Павлодарской области от 6 ноября 2019 года № 362/50 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций социального обеспечения, образования,  культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах города Аксу
  kaz: Ақсу қаласының ауылдық елді мекендерде тұратын және жұмыс істейтін мемлекеттік әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының  мамандарына отын сатып алуға әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-03
approved_by:
- '164004000002'
version_date:
  kaz: 2017-11-03
  rus: 2017-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/116129/kaz/03.11.2017
  rus: https://zan.gov.kz/client/#!/doc/116129/rus/03.11.2017
