act_code: '207350'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 25 февраля 2025 года № 225/26
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Павлодар
  kaz: Павлодар қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-25
approved_by:
- '164002000002'
version_date:
  kaz: 2025-02-25
  rus: 2025-02-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/207350/kaz/25.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207350/rus/25.02.2025
