act_code: '16867'
requisite: Решение маслихата Успенского района Павлодарской области от 10 апреля 2003 года № 22/24. Зарегистрировано Департаментом юстиции Павлодарской области 7 мая 2003 года № 1782
title:
  rus: Об утверждении Регламента Успенского районного маслихата
  kaz: Успен аудандық мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2003-04-09
approved_by:
- '164011000002'
version_date:
  kaz: 2003-04-09
  rus: 2003-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/16867/kaz/09.04.2003
  rus: https://zan.gov.kz/client/#!/doc/16867/rus/09.04.2003
