act_code: '40060'
requisite: Решение акимата поселка Солнечный города Экибастуза Павлодарской области от 7 мая 2008 года № 06/1-03. Зарегистрировано Управлением юстиции города Экибастуза Павлодарской области 5 июня 2008 года за № 12-3-170
title:
  rus: Об утверждении Стандартов оказания государственных услуг государственным учреждением «Аппарат акима поселка Солнечный города Экибастуза»
  kaz: '"Екібастұз қаласы Солнечный поселкесі әкімінің аппараты" мемлекеттік мекемесімен мемлекеттік қызмет көрсетудің Стандартын бекіту туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-05-07
approved_by:
- '164013014001'
version_date:
  kaz: 2008-05-07
  rus: 2008-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/40060/kaz/07.05.2008
  rus: https://zan.gov.kz/client/#!/doc/40060/rus/07.05.2008
