act_code: '119306'
requisite: Решение маслихата города Аксу Павлодарской области от 27 февраля 2018 года № 176/22. Зарегистрировано Департаментом юстиции Павлодарской области 6 марта 2018 года № 5892. Утратило силу решением Аксуского городского маслихата от 14 сентября 2021 года № 70/9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность города Аксу
  kaz: Сот шешімімен Ақсу қаласының коммуналдық меншігіне түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-02-27
approved_by:
- '164004000002'
version_date:
  kaz: 2018-02-27
  rus: 2018-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/119306/kaz/27.02.2018
  rus: https://zan.gov.kz/client/#!/doc/119306/rus/27.02.2018
