act_code: '176406'
requisite: Решение Актогайского районного маслихата Павлодарской области от 28 декабря 2022 года № 149/31
title:
  rus: О бюджете Караобинского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Қараоба ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '164003000002'
version_date:
  kaz: 2023-04-24
  rus: 2023-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/176406/kaz/24.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176406/rus/24.04.2023
caused_by:
  code: '180254'
  requisite: Решение Актогайского районного маслихата Павлодарской области от 24 апреля 2023 года № 24/3
  title:
    rus: О внесении изменений в решение Актогайского районного маслихата от 28 декабря 2022года № 149/31 «О бюджете Караобинского сельского округа на 2023-2025 годы»
    kaz: Ақтоғай аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 149/31 «2023-2025 жылдарға арналған Қараоба ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180254/rus
