act_code: '63060'
requisite: Павлодар облысы Май ауданы әкімінің 2012 жылғы 04 қаңтардағы № 1 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 26 қаңтарда № 12-10-119 тіркелді
title:
  rus: 1995 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
  kaz: 1995 жылы туған азаматтарды шақыру учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-01-04
approved_by:
- '164010000001'
version_date:
  kaz: 2012-01-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/63060/kaz/04.01.2012
