act_code: '62858'
requisite: Павлодар облысы Май аудандық мәслихатының 2011 жылғы 20 желтоқсандағы № 8/44 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 18 қаңтарда № 12-10-118 тіркелді. Күші жойылды - Павлодар облысы Май аудандық мәслихатының 2013 жылғы 21 қарашадағы № 2/24 шешімімен
title:
  rus: Тіркелген салықтың ставкаларын бекіту туралы
  kaz: Тіркелген салықтың ставкаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164010000002'
version_date:
  kaz: 2011-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/62858/kaz/20.12.2011
