act_code: '29247'
requisite: Павлодар облысы Баянауыл ауданы әкімінің 2006 жылғы 14 шілдедегі № 24 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2006 жылғы 20 шілдеде № 12-5-28 тіркелді
title:
  rus: Күркелі селолық округінде бруцеллез ауруының шығуына байланысты шектеу (ограничение) қою туралы
  kaz: Күркелі селолық округінде бруцеллез ауруының шығуына байланысты шектеу (ограничение) қою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-07-14
approved_by:
- '164005000003'
version_date:
  kaz: 2006-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/29247/kaz/14.07.2006
