act_code: '150590'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 24 декабря 2020 года № 284/84. Зарегистрировано Департаментом юстиции Павлодарской области 28 декабря 2020 года № 7116
title:
  rus: О Щербактинском районном бюджете на 2021 – 2023 годы
  kaz: 2021 – 2023 жылдарға арналған Шарбақты аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-24
approved_by:
- '164012000002'
version_date:
  kaz: 2021-08-31
  rus: 2021-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/150590/kaz/31.08.2021
  rus: https://zan.gov.kz/client/#!/doc/150590/rus/31.08.2021
caused_by:
  code: '158309'
  requisite: Решение Щербактинского районного маслихата Павлодарской области от 31 августа 2021 года № 46/12. Зарегистрировано в Министерстве юстиции Республики Казахстан 3 сентября 2021 года № 24223
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 24 декабря 2020 года № 284/84 «О Щербактинском районном бюджете на 2021 – 2023 годы»
    kaz: Шарбақты аудандық мәслихатының 2020 жылғы 24 желтоқсандағы № 284/84 «2021 – 2023 жылдарға арналған Шарбақты аудандық бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158309/rus
