act_code: '72385'
requisite: Решение акима Байконысского сельского округа Качирского района Павлодарской области от 23 апреля 2013 года № 6. Зарегистрировано Департаментом юстиции Павлодарской области 06 мая 2013 года № 3532. Утратило силу решением акима Байконысского сельского округа Качирского района Павлодарской области от 25 июля 2013 года № 11
title:
  rus: Об установлении ограничительных мероприятий в селе Кызылтан Байконысского сельского округа
  kaz: Байқоныс ауылдық округінің Қызылтаң ауылында шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-04-23
approved_by:
- '164008008001'
version_date:
  kaz: 2013-04-23
  rus: 2013-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/72385/kaz/23.04.2013
  rus: https://zan.gov.kz/client/#!/doc/72385/rus/23.04.2013
