act_code: '122455'
requisite: Решение маслихата города Аксу Павлодарской области от 8 июня 2018 года № 218/29. Зарегистрировано Департаментом юстиции Павлодарской области 13 июня 2018 года № 5989. Утратило силу решением Аксуского городского маслихата Павлодарской области от 18 октября 2023 года № 67/9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата города  Аксу»
  kaz: «Ақсу қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2018-06-08
approved_by:
- '164004000002'
version_date:
  kaz: 2022-09-21
  rus: 2022-09-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/122455/kaz/21.09.2022
  rus: https://zan.gov.kz/client/#!/doc/122455/rus/21.09.2022
caused_by:
  code: '172011'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 21 сентября 2022 года № 188/27. Отменено решением Аксуского городского маслихата Павлодарской области от 5 декабря 2023 года № 82/10 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 8 июня 2018 года № 218/29 «Об утверждении методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата города Аксу»
    kaz: Ақсу қалалық мәслихатының 2018 жылғы 8 маусымдағы «Ақсу қалалық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы» № 218/29 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172011/rus
