act_code: '194496'
requisite: Решение Щербактинского районного маслихата Павлодарской области от 15 марта 2024 года № 69/21. Зарегистрировано в Департаменте юстиции Павлодарской области 18 марта 2024 года № 7508-14. Утратило силу решением Щербактинского районного маслихата Павлодарской области от 8 мая 2026 года № 179/60 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Щербактинском районе
  kaz: Шарбақты ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салықтар мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-15
approved_by:
- '164012000002'
version_date:
  kaz: 2024-03-15
  rus: 2024-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/194496/kaz/15.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194496/rus/15.03.2024
