act_code: '127824'
requisite: Решение маслихата города Аксу Павлодарской области от 25 декабря 2018 года № 277/36. Зарегистрировано Департаментом юстиции Павлодарской области 27 декабря 2018 года № 6199
title:
  rus: О бюджете города Аксу на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '164004000002'
version_date:
  kaz: 2019-06-19
  rus: 2019-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/127824/kaz/19.06.2019
  rus: https://zan.gov.kz/client/#!/doc/127824/rus/19.06.2019
caused_by:
  code: '132733'
  requisite: Решение маслихата города Аксу Павлодарской области от 19 июня 2019 года № 316/43. Зарегистрировано Департаментом юстиции Павлодарской области 20 июня 2019 года № 6431
  title:
    rus: О внесении изменений и дополнений в решение Аксуского городского маслихата  от 25 декабря 2018 года № 277/36 «О бюджете города Аксу на 2019 - 2021 годы»
    kaz: Ақсу қалалық мәслихатының 2018 жылғы 25 желтоқсандағы «2019 - 2021 жылдарға арналған Ақсу қаласының бюджеті туралы» № 277/36 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132733/rus
