act_code: '49706'
requisite: Решение маслихата Иртышского района Павлодарской области от 24 декабря 2009 года № 138-22-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 5 января 2010 года № 12-7-92. Утратило силу в связи с истечением срока действия - на основании решения маслихата Иртышского района Павлодарской области от 11 февраля 2011 года № 210-34-4
title:
  rus: О районном бюджете на 2010 - 2012 годы
  kaz: 2010 - 2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '164007000002'
version_date:
  kaz: 2010-02-11
  rus: 2010-02-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/49706/kaz/11.02.2010
  rus: https://zan.gov.kz/client/#!/doc/49706/rus/11.02.2010
caused_by:
  code: '50874'
  requisite: Решение маслихата Иртышского района Павлодарской области от 11 февраля 2010 года № 156-25-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 22 февраля 2010 года № 12-7-95
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2009 года № 138-22-4 "О районном бюджете на 2010 - 2012 годы"
    kaz: Аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 138-22-4 "2010 - 2012 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/50874/rus
