act_code: '97644'
requisite: Решение акима Евгеньевского сельского округа города Аксу Павлодарской области от 23 декабря 2015 года № 1-09/06
title:
  rus: О признании утратившим силу решение акима Евгеньевского сельского округа от 24 августа 2015 года № 1-09/04 “Об установлении ограничительных мероприятий”
  kaz: Ақсу қаласы Евгеньевка селолық округі әкімінің 2015 жылғы 24 тамыздағы “Шектеу іс-шараларын белгілеу туралы” № 1-09/04 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '164004008002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/97644/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97644/rus/23.12.2015
