act_code: '49534'
requisite: Решение маслихата города Павлодара Павлодарской области от 23 декабря 2009 года № 168/21. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 29 декабря 2009 года № 12-1-148
title:
  rus: О бюджете города Павлодара на 2010 - 2012 годы
  kaz: Павлодар қаласының 2010 - 2012 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '164002000002'
version_date:
  kaz: 2010-09-08
  rus: 2010-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/49534/kaz/08.09.2010
  rus: https://zan.gov.kz/client/#!/doc/49534/rus/08.09.2010
caused_by:
  code: '54503'
  requisite: Решение маслихата города Павлодара Павлодарской области от 08 сентября 2010 года № 60/26. Зарегистрировано Управлением юстиции города Павлодара Павлодарской области 14 сентября 2010 года № 12-1-160
  title:
    rus: О внесении изменений в решение Павлодарского городского маслихата от 23 декабря 2009 года № 168/21 "О бюджете города Павлодара на 2010 - 2012 годы"
    kaz: Павлодар қалалық мәслихатының 2009 жылғы 23 желтоқсандағы "Павлодар қаласының 2010 - 2012 жылдарға арналған бюджеті туралы" № 168/21 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/54503/rus
