act_code: '15176'
requisite: Решение Павлодарского областного маслихата (XXIV сессия II созыв) от 30 декабря 2002 года № 108/24. Зарегистрировано Управлением юстиции Павлодарской области 28 января 2003 года за № 1603
title:
  rus: Об изменениях в административно-территориальном устройстве некоторых городов и районов области
  kaz: Облыстың кейбiр қалалары мен аудандарының әкiмшiлiк-аумақты құрылысындағы өзгертулер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-30
approved_by:
- '164000000002'
version_date:
  kaz: 2002-12-30
  rus: 2002-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/15176/kaz/30.12.2002
  rus: https://zan.gov.kz/client/#!/doc/15176/rus/30.12.2002
