act_code: '80078'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 06 мая 2014 года № 2/32. Зарегистрировано Департаментом юстиции 22 мая 2014 года № 3818. Утратило силу решением маслихата Лебяжинского района Павлодарской области от 16 сентября 2015 года № 2/45 (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об утверждении Регламента Лебяжинского районного маслихата
  kaz: Лебяжі аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-05-06
approved_by:
- '164009000002'
version_date:
  kaz: 2014-05-06
  rus: 2014-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/80078/kaz/06.05.2014
  rus: https://zan.gov.kz/client/#!/doc/80078/rus/06.05.2014
