act_code: '145231'
requisite: Решение Успенского районного маслихата Павлодарской области от 15 июля 2020 года № 303/61. Зарегистрировано Департаментом юстиции Павлодарской области 30 июля 2020 года № 6879. Утратило силу решением Успенского районного маслихата Павлодарской области от 25 сентября 2023 года № 42/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил проведения раздельных сходов местного сообщества и определения количества представителей жителей улиц для участия в сходе местного сообщества на территории Лозовского сельского округа Успенского района Павлодарской области
  kaz: Павлодар облысы Успен ауданы Лозов ауылдық округінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту және жергілікті қоғамдастық жиынына қатысу үшін көшелер тұрғындары өкілдерінің санын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-15
approved_by:
- '164011000002'
version_date:
  kaz: 2020-07-15
  rus: 2020-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/145231/kaz/15.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145231/rus/15.07.2020
