act_code: '105279'
requisite: Решение маслихата Баянаульского района Павлодарской области от 20 июля 2016 года № 25/05. Зарегистрировано Департаментом юстиции Павлодарской области 09 августа 2016 года № 5197. Утратило силу решением Баянаульского районного маслихата Павлодарской области от 22 августа 2024 года № 197/22 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Баянаульского района
  kaz: Баянауыл ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2016-07-20
approved_by:
- '164005000002'
version_date:
  kaz: 2016-07-20
  rus: 2016-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/105279/kaz/20.07.2016
  rus: https://zan.gov.kz/client/#!/doc/105279/rus/20.07.2016
