act_code: '94070'
requisite: Решение маслихата Майского района Павлодарской области от 15 сентября 2015 года № 3/53. Зарегистрировано Департаментом юстиции Павлодарской области 28 сентября 2015 года № 4732. Утратило силу решением маслихата Майского района Павлодарской области от 26 декабря 2017 года № 3/23 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении регламента Майского районного маслихата
  kaz: Май аудандық  мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2015-09-15
approved_by:
- '164010000002'
version_date:
  kaz: 2015-09-15
  rus: 2015-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/94070/kaz/15.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94070/rus/15.09.2015
