act_code: '79426'
requisite: Решение маслихата города Аксу Павлодарской области от 30 апреля 2014 года № 229/31. Зарегистрировано Департаментом юстиции Павлодарской области 30 апреля 2014 года № 3784. Утратило силу решением маслихата города Аксу Павлодарской области от 20 мая 2019 года № 314/42 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням
  kaz: Алушылардың жеке алынған санаттары үшін атаулы күндер мен мереке күндеріне әлеуметтік көмектің мөлшерлерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-04-30
approved_by:
- '164004000002'
version_date:
  kaz: 2015-02-23
  rus: 2015-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/79426/kaz/23.02.2015
  rus: https://zan.gov.kz/client/#!/doc/79426/rus/23.02.2015
caused_by:
  code: '87716'
  requisite: Решение маслихата города Аксу Павлодарской области от 23 февраля 2015 года № 309/43. Зарегистрировано Департаментом юстиции Павлодарской области 19 марта 2015 года № 4379. Утратило силу решением маслихата города Аксу Павлодарской области от 20 мая 2019 года № 314/42 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 30 апреля 2014 года  № 229/31 «Об установлении размеров социальной помощи для отдельно взятых категорий получателей к памятным датам и праздничным дням»
    kaz: Ақсу қалалық мәслихатының 2014 жылғы 30 сәуірдегі «Алушылардың жеке алынған санаттары үшін атаулы күндер мен мереке күндеріне  әлеуметтік көмектің мөлшерлерін белгілеу туралы» № 229/31 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/87716/rus
