act_code: '45760'
requisite: Решение маслихата города Аксу Павлодарской области от 31 марта 2009 года № 114/15. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 7 мая 2009 года за № 111. Утратило силу решением маслихата города Аксу Павлодарской области от 23 июля 2012 года № 38/7
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным гражданам по оплате содержания жилища, потребления коммунальных услуг, услуг связи и компенсации затрат на отдельные виды капитального ремонта общего имущества объекта кондоминиума  по городу Аксу
  kaz: Ақсу қаласы бойынша аз қамтылған азаматтарға тұрғын үйді ұстауға, коммуналдық қызмет көрсетулерді, байланыс қызмет көрсетулерін тұтынуға және кондоминиум объектісінің ортақ мүлігін күрделі жөндеудің жекелеген түрлеріне шығын өтемақысын төлеу бойынша тұрғын үй көмегінің Қағидасы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2009-03-31
approved_by:
- '164004000002'
version_date:
  kaz: 2009-03-31
  rus: 2009-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/45760/kaz/31.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45760/rus/31.03.2009
