act_code: '76459'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 27 декабря 2013 года N 7/25. Зарегистрировано Департаментом юстиции Павлодарской области 08 января 2014 года N 3654. Утратило силу решением маслихата Лебяжинского района Павлодарской области от 26 декабря 2014 N 1/40 (вводится в действие с 01.01.2015)
title:
  rus: О бюджете Лебяжинского района на 2014 - 2016 годы
  kaz: 2014 - 2016 жылдарға арналған Лебяжі ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-27
approved_by:
- '164009000002'
version_date:
  kaz: 2014-11-03
  rus: 2014-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/76459/kaz/03.11.2014
  rus: https://zan.gov.kz/client/#!/doc/76459/rus/03.11.2014
caused_by:
  code: '84338'
  requisite: Решение маслихата Лебяжинского района Павлодарской области от 03 ноября 2014 года № 1/38. Зарегистрировано Департаментом юстиции Павлодарской области 14 ноября 2014 года № 4154
  title:
    rus: О внесении изменений в решение районного маслихата (XXV сессия V созыв) от 27 декабря 2013 года № 7/25 "О бюджете Лебяжинского района на 2014 - 2016 годы"
    kaz: Аудандық мәслихаттың (V сайланған XXV сессиясы) 2013 жылғы 27 желтоқсандағы "2014 - 2016 жылдарға арналған Лебяжі ауданының бюджеті туралы" № 7/25 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/84338/rus
