act_code: '100164'
requisite: Решение маслихата города Павлодара Павлодарской области от 4 марта 2016 года № 465/64. Зарегистрировано Департаментом юстиции Павлодарской области 14 марта 2016 года № 4993. Утратило силу решением города Павлодара Павлодарской области от 15 марта 2017 года № 139/18 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Павлодарского городского маслихата»
  kaz: «Павлодар қалалық мәслихат аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалау әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2016-03-04
approved_by:
- '164002000002'
version_date:
  kaz: 2016-03-04
  rus: 2016-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/100164/kaz/04.03.2016
  rus: https://zan.gov.kz/client/#!/doc/100164/rus/04.03.2016
