act_code: '33425'
requisite: Павлодар облысы Май аудандық мәслихатының 2007 жылғы 19 сәуірдегі № 3/35 шешімі. Павлодар облысы Май ауданының Әділет басқармасында 2007 жылғы 17 мамырда № 12-10-48 тіркелген
title:
  rus: Аудандық бюджеттік қызметкерлеріне пошта байланыс торабы арқылы еңбекақы төлегені үшін делдалдық сыйақы туралы
  kaz: Аудандық бюджеттік қызметкерлеріне пошта байланыс торабы арқылы еңбекақы төлегені үшін делдалдық сыйақы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-04-19
approved_by:
- '164010000002'
version_date:
  kaz: 2007-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/33425/kaz/19.04.2007
