act_code: '117791'
requisite: Решение маслихата Павлодарского района Павлодарской области от 27 декабря 2017 года № 26/142. Зарегистрировано Департаментом юстиции Павлодарской области 11 января 2018 года № 5812
title:
  rus: О бюджетах некоторых сельских округов Павлодарского района на 2018 - 2020 годы
  kaz: Павлодар ауданының кейбір ауылдық округтерінің 2018 - 2020 жылдарға арналған бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '164014000002'
version_date:
  kaz: 2018-10-25
  rus: 2018-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117791/kaz/25.10.2018
  rus: https://zan.gov.kz/client/#!/doc/117791/rus/25.10.2018
caused_by:
  code: '125970'
  requisite: Решение маслихата Павлодарского района Павлодарской области от 25 октября 2018 года № 40/202. Зарегистрировано Департаментом юстиции Павлодарской области 22 ноября 2018 года № 6118
  title:
    rus: О внесении изменений и дополнений в решение Павлодарского районного маслихата от 27 декабря 2017 года № 26/142 «О бюджетах некоторых сельских округов Павлодарского района на 2018 - 2020 годы»
    kaz: Павлодар аудандық мәслихатының 2017 жылғы 27 желтоқсандағы «Павлодар ауданының кейбір ауылдық округтерінің 2018 - 2020 жылдарға арналған бюджет туралы» № 26/142 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125970/rus
