act_code: '36019'
requisite: Решение маслихата города Павлодара Павлодарской области от 22 октября 2007 года № 31/2. Зарегистрировано управлением юстиции города Павлодара Павлодарской области 26 ноября 2007 года за № 12-1-97. Утратило силу - решением маслихата города Павлодара Павлодарской области от 19 июня 2008 года № 130/7
title:
  rus: Об утверждении "Правил приватизации жилых помещений государственного жилищного фонда города Павлодара"
  kaz: '"Павлодар қаласы мемлекеттік тұрғын үй қорының тұрғын үй-жайларын жекешелендіру қағидаларын" бекіту туралы'
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-10-22
approved_by:
- '164002000002'
version_date:
  kaz: 2007-10-22
  rus: 2007-10-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/36019/kaz/22.10.2007
  rus: https://zan.gov.kz/client/#!/doc/36019/rus/22.10.2007
