act_code: '205274'
requisite: Решение Майского районного маслихата Павлодарской области от 30 декабря 2024 года № 9/24
title:
  rus: О бюджете села Акжар Майского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Май ауданының Ақжар ауылының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '164010000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205274/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205274/rus/30.12.2024
