act_code: '5177'
requisite: Решение акима Павлодарской области от 16 сентября 1999 года № 203. Зарегистрировано управлением юстиции Павлодарской области 01 февраля 2000 года за № 210. Утратило силу решением акима Павлодарской области от 14 сентября 2009 года № 3
title:
  rus: О размерах адресой социальной помощи
  kaz: Атаулы әлеуметтiк көмек мөлшерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-09-15
approved_by:
- '164000000003'
version_date:
  kaz: 1999-09-15
  rus: 1999-09-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/5177/kaz/15.09.1999
  rus: https://zan.gov.kz/client/#!/doc/5177/rus/15.09.1999
