act_code: '192977'
requisite: Решение маслихата района Аққулы Павлодарской области от 31 января 2024 года № 72/17
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села для участия в сходе местного сообщества на территории Кызылагашского сельского округа района Аққулы
  kaz: Аққулы ауданы Қызылағаш ауылдық округігінің аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-01-31
approved_by:
- '164009000002'
version_date:
  kaz: 2024-01-31
  rus: 2024-01-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/192977/kaz/31.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192977/rus/31.01.2024
