act_code: '187263'
requisite: Решение Экибастузского городского маслихата Павлодарской области от 13 октября 2023 года № 70/8
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села для участия в сходе местного сообщества на территории Қояндинского сельского округа города Экибастуза
  kaz: Екібастұз қаласы Қоянды ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-13
approved_by:
- '164013000002'
version_date:
  kaz: 2023-10-13
  rus: 2023-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/187263/kaz/13.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187263/rus/13.10.2023
