act_code: '78301'
requisite: Решение маслихата Качирского района Павлодарской области от 18 февраля 2014 года № 1/26. Зарегистрировано Департаментом юстиции Павлодарской области 28 марта 2014 года № 3743. Утратило силу решением маслихата Качирского района Павлодарской области от 22 апреля 2016 года № 3/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Качирского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Качир ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-02-18
approved_by:
- '164008000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/78301/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/78301/rus/30.03.2015
caused_by:
  code: '88689'
  requisite: Решение маслихата Качирского района Павлодарской области от 30 марта 2015 года № 10/41. Зарегистрировано Департаментом юстиции Павлодарской области 14 апреля 2015 года № 4419. Утратило силу решением маслихата Качирского района Павлодарской области от 22 апреля 2016 года № 3/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений и дополнений в решение Качирского районного маслихата от 18 февраля 2014 года № 1/26 «Об утверждении Правил оказания социальной помощи,установления размеров и определения перечня отдельных категорий  нуждающихся граждан Качирского района»
    kaz: Качир аудандық мәслихатының 2014 жылғы 18 ақпандағы «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Качир ауданындағы мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы» № 1/26 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88689/rus
