act_code: '193778'
requisite: Решение Аксуского городского маслихата Павлодарской области от 9 февраля 2024 года № 103/15. Зарегистрировано в Департаменте юстиции Павлодарской области 20 февраля 2024 года № 7484-14
title:
  rus: Об оказании дополнительной социальной помощи отдельным категориям нуждающихся граждан города Аксу к 35-летию вывода ограниченного контингента советских войск из Демократической Республики Афганистан
  kaz: Ақсу қаласының мұқтаж азаматтарының жекеленген санаттарына Ауғанстан Демократиялық Республикасынан Кеңес әскерлерінің шектеулі контингентінің шығарылғанына 35 жыл толуына орай қосымша әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-09
approved_by:
- '164004000002'
version_date:
  kaz: 2024-02-09
  rus: 2024-02-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/193778/kaz/09.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193778/rus/09.02.2024
