act_code: '126940'
requisite: Решение маслихата Майского района Павлодарской области от 30 ноября 2018 года № 1/38. Зарегистрировано Департаментом юстиции Павлодарской области 14 декабря 2018 года № 6166. Утратило силу решением Майского районного маслихата Павлодарской области от 10 февраля 2022 года № 3/13 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О корректировке базовых ставок земельного налога по Майскому району
  kaz: Май ауданы бойынша жер салығының базалық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-30
approved_by:
- '164010000002'
version_date:
  kaz: 2018-11-30
  rus: 2018-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/126940/kaz/30.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126940/rus/30.11.2018
