act_code: '154413'
requisite: Решение Актогайского районного маслихата Павлодарской области от 30 марта 2021 года № 17/4. Зарегистрировано Департаментом юстиции Павлодарской области 8 апреля 2021 года № 7240
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Актогайском районе
  kaz: Ақтоғай ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-30
approved_by:
- '164003000002'
version_date:
  kaz: 2021-03-30
  rus: 2021-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/154413/kaz/30.03.2021
  rus: https://zan.gov.kz/client/#!/doc/154413/rus/30.03.2021
