act_code: '186316'
requisite: Решение акима города Павлодара Павлодарской области от 18 сентября 2023 года № 7. Утратило силу решением акима города Павлодара Павлодарской области от 7 февраля 2025 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба
  kaz: Жергілікті ауқымдағы техногендік сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-18
approved_by:
- '164002000003'
version_date:
  kaz: 2023-09-18
  rus: 2023-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/186316/kaz/18.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186316/rus/18.09.2023
