act_code: '118333'
requisite: Решение маслихата Актогайского района Павлодарской области от 12 января 2018 года № 152/27. Зарегистрировано Департаментом юстиции Павлодарской области 22 января 2018 года № 5826. Утратило силу решением Актогайского районного маслихата Павлодарской области от 29 сентября 2021 года № 45/10 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил управления бесхозяйными отходами, признанными решением суда поступившими в коммунальную собственность Актогайского района
  kaz: Сот шешімімен Ақтоғай ауданының коммуналдық меншігіне түскен болып танылған иесіз қалдықтарды басқару қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2018-01-12
approved_by:
- '164003000002'
version_date:
  kaz: 2018-01-12
  rus: 2018-01-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/118333/kaz/12.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118333/rus/12.01.2018
