act_code: '77553'
requisite: Решение Успенского районного маслихата Павлодарской области от 30 января 2014 года № 138/31. Зарегистрировано Департаментом юстиции Павлодарской области 21 февраля 2014 года № 3706. Утратило силу решением Успенского районного маслихата Павлодарской области от 12 апреля 2021 года № 27/3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-01-30
approved_by:
- '164011000002'
version_date:
  kaz: 2014-01-30
  rus: 2014-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/77553/kaz/30.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77553/rus/30.01.2014
