act_code: '229070'
requisite: Решение акима Агашорынского сельского округа Иртышского района Павлодарской области от 6 августа 2026 года № 1-03-08
title:
  rus: Об установлении публичного сервитута на территории села Агашорын Агашорынского сельского округа Иртышского района
  kaz: Ертіс ауданы Ағашорын ауылдық округі Ағашорын ауылы аумағында қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-10
approved_by:
- '164007003002'
version_date:
  kaz: 2026-08-10
  rus: 2026-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/229070/kaz/10.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229070/rus/10.08.2026
