act_code: '130635'
requisite: Решение маслихата района Аққулы Павлодарской области от 8 апреля 2019 года № 197/39. Зарегистрировано Департаментом юстиции Павлодарской области 12 апреля 2019 года № 6299
title:
  rus: Об утверждении положения о награждении Почетной грамотой района Аққулы
  kaz: Аққулы ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2019-04-08
approved_by:
- '164009000002'
version_date:
  kaz: 2019-04-08
  rus: 2019-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/130635/kaz/08.04.2019
  rus: https://zan.gov.kz/client/#!/doc/130635/rus/08.04.2019
