act_code: '27831'
requisite: Решение Экибастузкого городского маслихата от 25 апреля 2006 года № 338/25. Зарегистрировано Управлением юстиции города Экибастуза 12 мая 2006 года № 12-3-54
title:
  rus: Об утверждении схемы зонирования земель города Экибастуза, поправочных коэффициентов к ставкам земельного налога по городу Экибастузу
  kaz: Екібастұз қаласының жерін аймаққа бөлу сұлбасы, Екібастұз қаласы бойынша жер салығының мөлшеріне түзету коэффициенттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-04-25
approved_by:
- '164013000002'
version_date:
  kaz: 2006-04-25
  rus: 2006-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/27831/kaz/25.04.2006
  rus: https://zan.gov.kz/client/#!/doc/27831/rus/25.04.2006
