act_code: '56415'
requisite: Решение маслихата города Аксу Павлодарской области от 23 декабря 2010 года № 265/31. Зарегистрировано Департаментом юстиции Павлодарской области 31 декабря 2010 года № 12-2-165
title:
  rus: О бюджете города Аксу на 2011 - 2013 годы
  kaz: 2011 - 2013 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-23
approved_by:
- '164004000002'
version_date:
  kaz: 2011-02-14
  rus: 2011-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/56415/kaz/14.02.2011
  rus: https://zan.gov.kz/client/#!/doc/56415/rus/14.02.2011
caused_by:
  code: '57343'
  requisite: Решение маслихата города Аксу Павлодарской области от 14 февраля 2011 года № 269/32. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 22 февраля 2011 года № 12-2-168
  title:
    rus: О внесении изменений и дополнений в решение Аксуского городского маслихата (XXXI сессия, IV созыв) от 23 декабря 2010 года № 265/31 "О бюджете города Аксу на 2011 - 2013 годы"
    kaz: Ақсу қалалық мәслихатының (IV сайланған XXXI сессиясы) 2010 жылғы 23 желтоқсандағы "2011 - 2013 жылдарға арналған Ақсу қаласының бюджеті туралы" № 265/31 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/57343/rus
