act_code: '133226'
requisite: Решение маслихата Иртышского района Павлодарской области от 28 июня 2019 года № 181-41-6. Зарегистрировано Департаментом юстиции Павлодарской области 11 июля 2019 года № 6473
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Иртышскому району на 2019 - 2020 годы
  kaz: Ертіс ауданы бойынша 2019 - 2020 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2019-06-28
approved_by:
- '164007000002'
version_date:
  kaz: 2019-06-28
  rus: 2019-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/133226/kaz/28.06.2019
  rus: https://zan.gov.kz/client/#!/doc/133226/rus/28.06.2019
