act_code: '38647'
requisite: Решение маслихата Успенского района Павлодарской области от 6 марта 2008 года № 25/5. Зарегистрировано Управлением юстиции Успенского района Павлодарской области 1 апреля 2008 года № 12-12-50. Утратило силу решением маслихата Успенского района Павлодарской области от 27 марта 2009 года № 67
title:
  rus: О правилах благоустройства, санитарной очистки, соблюдения чистоты, организации уборки территории населенных пунктов района
  kaz: Ауданның елді мекендерін көріктендірудің, санитарлық тазалаудың, тазалықты ұстаудың ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2008-03-06
approved_by:
- '164011000002'
version_date:
  kaz: 2008-03-06
  rus: 2008-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/38647/kaz/06.03.2008
  rus: https://zan.gov.kz/client/#!/doc/38647/rus/06.03.2008
