act_code: '9547'
requisite: Решение маслихата Павлодарской области от 25 мая 2001 года (ХІІ сессия, ІІ созыв). Зарегистрировано Управлением юстиции Павлодарской области 26 июня 2001 года за № 772
title:
  rus: О бюджетной программе 6.2.105.60.00 «Социальные выплаты отдельным категориям граждан области на 2001 – 2002 годы»
  kaz: «2001 – 2002 жылдарға арналған облыстың жеке азаматтар тобына әлеуметтік төлемдер» № 6.2.105.60.00 бюджеттік бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-24
approved_by:
- '164000000002'
version_date:
  kaz: 2001-05-24
  rus: 2001-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/9547/kaz/24.05.2001
  rus: https://zan.gov.kz/client/#!/doc/9547/rus/24.05.2001
