act_code: '53256'
requisite: Павлодар облысы Баянауыл ауданы Баянауыл ауылдық округі әкім міндетін атқарушысының 2010 жылғы 10 маусымдағы № 27 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2010 жылғы 23 маусымда № 12-5-77 тіркелген
title:
  rus: Баянауыл ауылдық округі, Баянауыл ауылының көшелерін қайта атау туралы
  kaz: Баянауыл ауылдық округі, Баянауыл ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-10
approved_by:
- '164005002001'
version_date:
  kaz: 2010-06-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/53256/kaz/10.06.2010
