act_code: '126207'
requisite: Решение акима Кенжекольского сельского округа города Павлодара Павлодарской области от 7 ноября 2018 года № 17-1-03/66. Зарегистрировано Департаментом юстиции Павлодарской области 21 ноября 2018 года № 6117
title:
  rus: О переименовании улиц сел Кенжеколь, Байдала и Долгое Кенжекольского сельского округа города Павлодара
  kaz: Павлодар қаласы Кенжекөл ауылдық округіндегі Кенжекөл, Байдала және Долгое ауылдарының көшелеріне қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-07
approved_by:
- '164002002002'
version_date:
  kaz: 2018-11-07
  rus: 2018-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/126207/kaz/07.11.2018
  rus: https://zan.gov.kz/client/#!/doc/126207/rus/07.11.2018
