act_code: '207147'
requisite: Решение Актогайского районного маслихата Павлодарской области от 6 февраля 2025 года № 179/29. Зарегистрировано в Департаменте юстиции Павлодарской области 17 февраля 2025 года № 7637-14
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Актогайского района Павлодарской области
  kaz: Павлодар облысы Ақтоғай ауданының елді мекендерінде жер телімдер үшін бағалау аймақтарының шекараларын және төлемақы базалық мөлшерлемелеріне түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-06
approved_by:
- '164003000002'
version_date:
  kaz: 2025-02-06
  rus: 2025-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/207147/kaz/06.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207147/rus/06.02.2025
