act_code: '205183'
requisite: Решение Аксуского городского маслихата Павлодарской области от 27 декабря 2024 года № 181/30
title:
  rus: О бюджетах сельских округов города Аксу на 2025 - 2027 годы
  kaz: 2025-2027 жылдарға арналған Ақсу қаласы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164004000002'
version_date:
  kaz: 2025-10-24
  rus: 2025-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205183/kaz/24.10.2025
  rus: https://zan.gov.kz/client/#!/doc/205183/rus/24.10.2025
caused_by:
  code: '216056'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 24 октября 2025 года № 234/41
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 27 декабря 2024 года № 181/30 «О бюджете сельских округов города Аксу на 2025-2027 годы»
    kaz: Ақсу қалалық мәслихатының 2024 жылғы 27 желтоқсандағы «2025-2027 жылдарға арналған Ақсу қаласының ауылдық округтерінің бюджеті туралы» № 181/30 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216056/rus
