act_code: '205183'
requisite: Решение Аксуского городского маслихата Павлодарской области от 27 декабря 2024 года № 181/30
title:
  rus: О бюджетах сельских округов города Аксу на 2025 - 2027 годы
  kaz: 2025-2027 жылдарға арналған Ақсу қаласы ауылдық округтерінің бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '164004000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205183/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205183/rus/27.12.2024
