act_code: '39067'
requisite: Павлодар облысы Павлодар қалалық мәслихатының 2008 жылғы 4 сәуірдегі № 126/5 шешімі. Павлодар облысы Павлодар қаласының Әділет басқармасында 2008 жылғы 23 сәуірде № 106 тіркелген
title:
  rus: Қалалық қоғамдық жолаушылар көлігінде (таксиден басқа) жетім ата-анасының қамқорлығынсыз қалған оқушы балалардың жеңілдетілген жол жүруі туралы
  kaz: Қалалық қоғамдық жолаушылар көлігінде (таксиден басқа) жетім ата-анасының қамқорлығынсыз қалған оқушы балалардың жеңілдетілген жол жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-04
approved_by:
- '164002000002'
version_date:
  kaz: 2008-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/39067/kaz/04.04.2008
