act_code: '65239'
requisite: Павлодар облысы Лебяжі аудандық мәслихатының 2012 жылғы 23 сәуірдегі № 3/5 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 04 мамырда № 12-9-162 тіркелді. Күші жойылды - Павлодар облысы Лебяжі аудандық мәслихатының 2013 жылғы 04 желтоқсандағы № 9/23 шешімімен
title:
  rus: Лебяжі ауданы бойынша 2012 - 2013 жылдарға арналған бірыңғай тіркелген салық ставкаларын белгілеу туралы
  kaz: Лебяжі ауданы бойынша 2012 - 2013 жылдарға арналған бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-04-23
approved_by:
- '164009000002'
version_date:
  kaz: 2012-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/65239/kaz/23.04.2012
