act_code: '187734'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 26 октября 2023 года № 10/8
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества на территории Берегового сельского округа района Тереңкөл
  kaz: Тереңкөл ауданы Береговой ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізу Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-26
approved_by:
- '164008000002'
version_date:
  kaz: 2023-10-26
  rus: 2023-10-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/187734/kaz/26.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187734/rus/26.10.2023
