act_code: '36585'
requisite: Решение маслихата Железинского района Павлодарской области от 24 декабря 2007 года № 26-4/3. Зарегистрировано Управлением юстиции Железинского района Павлодарской области 25 декабря 2007 года № 12-6-46
title:
  rus: О районном бюджете на 2008 год
  kaz: О районном бюджете на 2008 год
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '164006000002'
version_date:
  rus: 2007-12-24
source:
  rus: https://zan.gov.kz/client/#!/doc/36585/rus/24.12.2007
