act_code: '70087'
requisite: Решение маслихата Щербактинского района Павлодарской области от 21 декабря 2012 года № 57/18. Зарегистрировано Департаментом юстиции Павлодарской области 14 января 2013 года № 3336. Утратило силу решением маслихата Щербактинского района Павлодарской области от 26 декабря 2013 года № 103/36
title:
  rus: О социальной поддержке отдельных категорий граждан Щербактинского района на 2013 год
  kaz: 2013 жылы Шарбақты ауданындағы жеке санаттардағы азаматтарды әлеуметтік қолдау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-21
approved_by:
- '164012000002'
version_date:
  kaz: 2013-04-19
  rus: 2013-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/70087/kaz/19.04.2013
  rus: https://zan.gov.kz/client/#!/doc/70087/rus/19.04.2013
caused_by:
  code: '72355'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 19 апреля 2013 года № 74/23. Зарегистрировано Департаментом юстиции Павлодарской области 03 мая 2013 года № 3529. Утратило силу решением маслихата Щербактинского района Павлодарской области от 26 декабря 2013 года № 103/36
  title:
    rus: О внесении изменения в решение Щербактинского районного маслихата от 21 декабря 2012 года № 57/18 "О социальной поддержке отдельных категорий граждан Щербактинского района на 2013 год"
    kaz: Шарбақты аудандық мәслихатының 2012 жылғы 21 желтоқсандағы № 57/18 "2013 жылы Шарбақты ауданындағы жеке санаттардағы азаматтарды әлеуметтік қолдау туралы" шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72355/rus
