act_code: '151463'
requisite: Решение Иртышского районного маслихата Павлодарской области от 6 января 2021 года № 273-63-6. Зарегистрировано Департаментом юстиции Павлодарской области 8 января 2021 года № 7175
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Иртышском районе
  kaz: Ертіс ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-06
approved_by:
- '164007000002'
version_date:
  kaz: 2021-04-23
  rus: 2021-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/151463/kaz/23.04.2021
  rus: https://zan.gov.kz/client/#!/doc/151463/rus/23.04.2021
caused_by:
  code: '155583'
  requisite: Решение Иртышского районного маслихата Павлодарской области от 23 апреля 2021 года № 20-4-7. Зарегистрировано Департаментом юстиции Павлодарской области 4 мая 2021 года № 7269
  title:
    rus: О внесении изменения в решение Иртышского районного маслихата от 6 января 2021 года № 273-63-6 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, норм их предельной заполняемости, а также требований к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования в Иртышском районе»
    kaz: Ертіс аудандық мәслихатының 2021 жылғы 6 қаңтардағы «Ертіс ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» № 273-63-6  шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/155583/rus
