act_code: '18908'
requisite: Решение Павлодарского областного маслихата от 10 февраля 2004 года № 5/3. Зарегистрировано Департаментом юстиции Павлодарской области 28 февраля 2004 года за № 2319
title:
  rus: О предельных (максимальных) размерах земельных участков, которые могут находиться в частной собственности граждан для ведения личного подсобного хозяйства (включая приусадебный и полевой наделы) в сельской местности на неорошаемых и орошаемых землях, а также садоводства, индивидуального жилищного и дачного строительства
  kaz: Ауылдық жерлерде суарылмайтын және суармалы жерлерде жеке қосалқы шаруашылығын (үй маңындағы және егiстiк телiмдердi қоса алғанда), сондай-ақ бағбандық және жеке тұрғын үй мен саяжай құрылысын жүргiзу үшiн азаматтардың жеке меншiгiнде болуы мүмкiн жер учаскелерiнiң шектi (ең жоғары) мөлшерлерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2004-02-10
approved_by:
- '164000000002'
version_date:
  kaz: 2004-02-10
  rus: 2004-02-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/18908/kaz/10.02.2004
  rus: https://zan.gov.kz/client/#!/doc/18908/rus/10.02.2004
