act_code: '20491'
requisite: Решение маслихата Павлодарской области от 30 июня 2004 года № 45/6. Зарегистрировано департаментом юстиции Павлодарской области 30 июня 2004 года за № 2633
title:
  rus: О региональной программе развития жилищного строительства и стройиндустрии в области на 2005 - 2007 годы
  kaz: Облыста 2005 - 2007 жылдарға арналған тұрғын үй құрылысы мен құрылыс индустриясын дамыту аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- МРП
- ПЛАН
- ПРОГ
- РЕШ
approved_on: 2004-06-29
approved_by:
- '164000000002'
version_date:
  kaz: 2005-04-15
  rus: 2005-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/20491/kaz/15.04.2005
  rus: https://zan.gov.kz/client/#!/doc/20491/rus/15.04.2005
caused_by:
  code: '24209'
  requisite: Решение Павлодарского областного Маслихата от 15 апреля 2005 года № 42/11. Зарегистрировано Департаментом юстиции Павлодарской области 20 мая 2005 года за № 3023
  title:
    rus: О внесении изменений в решение областного маслихата (VI (внеочередная) сессия III созыв) от 30 июня 2004 года № 45/6 "О региональной программе развития жилищного строительства и стройиндустрии в области на 2005 - 2007 годы"
    kaz: Облыстық мәслихаттың (III сайланған VI (кезектен тыс) сессия) 2004 жылғы 30 маусымдағы "Облыста 2005 - 2007 жылдарға арналған тұрғын үй құрылысы мен құрылыс индустриясын дамыту аймақтық бағдарламасы туралы" № 45/6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/24209/rus
