act_code: '20491'
requisite: Решение маслихата Павлодарской области от 30 июня 2004 года № 45/6. Зарегистрировано департаментом юстиции Павлодарской области 30 июня 2004 года за № 2633
title:
  rus: О региональной программе развития жилищного строительства и стройиндустрии в области на 2005 - 2007 годы
  kaz: Облыста 2005 - 2007 жылдарға арналған тұрғын үй құрылысы мен құрылыс индустриясын дамыту аймақтық бағдарламасы туралы
form: РЕШ
type_codes:
- МРП
- ПЛАН
- ПРОГ
- РЕШ
approved_on: 2004-06-29
approved_by:
- '164000000002'
version_date:
  kaz: 2004-06-29
  rus: 2004-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/20491/kaz/29.06.2004
  rus: https://zan.gov.kz/client/#!/doc/20491/rus/29.06.2004
