act_code: '102683'
requisite: Решение акима Алакольского сельского округа Железинского района Павлодарской области от 21 апреля 2016 года № 1. Зарегистрировано Департаментом юстиции Павлодарской области 25 мая 2016 года № 5131
title:
  rus: О переименовании улицы в селе Алаколь Алакольского сельского округа Железинского района
  kaz: Железин ауданы Алакөл селолық округінің Алакөл селосындағы көшені қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-21
approved_by:
- '164006001001'
version_date:
  kaz: 2016-04-21
  rus: 2016-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/102683/kaz/21.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102683/rus/21.04.2016
