act_code: '162673'
requisite: Решение маслихата района Аққулы Павлодарской области от 30 декабря 2021 года № 55/12
title:
  rus: О бюджетах сельских округов района Аққулы на 2022 - 2024 годы
  kaz: Аққулы ауданының ауылдық округтерінің 2022 - 2024 жылдарға арналған бюджеттері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '164009000002'
version_date:
  kaz: 2021-12-30
  rus: 2021-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/162673/kaz/30.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162673/rus/30.12.2021
