act_code: '94204'
requisite: Решение акима Панфиловского сельского округа Иртышского района Павлодарской области от 06 октября 2015 года № 5
title:
  rus: Об отмене ранее принятого решения акима Панфиловского сельского округа № 2 от 1 июня 2015 года «Об установлении ограничительных                 мероприятий по улице имени Абая в селе Тохта Панфиловского сельского округа Иртышского района»
  kaz: Бұрын, 2015 жылғы 01 маусымда қабылданған, Панфилов ауылдық округінің «Ертіс ауданы Панфилов ауылдық округі Тоқта ауылындағы Абай атындағы көшесіне шектеулі іс-шаралар орнату туралы» № 2 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-06
approved_by:
- '164007013001'
version_date:
  kaz: 2015-10-06
  rus: 2015-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/94204/kaz/06.10.2015
  rus: https://zan.gov.kz/client/#!/doc/94204/rus/06.10.2015
