act_code: '133890'
requisite: Решение маслихата Успенского района Павлодарской области от 29 июля 2019 года № 225/48. Зарегистрировано Департаментом юстиции Павлодарской области 8 августа 2019 года № 6497
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Успенскому району на 2019 - 2020 годы
  kaz: Успен ауданы бойынша 2019 - 2020 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-07-29
approved_by:
- '164011000002'
version_date:
  kaz: 2020-09-18
  rus: 2020-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/133890/kaz/18.09.2020
  rus: https://zan.gov.kz/client/#!/doc/133890/rus/18.09.2020
caused_by:
  code: '146641'
  requisite: Решение Успенского районного маслихата Павлодарской области от 18 сентября 2020 года № 315/63. Зарегистрировано Департаментом юстиции Павлодарской области 24 сентября 2020 года № 6958
  title:
    rus: О внесении изменения в решение Успенского районного маслихата от 29 июля 2019 года № 225/48 «Об утверждении Плана по управлению пастбищами и их использованию по Успенскому району на 2019 - 2020 годы»
    kaz: Успен аудандық мәслихатының 2019 жылғы 29 шілдедегі «Успен ауданы бойынша 2019 - 2020 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі Жоспарды бекіту туралы» № 225/48 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/146641/rus
