act_code: '111319'
requisite: Решение маслихата города Аксу Павлодарской области от 17 марта 2017 года № 87/11. Зарегистрировано Департаментом юстиции Павлодарской области 11 апреля 2017 года № 5458. Утратило силу решением Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по городу Аксу
  kaz: Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-17
approved_by:
- '164004000002'
version_date:
  kaz: 2023-04-12
  rus: 2023-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/111319/kaz/12.04.2023
  rus: https://zan.gov.kz/client/#!/doc/111319/rus/12.04.2023
caused_by:
  code: '179772'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 12 апреля 2023 года № 16/3. Зарегистрировано Департаментом юстиции Павлодарской области 14 апреля 2023 года № 7322. Утратило силу решением Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 17 марта 2017 года № 87/11 «Об определении размера и порядка оказания жилищной помощи по городу Аксу»
    kaz: Ақсу қалалық мәслихатының 2017 жылғы 17 наурыздағы «Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» № 87/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179772/rus
