act_code: '111319'
requisite: Решение маслихата города Аксу Павлодарской области от 17 марта 2017 года № 87/11. Зарегистрировано Департаментом юстиции Павлодарской области 11 апреля 2017 года № 5458. Утратило силу решением Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи по городу Аксу
  kaz: Ақсу қаласы бойынша тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-17
approved_by:
- '164004000002'
version_date:
  kaz: 2022-03-18
  rus: 2022-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/111319/kaz/18.03.2022
  rus: https://zan.gov.kz/client/#!/doc/111319/rus/18.03.2022
caused_by:
  code: '165727'
  requisite: Решение Аксуского городского маслихата Павлодарской области от 18 марта 2022 года № 135/21. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 марта 2022 года № 27270. Утратило силу решением Аксуского городского маслихата Павлодарской области от 28 марта 2024 года № 119/18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата от 17 марта 2017 года № 87/11 «Об определении размера и порядка оказания жилищной помощи малообеспеченным семьям (гражданам) города Аксу»
    kaz: Ақсу қалалық мәслихатының 2017 жылғы 17 наурыздағы «Ақсу қаласында аз қамтамасыз етілген отбасыларына (азаматтарға) тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» № 87/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165727/rus
