act_code: '43292'
requisite: Павлодар облысы Баянауыл аудандық мәслихатының 2008 жылғы 29 желтоқсандағы № 74/12 шешімі. Павлодар облысы Баянауыл ауданының Әділет басқармасында 2009 жылғы 5 қаңтарда № 12-5-61 тіркелген
title:
  rus: Баянауыл ауданының 2009 жылға арналған бюджеті туралы
  kaz: Баянауыл ауданының 2009 жылға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-29
approved_by:
- '164005000002'
version_date:
  kaz: 2010-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/43292/kaz/09.04.2010
