act_code: '83645'
requisite: Решение маслихата Успенского района Павлодарской области от 25 сентября 2014 года № 201/38. Зарегистрировано Департаментом юстиции Павлодарской области 10 октября 2014 года № 4112. Утратило силу решением Успенского районного маслихата Павлодарской области от 15 июля 2020 года № 303/61 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количества представителей жителей сел для участия в сходе местного сообщества на территории Лозовского сельского округа Успенского района
  kaz: Успен ауданы Лозов ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің Қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің санын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-09-25
approved_by:
- '164011000002'
version_date:
  kaz: 2014-09-25
  rus: 2014-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/83645/kaz/25.09.2014
  rus: https://zan.gov.kz/client/#!/doc/83645/rus/25.09.2014
