act_code: '147857'
requisite: Решение маслихата района Аққулы Павлодарской области от 20 октября 2020 года № 279/57. Зарегистрировано Департаментом юстиции Павлодарской области 28 октября 2020 года № 6999. Утратило силу решением маслихата района Аққулы Павлодарской области от 16 ноября 2023 года № 51/11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села для участия в сходе местного сообщества на территории сельского округа Аққулы района Аққулы
  kaz: Аққулы ауданы Аққулы ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің тәртібін бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2020-10-20
approved_by:
- '164009000002'
version_date:
  kaz: 2022-11-15
  rus: 2022-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/147857/kaz/15.11.2022
  rus: https://zan.gov.kz/client/#!/doc/147857/rus/15.11.2022
caused_by:
  code: '173715'
  requisite: Решение маслихата района Аққулы Павлодарской области от 15 ноября 2022 года № 110/22. Утратило силу решением маслихата района Аққулы Павлодарской области от 16 ноября 2023 года № 52/11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата района Аққулы от 20 октября 2020 года № 279/57 «Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей села для участия в сходе местного сообщества на территории сельского округа Аққулы района Аққулы»
    kaz: Аққулы аудандық мәслихатының 2020 жылғы 20 қазандағы «Аққулы ауданы Аққулы ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің тәртібін бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауыл тұрғындары өкілдерінің санын айқындау туралы» № 279/57 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173715/rus
