act_code: '205843'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 30 декабря 2024 года № 265/28
title:
  rus: О бюджете Узунбулакского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ұзынбұлақ ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '164005000002'
version_date:
  kaz: 2025-12-02
  rus: 2025-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/205843/kaz/02.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205843/rus/02.12.2025
caused_by:
  code: '218091'
  requisite: Решение Баянаульского районного маслихата Павлодарской области от 2 декабря 2025 года № 382/40
  title:
    rus: О внесении изменений в решение Баянаульского районного маслихата от 30 декабря 2024 года № 265/28 «О бюджете Узынбулакского сельского округа на 2025-2027 годы»
    kaz: Баянауыл аудандық мәслихатының 2024 жылғы 30 желтоқсандағы «2025-2027 жылдарға арналған Ұзынбұлақ ауылдық округінің бюджеті туралы» № 265/28 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218091/rus
