act_code: '145554'
requisite: Решение маслихата района Аққулы Павлодарской области от 7 августа 2020 года № 275/56. Зарегистрировано Департаментом юстиции Павлодарской области 17 августа 2020 года № 6901. Утратило силу решением маслихата района Аққулы Павлодарской области от 16 ноября 2023 года № 51/11 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Решение маслихата района Аққулы от 7 августа 2020 года № 275/56 "Об утверждении порядка проведения раздельных сходов местного сообщества и определения количества представителей жителей сел для участия в сходе местного сообщества на территории сельского округа Қарақала района Аққулы"
  kaz: Аққулы аудандық мәслихатының 2020 жылғы 7 тамыздағы "Аққулы ауданы Қарақала ауылдық округінің аумағында бөлек жергілікті қоғамдастық жиындарын өткізудің тәртібін бекіту және жергілікті қоғамдастық жиынына қатысу үшін ауылдар тұрғындары өкілдерінің санын айқындау туралы" № 275/56 шешімі
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-08-07
approved_by:
- '164009000002'
version_date:
  kaz: 2020-08-07
  rus: 2020-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/145554/kaz/07.08.2020
  rus: https://zan.gov.kz/client/#!/doc/145554/rus/07.08.2020
