act_code: '95579'
requisite: Решение маслихата Железинского района Павлодарской области от 12 октября 2015 года № 327-5/41. Зарегистрировано Департаментом юстиции Павлодарской области 17 ноября 2015 года № 4794
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в населенных пунктах Железинского района  Павлодарской области
  kaz: Павлодар облысы Железин ауданының елді мекендерінде жер учаскелері үшін бағалау аймақтарының  шекараларын және төлемақы базалық мөлшерлемелеріне  түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-12
approved_by:
- '164006000002'
version_date:
  kaz: 2015-10-12
  rus: 2015-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/95579/kaz/12.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95579/rus/12.10.2015
