act_code: '1592'
requisite: Решение маслихата Павлодарской области от 26 июня 1998 года. Зарегистрировано Управлением юстиции Павлодарской области 4 августа 1998 года № 62
title:
  rus: '"О ситуации на рынке труда и мерах по активизации экономической деятельности населения области"'
  kaz: '"Еңбек нарқындағы хал-ахуал және облыс тұрғындарының экономикалық қызметін жандандыру шаралары туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-06-25
approved_by:
- '164000000002'
version_date:
  kaz: 1998-06-25
  rus: 1998-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/1592/kaz/25.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1592/rus/25.06.1998
