act_code: '59228'
requisite: Решение маслихата города Аксу Павлодарской области от 09 июня 2011 года № 295/34. Зарегистрировано Управлением юстиции города Аксу Павлодарской области 15 июня 2011 года № 12-2-176
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Аксуского региона в 2011 году
  kaz: 2011 жылы Ақсу аймағының елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-06-09
approved_by:
- '164004000002'
version_date:
  kaz: 2011-06-09
  rus: 2011-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/59228/kaz/09.06.2011
  rus: https://zan.gov.kz/client/#!/doc/59228/rus/09.06.2011
