act_code: '62650'
requisite: Павлодар облысы Май аудандық мәслихатының 2011 жылғы 20 желтоқсандағы № 2/44 шешімі. Павлодар облысының Әділет департаментінде 2012 жылғы 09 қаңтарда № 12-10-117 тіркелді
title:
  rus: 2012 - 2014 жылдарға арналған Май аудандық бюджет туралы
  kaz: 2012 - 2014 жылдарға арналған Май аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-20
approved_by:
- '164010000002'
version_date:
  kaz: 2012-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/62650/kaz/24.10.2012
caused_by:
  code: '68397'
  requisite: Решение маслихата Майского района Павлодарской области от 24 октября 2012 года № 4/8. Зарегистрировано Департаментом юстиции Павлодарской области 07 ноября 2012 года № 3249
  title:
    rus: О внесении изменений в решение Майского районного маслихата (XLIV сессия, IV созыв) от 20 декабря 2011 года № 2/44 "О Майском районном бюджете на 2012 - 2014 годы"
    kaz: Май аудандық мәслихатының (IV шақырылған XLIV сессиясы) 2011 жылғы 20 желтоқсандағы "2012 - 2014 жылдарға арналған Май аудандық бюджет туралы" № 2/44 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/68397/rus
