act_code: '48943'
requisite: Павлодар облысы Ақсу қаласы Мәмәйіт Омаров атындағы селолық округ әкімінің 2009 жылғы 22 қазандағы N 1-08 шешімі. Павлодар облысы Ақсу қаласынын Әділет басқармасында 2009 жылғы 2 желтоқсанда N 12-2-117 тіркелген
title:
  rus: Ақсу қаласы Мәмәйіт Омаров атындағы селолық округінің Донентаев, Сырлы-қала, Көктерек және Евден ауылдарындағы көшелерге атаулар беру туралы
  kaz: Ақсу қаласы Мәмәйіт Омаров атындағы селолық округінің Донентаев, Сырлы-қала, Көктерек және Евден ауылдарындағы көшелерге атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-22
approved_by:
- '164004011001'
version_date:
  kaz: 2011-06-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/48943/kaz/14.06.2011
caused_by:
  code: '59229'
  requisite: Павлодар облысы Ақсу қаласы Мәмәйіт Омаров атындағы селолық округі әкімінің 2011 жылғы 14 маусымдағы № 1-10 шешімі. Павлодар облысы Ақсу қаласының Әділет басқармасында 2011 жылғы 15 маусымда № 12-2-177 тіркелді
  title:
    rus: Мәмәйіт Омаров атындағы селолық округі әкімінің 2009 жылғы 22 қазандағы "Ақсу қаласы Мәмәйіт Омаров атындағы селолық округінің Дөнентаев, Сырлы-қала, Көктерек және Евден ауылдарындағы көшелерге атаулар беру туралы" № 1-08 шешіміне өзгеріс енгізу туралы
    kaz: Мәмәйіт Омаров атындағы селолық округі әкімінің 2009 жылғы 22 қазандағы "Ақсу қаласы Мәмәйіт Омаров атындағы селолық округінің Дөнентаев, Сырлы-қала, Көктерек және Евден ауылдарындағы көшелерге атаулар беру туралы" № 1-08 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/59229/rus
