act_code: '137420'
requisite: Решение маслихата района Аққулы Павлодарской области от 23 декабря 2019 года № 241/50. Зарегистрировано Департаментом юстиции Павлодарской области 25 декабря 2019 года № 6677
title:
  rus: О бюджете района Аққулы на 2020 - 2022 годы
  kaz: 2020 - 2022 жылдарға арналған Аққулы аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '164009000002'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/137420/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137420/rus/23.12.2019
