act_code: '9512'
requisite: Решение акима Павлодарской области от 14 мая 2001 года № 111. Зарегистрировано Управлением юстиции Павлодарской области 8 июня 2001 года за № 751. Утратило силу решением акима Павлодарской области от 14 сентября 2009 года № 3
title:
  rus: О правилах разработки местных бюджетных программ (подпрограмм)
  kaz: Жергiлiктi бюджеттiк бағдарламаларды (кiшi бағдарламаларды) әзiрлеу ережелерi туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-05-13
approved_by:
- '164000000001'
version_date:
  kaz: 2001-05-13
  rus: 2001-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/9512/kaz/13.05.2001
  rus: https://zan.gov.kz/client/#!/doc/9512/rus/13.05.2001
