act_code: '202644'
requisite: Решение акима Шарбактинского сельского округа Щербактинского района Павлодарской области от 27 сентября 2024 года № 1-03/8
title:
  rus: Об установлении публичного сервитута акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-27
approved_by:
- '164009006002'
version_date:
  kaz: 2024-09-27
  rus: 2024-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/202644/kaz/27.09.2024
  rus: https://zan.gov.kz/client/#!/doc/202644/rus/27.09.2024
