act_code: '6988'
requisite: Решение акима Павлодарской области от 31 июля 2000 г. № 184. Зарегистрировано Управлением юстиции Павлодарской области 28 августа 2000 г. за № 419. Утратило силу - решением акима Павлодарской области от 19 июня 2003 года № 19
title:
  rus: Об обеспечении пожарной безопасности лесов, степных и пойменных территорий области
  kaz: Облыс ормандары, дала мен өзен аңғарлары аумақтарында өрт қауiпсiздiгiн қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-07-30
approved_by:
- '164000000001'
version_date:
  kaz: 2000-07-30
  rus: 2000-07-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/6988/kaz/30.07.2000
  rus: https://zan.gov.kz/client/#!/doc/6988/rus/30.07.2000
