act_code: '204967'
requisite: Решение Павлодарского городского маслихата Павлодарской области от 26 декабря 2024 года № 218/25
title:
  rus: О бюджете поселка, сельского округа и некоторых сел города Павлодара на 2025 – 2027 годы
  kaz: 2025 – 2027 жылдарға арналған Павлодар қаласы кентінің, ауылдық округінің және кейбір ауылдарының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-26
approved_by:
- '164002000002'
version_date:
  kaz: 2024-12-26
  rus: 2024-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/204967/kaz/26.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204967/rus/26.12.2024
