act_code: '116381'
requisite: Решение маслихата Баянаульского района Павлодарской области от 21 ноября 2017 года № 125/19. Зарегистрировано Департаментом юстиции Павлодарской области 30 ноября 2017 года № 5713
title:
  rus: Об утверждении положения о награждении Почетной грамотой Баянаульского района
  kaz: Баянауыл ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2017-11-21
approved_by:
- '164005000002'
version_date:
  kaz: 2017-11-21
  rus: 2017-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/116381/kaz/21.11.2017
  rus: https://zan.gov.kz/client/#!/doc/116381/rus/21.11.2017
