act_code: '90561'
requisite: Решение акима Байзаковского сельского округа Иртышского района Павлодарской области от 26 мая 2015 года № 2. Зарегистрировано Департаментом юстиции Павлодарской области 16 июня 2015 года № 4526. Утратило силу решением акима Байзаковского сельского округа Иртышского района Павлодарской области от 7 августа 2015 года N 3
title:
  rus: Об установлении карантина на улице Карла Маркса в селе Исы Байзакова Байзаковского сельского округа Иртышского района
  kaz: Ертіс ауданы Байзақов ауылдық округінің Иса Байзақов ауылының Карл Маркс көшесіне карантин орнату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-26
approved_by:
- '164007004001'
version_date:
  kaz: 2015-05-26
  rus: 2015-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/90561/kaz/26.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90561/rus/26.05.2015
