act_code: '1334'
requisite: Решение Акима Павлодарской области от 16 июня 1997 года № 121. Зарегистрировано Управлением юстиции Павлодарской области 19 марта 1998 года за № 20. Утратило силу решением Акима Павлодарской области от 29 октября 2004 года № 25
title:
  rus: Об утверждении Порядка использования средств резервного фонда акима области
  kaz: Облыс әкімі резервтік қорының қаржысын пайдалану тәртібін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 1997-06-15
approved_by:
- '164000000003'
version_date:
  kaz: 1997-06-15
  rus: 1997-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/1334/kaz/15.06.1997
  rus: https://zan.gov.kz/client/#!/doc/1334/rus/15.06.1997
