act_code: '117229'
requisite: Решение маслихата Качирского района Павлодарской области от 21 декабря 2017 года № 1/22. Зарегистрировано Департаментом юстиции Павлодарской области 26 декабря 2017 года № 5758
title:
  rus: О бюджете района Тереңкөл на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған Тереңкөл аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '164008000002'
version_date:
  kaz: 2018-06-20
  rus: 2018-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/117229/kaz/20.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117229/rus/20.06.2018
caused_by:
  code: '123230'
  requisite: Решение маслихата Качирского района Павлодарской области от 20 июня 2018 года № 1/29. Зарегистрировано Департаментом юстиции Павлодарской области 5 июля 2018 года № 6005
  title:
    rus: О внесении изменений и дополнений в решение Качирского районного маслихата от 21 декабря 2017 года № 1/22 «О Качирском районном бюджете на 2018 - 2020 годы»
    kaz: Качир аудандық мәслихатының 2017 жылғы 21 желтоқсандағы «2018 - 2020 жылдарға арналған Качир аудандық бюджеті туралы» № 1/22 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123230/rus
