act_code: '57460'
requisite: Решение маслихата Качирского района Павлодарской области от 24 февраля 2011 года N 1/29. Зарегистрировано Департаментом юстиции Павлодарской области 24 февраля 2011 года N 12-8-103. Утратило силу решением маслихата Качирского района Павлодарской области от 16 марта 2016 года № 1/55 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании проведения мирных собраний, митингов, шествий, пикетов и демонстраций в Качирском районе
  kaz: Качир ауданында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізуді қосымша регламент белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-02-24
approved_by:
- '164008000002'
version_date:
  kaz: 2011-02-24
  rus: 2011-02-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/57460/kaz/24.02.2011
  rus: https://zan.gov.kz/client/#!/doc/57460/rus/24.02.2011
