act_code: '94103'
requisite: Решение маслихата Актогайского района Павлодарской области от 17 сентября 2015 года № 204/48. Зарегистрировано Департаментом юстиции Павлодарской области 02 октября 2015 года № 4739. Отменено решением маслихата Актогайского района Павлодарской области от 18 января 2016 года № 238/55 (вступает в силу со дня подписания)
title:
  rus: Об утверждении методики ежегодной оценки деятельности административных государственных служащих корпуса «Б» аппарата маслихата Актогайского района
  kaz: Ақтоғай аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін жыл сайынғы бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2015-09-17
approved_by:
- '164003000002'
version_date:
  kaz: 2015-09-17
  rus: 2015-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/94103/kaz/17.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94103/rus/17.09.2015
