act_code: '87210'
requisite: Решение акима Павлодарской области от 20 февраля 2015 года № 1. Зарегистрировано Департаментом юстиции Павлодарской области 04 марта 2015 года № 4334. Утратило силу решением акима Павлодарской области от 27 января 2016 года N 1
title:
  rus: Об определении единого организатора государственных закупок для бюджетных организаций  Павлодарской области и товаров, работ, услуг, по которым организация и проведение государственных закупок осуществляется единым организатором
  kaz: Павлодар облысының бюджеттік ұйымдары үшін мемлекеттік сатып алуды бірыңғай ұйымдастырушысын және мемлекеттік сатып алуды ұйымдастыру мен өткізуді бірыңғай ұйымдастырушы жүзеге асыратын тауарларды, жұмыстарды, қызметтерді анықтау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-20
approved_by:
- '164000000001'
version_date:
  kaz: 2015-08-27
  rus: 2015-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/87210/kaz/27.08.2015
  rus: https://zan.gov.kz/client/#!/doc/87210/rus/27.08.2015
caused_by:
  code: '93164'
  requisite: Решение акима Павлодарской области от 27 августа 2015 года № 5. Зарегистрировано Департаментом юстиции Павлодарской области 01 сентября 2015 года № 4677. Утратило силу решением акима Павлодарской области от 27 января 2016 года N 1
  title:
    rus: О внесении дополнения в решение акима Павлодарской области от 20 февраля 2015 года № 1 «Об определении единого организатора государственных закупок для бюджетных организаций Павлодарской области и товаров, работ, услуг, по которым организация и проведение государственных закупок осуществляется единым организатором»
    kaz: Павлодар облысы әкiмiнiң 2015 жылғы 20 ақпандағы «Павлодар облысының бюджеттік ұйымдары үшін мемлекеттік сатып алуды бірыңғай ұйымдастырушысын және мемлекеттік сатып алуды ұйымдастыру мен өткізуді бірыңғай ұйымдастырушы  жүзеге асыратын тауарларды, жұмыстарды, қызметтерді анықтау туралы» № 1 шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93164/rus
