act_code: '117260'
requisite: Решение маслихата Щербактинского района Павлодарской области от 22 декабря 2017 года № 105/32. Зарегистрировано Департаментом юстиции Павлодарской области 28 декабря 2017 года № 5765
title:
  rus: О Щербактинском районном бюджете на 2018  –  2020 годы
  kaz: 2018 – 2020  жылдарға арналған Шарбақты аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-22
approved_by:
- '164012000002'
version_date:
  kaz: 2018-10-25
  rus: 2018-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117260/kaz/25.10.2018
  rus: https://zan.gov.kz/client/#!/doc/117260/rus/25.10.2018
caused_by:
  code: '125846'
  requisite: Решение маслихата Щербактинского района Павлодарской области от 25 октября 2018 года № 147/44. Зарегистрировано Департаментом юстиции Павлодарской области 14 ноября 2018 года № 6112
  title:
    rus: О внесении изменений в решение Щербактинского районного маслихата от 22 декабря 2017 года № 105/32 «О Щербактинском районном бюджете на 2018 – 2020 годы»
    kaz: Шарбақты аудандық мәслихатының 2017 жылғы 22 желтоқсандағы «2018 – 2020 жылдарға арналған Шарбақты аудан бюджеті туралы» № 105/32 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125846/rus
