act_code: '161774'
requisite: Решение акима Казахстанского сельского округа Железинского района Павлодарской области от 13 декабря 2021 года № 14
title:
  rus: Об установлении публичного сервитута на земельные участки
  kaz: Жер учаскелеріне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-13
approved_by:
- '164006008002'
version_date:
  kaz: 2021-12-13
  rus: 2021-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/161774/kaz/13.12.2021
  rus: https://zan.gov.kz/client/#!/doc/161774/rus/13.12.2021
