act_code: '69744'
requisite: Решение маслихата Лебяжинского района Павлодарской области от 20 декабря 2012 года № 1/12. Зарегистрировано Департаментом юстиции Павлодарской области 29 декабря 2012 года № 3316
title:
  rus: О бюджете Лебяжинского района на 2013 - 2015 годы
  kaz: 2013 - 2015 жылдарға арналған Лебяжі ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '164009000002'
version_date:
  kaz: 2014-03-05
  rus: 2014-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/69744/kaz/05.03.2014
  rus: https://zan.gov.kz/client/#!/doc/69744/rus/05.03.2014
