act_code: '23823'
requisite: Павлодар облысы Павлодар аудандық мәслихатының 2005 жылғы 18 наурыздағы № 13/66 шешімі. Павлодар облысының Әділет департаментінде 2005 жылғы 27 сәуірде № 3012 тіркелді
title:
  rus: Табиғи және техногендік сипаттағы төтенше жағдайлар пайда болған кезде қоғамдық тәртіп пен қауіпсіздікті қамтамасыз ету Қағидасын және жасыл екпелерді ұстау, елді мекендер аумақтарын көріктендіру Қағидасын бекіту туралы
  kaz: Табиғи және техногендік сипаттағы төтенше жағдайлар пайда болған кезде қоғамдық тәртіп пен қауіпсіздікті қамтамасыз ету Қағидасын және жасыл екпелерді ұстау, елді мекендер аумақтарын көріктендіру Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2005-03-18
approved_by:
- '164014000002'
version_date:
  kaz: 2005-03-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/23823/kaz/18.03.2005
