act_code: '204555'
requisite: Решение Актогайского районного маслихата Павлодарской области от 19 декабря 2024 года № 168/27
title:
  rus: Об Актогайском районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақтоғай аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-19
approved_by:
- '164003000002'
version_date:
  kaz: 2024-12-19
  rus: 2024-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/204555/kaz/19.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204555/rus/19.12.2024
