act_code: '41037'
requisite: Решение маслихата Иртышского района Павлодарской области от 25 июня 2008 года № 46-7-4. Зарегистрировано Управлением юстиции Иртышского района Павлодарской области 2 августа 2008 года № 12-7-73
title:
  rus: Об утверждении Инструкции по присвоению звания «Почетный гражданин Иртышского района»
  kaz: «Ертіс ауданының  Құрметті азаматы» атағын беру жөніндегі Нұсқауын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-06-25
approved_by:
- '164007000002'
version_date:
  kaz: 2008-06-25
  rus: 2008-06-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/41037/kaz/25.06.2008
  rus: https://zan.gov.kz/client/#!/doc/41037/rus/25.06.2008
