act_code: '186356'
requisite: Решение Аксуского городского маслихата Павлодарской области от 20 сентября 2023 года № 46/7. Отменено решением Аксуского городского маслихата Павлодарской области от 26 сентября 2023 года № 56/8 (решение вступает в силу со дня подписания)
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год по городу Аксу
  kaz: Ақсу қаласы бойынша шетелдіктер үшін 2023 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-09-20
approved_by:
- '164004000002'
version_date:
  kaz: 2023-09-20
  rus: 2023-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/186356/kaz/20.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186356/rus/20.09.2023
