act_code: '136301'
requisite: Решение акима Заринского сельского округа Павлодарского района Павлодарской области от 20 ноября 2019 года № 1-03-10. Зарегистрировано Департаментом юстиции Павлодарской области 25 ноября 2019 года № 6624. Утратило силу решением акима Заринского сельского округа Павлодарского района Павлодарской области от 21 января 2020 года № 1-03-01 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении карантина на территории села Бирлик Заринского сельского округа Павлодарского района
  kaz: Павлодар ауданы Заря ауылдық округі Бірлік ауылының аумағында карантин белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-11-20
approved_by:
- '164014014002'
version_date:
  kaz: 2019-11-20
  rus: 2019-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/136301/kaz/20.11.2019
  rus: https://zan.gov.kz/client/#!/doc/136301/rus/20.11.2019
