act_code: '105921'
requisite: Решение маслихата города Экибастуза Павлодарской области от 19 августа 2016 года № 49/9. Зарегистрировано Департаментом юстиции Павлодарской области 31 августа 2016 года № 5226. Утратило силу решением Экибастузского городского маслихата Павлодарской области от 8 января 2021 года № 497/64 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О повышении ставок земельного налога и ставок единого земельного налога на не используемые в соответствии с земельным законодательством Республики Казахстан земли сельскохозяйственного назначения города Экибастуза Павлодарской области
  kaz: Қазақстан Республикасының жер заңнамасына сәйкес Павлодар облысы Екібастұз қаласының пайдаланылмайтын ауыл шаруашылығы мақсатындағы жерлеріне жер салығының мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-08-19
approved_by:
- '164013000002'
version_date:
  kaz: 2016-08-19
  rus: 2016-08-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/105921/kaz/19.08.2016
  rus: https://zan.gov.kz/client/#!/doc/105921/rus/19.08.2016
