act_code: '191132'
requisite: Решение Железинского районного маслихата Павлодарской области от 28 декабря 2023 года № 84/8
title:
  rus: О бюджете сельских округов Железинского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Железин ауданының ауылдық округтерінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '164006000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/191132/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191132/rus/28.12.2023
