act_code: '16151'
requisite: Решение маслихата Павлодарской области от 25 апреля 2003 года № 120/26. Зарегистрировано Управлением юстиции Павлодарской области 15 мая 2003 года за № 1792. Утратило силу решением маслихата Павлодарской области от 23 апреля 2004 года № 31/4
title:
  rus: Об областной комплексной целевой программе по защите населения от туберкулеза на 2003 год
  kaz: Халықты туберкулезден қорғаудың 2003 жылға арналған облыстық кешенді мақсатты бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-04-24
approved_by:
- '164000000002'
version_date:
  kaz: 2003-04-24
  rus: 2003-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/16151/kaz/24.04.2003
  rus: https://zan.gov.kz/client/#!/doc/16151/rus/24.04.2003
