act_code: '145099'
requisite: Решение акима Панфиловского сельского округа Иртышского района Павлодарской области от 23 июля 2020 года № 6. Зарегистрировано Департаментом юстиции Павлодарской области 24 июля 2020 года № 6867
title:
  rus: О переименовании некоторых улиц села Агашорын Агашорынского сельского округа Иртышского района
  kaz: Ертіс ауданы Ағашорын ауылдық округі Ағашорын ауылының кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-23
approved_by:
- '164007003002'
version_date:
  kaz: 2020-07-23
  rus: 2020-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/145099/kaz/23.07.2020
  rus: https://zan.gov.kz/client/#!/doc/145099/rus/23.07.2020
