act_code: '61091'
requisite: Павлодар облысы Лебяжі ауданы Майқарағай ауылдық округ әкімінің 2011 жылғы 28 қыркүйектегі № 06 шешімі. Павлодар облысы Лебяжі аудандық Әділет басқармасында 2011 жылғы 03 қарашада № 12-9-142 тіркелді
title:
  rus: Лебяжі ауданы Майқарағай ауылдық округіне қарасты Майқарағай ауылы мен Мерғалым ауылының көше атауларын бекіту туралы
  kaz: Лебяжі ауданы Майқарағай ауылдық округіне қарасты Майқарағай ауылы мен Мерғалым ауылының көше атауларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-09-28
approved_by:
- '164009009001'
version_date:
  kaz: 2011-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/61091/kaz/28.09.2011
