act_code: '3133'
requisite: Павлодар облыстық мәслихаттың 1999 жылғы 23 сәуірдегі XXV сессия, I шақырылым шешімі. Павлодар облысының Әділет басқармасында 1999 жылғы 3 маусымда № 168 тіркелді
title:
  rus: Павлодар облысында шағын кәсіпкерлікті дамыту және мемлекеттік қолдаудың 1999 – 2000 жылдарға арналған Бағдарламасы туралы
  kaz: Павлодар облысында шағын кәсіпкерлікті дамыту және мемлекеттік қолдаудың 1999 – 2000 жылдарға арналған Бағдарламасы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-04-22
approved_by:
- '164000000002'
version_date:
  kaz: 1999-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3133/kaz/22.04.1999
