act_code: '16293'
requisite: Решение маслихата Павлодарской области от 30 декабря 2002 года № 94/24. Зарегистрировано Департаментом юстиции Павлодарской области 22 января 2008 года за № 1600. Утратило силу решением Павлодарского областного маслихата от 23 февраля 2021 года № 10/2-VII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О проектах (схемах) зонирования территорий и районов области
  kaz: Облыс қалалары мен аудандары жерлерін аймақтарға бөлу жобалары (сұлбалары) туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2002-12-30
approved_by:
- '164000000002'
version_date:
  kaz: 2002-12-30
  rus: 2002-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/16293/kaz/30.12.2002
  rus: https://zan.gov.kz/client/#!/doc/16293/rus/30.12.2002
