act_code: '49705'
requisite: Решение маслихата Качирского района Павлодарской области от 25 декабря 2009 года № 1/19. Зарегистрировано Управлением юстиции Качирского района Павлодарской области 31 декабря 2009 года № 12-8-80
title:
  rus: О бюджете района на 2010 - 2012 годы
  kaz: 2010 - 2012 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '164008000002'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49705/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49705/rus/25.12.2009
