act_code: '87355'
requisite: Решение маслихата Майского района Павлодарской области от 19 февраля 2015 года № 3/46. Зарегистрировано Департаментом юстиции Павлодарской области 10 марта 2015 года № 4342. Утратило силу решением маслихата Майского района Павлодарской области от 16 марта 2016 года N 1/60 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании проведения мирных собраний, митингов, шествий, пикетов и демонстраций на территории населенных пунктов Майского района
  kaz: Май ауданы елді мекендер аумағында бейбіт жиналыстар, митингілер, шерулер, пикеттер және демонстрациялар өткізуді қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-19
approved_by:
- '164010000002'
version_date:
  kaz: 2015-02-19
  rus: 2015-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/87355/kaz/19.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87355/rus/19.02.2015
