act_code: '96981'
requisite: Решение маслихата города Аксу Павлодарской области от 22 декабря 2015 года № 395/52. Зарегистрировано Департаментом юстиции Павлодарской области 30 декабря 2015 года № 4874. Утратило силу решением маслихата города Аксу Павлодарской области от 15 марта 2017 года № 97/11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О бюджете города Аксу на 2016 - 2018 годы
  kaz: 2016 - 2018 жылдарға арналған Ақсу қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-22
approved_by:
- '164004000002'
version_date:
  kaz: 2016-08-10
  rus: 2016-08-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/96981/kaz/10.08.2016
  rus: https://zan.gov.kz/client/#!/doc/96981/rus/10.08.2016
caused_by:
  code: '105920'
  requisite: Решение маслихата города Аксу Павлодарской области от 10 августа 2016 года № 46/6. Зарегистрировано Департаментом юстиции Павлодарской области 31 августа 2016 года № 5228. Утратило силу решением маслихата города Аксу Павлодарской области от 15 марта 2017 года № 97/11 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аксуского городского маслихата (LII сессия, V созыв) от 22 декабря 2015 года  № 395/52 «О бюджете города Аксу на 2016 - 2018 годы»
    kaz: Ақсу қалалық мәслихатының (V сайланған LII сессиясы) 2015 жылғы 22 желтоқсандағы «2016 - 2018 жылдарға арналған Ақсу қаласының бюджеті туралы» № 395/52 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/105920/rus
