act_code: '188544'
requisite: Решение Иртышского районного маслихата Павлодарской области от 10 ноября 2023 года № 35-10-8. Зарегистрировано в Департаменте юстиции Павлодарской области 17 ноября 2023 года № 7414-14. Утратило силу решением Иртышского районного маслихата Павлодарской области от 9 июня 2026 года № 175-57-8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Иртышского района
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Ертіс ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-10
approved_by:
- '164007000002'
version_date:
  kaz: 2023-11-10
  rus: 2023-11-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/188544/kaz/10.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188544/rus/10.11.2023
