act_code: '71578'
requisite: Решение маслихата Павлодарской области от 20 февраля 2013 года № 133/15. Зарегистрировано Департаментом юстиции Павлодарской области 14 марта 2013 года № 3484
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников на 2013 год по Павлодарской области
  kaz: Павлодар облысы бойынша 2013 жылға арналған жерүсті су көздерінің ресурстарын пайдаланғаны үшін төленетін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-02-20
approved_by:
- '164000000002'
version_date:
  kaz: 2013-02-20
  rus: 2013-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/71578/kaz/20.02.2013
  rus: https://zan.gov.kz/client/#!/doc/71578/rus/20.02.2013
