act_code: '194882'
requisite: Решение Павлодарского районного маслихата Павлодарской области от 27 марта 2024 года № 15/137. Зарегистрировано в Департаменте юстиции Павлодарской области 28 марта 2024 года № 7523-14. Утратило силу решением Павлодарского районного маслихата Павлодарской области от 12 мая 2026 года № 46/383 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Павлодарском районе
  kaz: Павлодар ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салықтар мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '164014000002'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/194882/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194882/rus/27.03.2024
