act_code: '192530'
requisite: Решение маслихата района Аққулы Павлодарской области от 8 января 2024 года № 65/16. Зарегистрировано в Департаменте юстиции Павлодарской области 15 января 2024 года № 7459-14. Утратило силу решением маслихата района Аққулы Павлодарской области от 3 июля 2026 года № 205/48 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан района Аққулы
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және Аққулы ауданының мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-01-08
approved_by:
- '164009000002'
version_date:
  kaz: 2024-01-08
  rus: 2024-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/192530/kaz/08.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192530/rus/08.01.2024
