act_code: '111313'
requisite: Решение маслихата города Экибастуза Павлодарской области от 17 марта 2017 года № 110/15. Зарегистрировано Департаментом юстиции Павлодарской области 11 апреля 2017 года № 5454
title:
  rus: О признании утратившим силу решения маслихата города Экибастуза (очередная XXX сессия, V созыв) от 4 июля 2014 года № 243/30 «О Правилах предоставления жилищной помощи малообеспеченным семьям (гражданам) по городу Экибастузу»
  kaz: Екібастұз қалалық мәслихатының (V шақырылған кезекті ХХХ сессиясы) 2014 жылғы 4 шілдедегі «Екібастұз қаласы бойынша аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету Ережесі туралы» № 243/30 шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-03-17
approved_by:
- '164013000002'
version_date:
  kaz: 2017-03-17
  rus: 2017-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/111313/kaz/17.03.2017
  rus: https://zan.gov.kz/client/#!/doc/111313/rus/17.03.2017
