act_code: '10904'
requisite: Решение Маслихата Павлодарской области от 31 октября 2001 года ХҮ сессия, ІІ созыв. Зарегистрировано Управлением юстиции Павлодарской области 30 ноября 2001 года за № 965
title:
  rus: О программе совершенствования первичной медико-санитарной помощи в системе здравоохранения области на 2002 - 2003 годы
  kaz: Облыс денсаулық сақтау жүйесінде бастапқы медициналық-санитарлық қөмек көрсетуді жетілдірудің 2002 - 2003 жылдарға арналған бағдарламасы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-10-31
approved_by:
- '164000000002'
version_date:
  kaz: 2001-10-31
  rus: 2001-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/10904/kaz/31.10.2001
  rus: https://zan.gov.kz/client/#!/doc/10904/rus/31.10.2001
