act_code: '230032'
requisite: Решение маслихата района Тереңкөл Павлодарской области от 31 августа 2026 года № 4/51
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат маслихата района Тереңкөл»
  kaz: «Тереңкөл аудандық мәслихатының аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-08-31
approved_by:
- '164008000002'
version_date:
  kaz: 2026-08-31
  rus: 2026-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/230032/kaz/31.08.2026
  rus: https://zan.gov.kz/client/#!/doc/230032/rus/31.08.2026
