act_code: '117814'
requisite: Решение маслихата Успенского района Павлодарской области от 27 декабря 2017 года № 113/24. Зарегистрировано Департаментом юстиции Павлодарской области 9 января 2018 года № 5793
title:
  rus: О бюджете Успенского сельского округа Успенского района на 2018 - 2020 годы
  kaz: 2018 - 2020 жылдарға арналған Успен ауданы Успен ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '164011000002'
version_date:
  kaz: 2018-08-09
  rus: 2018-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/117814/kaz/09.08.2018
  rus: https://zan.gov.kz/client/#!/doc/117814/rus/09.08.2018
caused_by:
  code: '124493'
  requisite: Решение маслихата Успенского района Павлодарской области от 9 августа 2018 года № 170/35. Зарегистрировано Департаментом юстиции Павлодарской области 11 сентября 2018 года № 6056
  title:
    rus: О внесении изменений и дополнения в решение Успенского районного маслихата от 27 декабря 2017 года № 113/24 «О бюджете Успенского сельского округа Успенского района на 2018 - 2020 годы»
    kaz: Успен аудандық мәслихатының 2017 жылғы 27 желтоқсандағы «2018 - 2020 жылдарға арналған Успен ауданы Успен ауылдық округінің бюджеті туралы» № 113/24 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124493/rus
