act_code: '189780'
requisite: Решение Баянаульского районного маслихата Павлодарской области от 8 декабря 2023 года № 78/10. Зарегистрировано в Департаменте юстиции Павлодарской области 11 декабря 2023 года № 7441-14
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Баянаульском районе
  kaz: Баянауыл ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-08
approved_by:
- '164005000002'
version_date:
  kaz: 2023-12-08
  rus: 2023-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/189780/kaz/08.12.2023
  rus: https://zan.gov.kz/client/#!/doc/189780/rus/08.12.2023
