act_code: '36104'
requisite: Решение акима Иртышского района Павлодарской области от 19 ноября 2007 года № 9. Зарегистрировано Управлением юстиции Павлодарской области 06 декабря 2007 года № 12-7-58
title:
  rus: О проведении приписки граждан 1991 года рождения
  kaz: 1991 жылы туған азаматтардың жазуын өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-11-19
approved_by:
- '164007000003'
version_date:
  kaz: 2007-11-19
  rus: 2007-11-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/36104/kaz/19.11.2007
  rus: https://zan.gov.kz/client/#!/doc/36104/rus/19.11.2007
