act_code: '66401'
requisite: Павлодар облысы Баянауыл ауданы Майқайың кенті әкімінің 2012 жылғы 18 маусымдағы № 42 шешімі. Павлодар облысы Баянауыл аудандық Әділет басқармасында 2012 жылғы 27 маусымда № 12-5-110 тіркелді
title:
  rus: Баянауыл ауданы Майқайың кентінің көшесін өзгерту туралы
  kaz: Баянауыл ауданы Майқайың кентінің көшесін өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-07-18
approved_by:
- '164005001001'
version_date:
  kaz: 2012-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/66401/kaz/18.06.2012
