act_code: '133092'
requisite: Решение маслихата Щербактинского района Павлодарской области от 2 июля 2019 года № 198/59. Зарегистрировано Департаментом юстиции Павлодарской области 4 июля 2019 года № 6464
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Щербактинскому району на 2019 – 2020 годы
  kaz: Шарбақты ауданы бойынша 2019 – 2020 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
- СХЕМ
approved_on: 2019-07-02
approved_by:
- '164012000002'
version_date:
  kaz: 2019-07-02
  rus: 2019-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/133092/kaz/02.07.2019
  rus: https://zan.gov.kz/client/#!/doc/133092/rus/02.07.2019
