act_code: '229264'
requisite: Решение Павлодарского областного маслихата от 21 августа 2026 года № 296/33
title:
  rus: Об утверждении правил присвоения звания «Почетный гражданин Павлодарской области (города, района)»
  kaz: «Павлодар облысының (қаласының, ауданының) құрметті азаматы» атағын берудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-08-21
approved_by:
- '164000000002'
version_date:
  kaz: 2026-08-21
  rus: 2026-08-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/229264/kaz/21.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229264/rus/21.08.2026
