act_code: '94066'
requisite: Решение маслихата города Экибастуза Павлодарской области от 11 сентября 2015 года № 345/41. Зарегистрировано Департаментом юстиции Павлодарской области 28 сентября 2015 года № 4731. Утратило силу решением маслихата города Экибастуза Павлодарской области от 23 января 2018 года № 225/26 (вступает в силу по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении регламента Экибастузского городского маслихата
  kaz: Екібастұз қаласы мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2015-09-11
approved_by:
- '164013000002'
version_date:
  kaz: 2015-09-11
  rus: 2015-09-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/94066/kaz/11.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94066/rus/11.09.2015
